/**
 * Ninety checked facts about Durga Puja, from the Devi Mahatmya to
 * the UNESCO inscription. Each carries the source it came from.
 *
 * Generated from research/facts.json. Where historians disagree, the
 * disagreement is stated inside the fact rather than smoothed over.
 */

export type Era =
  | "Ancient"
  | "Medieval"
  | "Colonial"
  | "Modern"
  | "Contemporary";

export type Fact = {
  id: string;
  era: Era;
  year: string | null;
  title: string;
  fact: string;
  bangla: string;
  source: string;
  tags: string[];
};

export const ERAS: Era[] = [
  "Ancient",
  "Medieval",
  "Colonial",
  "Modern",
  "Contemporary",
];

export const FACTS: Fact[] = [
  {
    id: "devi-mahatmya-is-chapters-81-93",
    era: "Ancient",
    year: "c. 400-600 CE",
    title: "The Chandi is a chapter, not a book",
    fact: "The Devi Mahatmya is not an independent scripture. It is chapters 81 to 93 of the Markandeya Purana, inserted into a far older text somewhere between 400 and 600 CE. Wendy Doniger dates the insertion to about 550 CE and the surrounding Purana to about 250 CE.",
    bangla: "দেবীমাহাত্ম্য আসলে স্বতন্ত্র কোনো শাস্ত্র নয়। এটি মার্কণ্ডেয় পুরাণের ৮১ থেকে ৯৩ অধ্যায়, যা ৪০০ থেকে ৬০০ খ্রিস্টাব্দের মধ্যে অনেক পুরোনো একটি পুরাণের ভিতরে সংযোজিত হয়েছিল। ওয়েন্ডি ডনিগার এই সংযোজনকে আনুমানিক ৫৫০ এবং বাকি পুরাণটিকে আনুমানিক ২৫০ খ্রিস্টাব্দে স্থাপন করেন।",
    source: "Wikipedia: Devi Mahatmya",
    tags: ["scripture", "chandi", "dating"],
  },
  {
    id: "dadhimati-inscription-608",
    era: "Ancient",
    year: "608 CE",
    title: "Carved proof from a Rajasthan wall",
    fact: "The oldest hard evidence for the Devi Mahatmya is not a manuscript but a wall. The Dadhimati Mata temple inscription in Rajasthan, dated 608 CE, quotes the text directly, so it was already scriptural within a century of composition.",
    bangla: "দেবীমাহাত্ম্যের প্রাচীনতম নিশ্চিত প্রমাণ কোনো পুঁথি নয়, একটি মন্দিরের দেয়াল। রাজস্থানের দধিমতী মাতা মন্দিরের ৬০৮ খ্রিস্টাব্দের শিলালিপিতে গ্রন্থটি সরাসরি উদ্ধৃত হয়েছে, অর্থাৎ রচনার এক শতাব্দীর মধ্যেই তা শাস্ত্রের মর্যাদা পেয়ে গিয়েছিল।",
    source: "Wikipedia: Devi Mahatmya",
    tags: ["epigraphy", "scripture", "archaeology"],
  },
  {
    id: "first-puja-two-bankrupts",
    era: "Ancient",
    year: null,
    title: "The first worshippers were two ruined men",
    fact: "In the Devi Mahatmya's frame story the first Durga Puja is performed by a deposed king, Suratha, and a merchant, Samadhi, cheated by his own wife and sons. At the sage Medhas's hermitage they make a clay image on a riverbank and worship it.",
    bangla: "দেবীমাহাত্ম্যের কাহিনি-কাঠামোয় প্রথম দুর্গাপূজা করেন রাজ্যচ্যুত রাজা সুরথ এবং নিজের স্ত্রী-পুত্রের দ্বারা প্রতারিত বণিক সমাধি। মেধস মুনির আশ্রমে নদীতীরে মাটির প্রতিমা গড়ে তাঁরা দেবীর আরাধনা করেন।",
    source: "Devi Mahatmya / Markandeya Purana",
    tags: ["scripture", "origins", "suratha"],
  },
  {
    id: "basanti-is-the-original",
    era: "Ancient",
    year: null,
    title: "Spring, not autumn, is canonical",
    fact: "Scripture places Suratha's worship in Chaitra, which makes Basanti Puja the timely one and the autumn festival the untimely exception. A ritual trace survives, in Basanti Puja no ghat is installed on Shashthi, because no awakening is needed.",
    bangla: "শাস্ত্রে সুরথের পূজা চৈত্র মাসে স্থাপিত, ফলে বাসন্তী পূজাই যথাকালের পূজা আর শারদীয়া উৎসবই ব্যতিক্রম। একটি আচারগত চিহ্ন আজও টিকে আছে, বাসন্তী পূজায় ষষ্ঠীতে ঘট বসে না, কারণ সেখানে বোধনের প্রয়োজন নেই।",
    source: "India TV / The Statesman on Basanti Puja",
    tags: ["basanti", "ritual", "calendar"],
  },
  {
    id: "rigveda-durga-not-buffalo-slayer",
    era: "Ancient",
    year: null,
    title: "The oldest Durga killed nobody",
    fact: "The word Durga appears in six Rigvedic hymns and a deity Durgi in the Taittiriya Aranyaka, but none of these is the buffalo-slayer. The name is far older than the goddess we picture.",
    bangla: "ঋগ্বেদের ছয়টি সূক্তে 'দুর্গা' শব্দটি এবং তৈত্তিরীয় আরণ্যকে 'দুর্গী' নামের এক দেবতার উল্লেখ আছে, কিন্তু এঁদের কেউই মহিষাসুরমর্দিনী নন। নামটি আমাদের চেনা দেবীমূর্তির চেয়ে অনেক বেশি প্রাচীন।",
    source: "Wikipedia: Durga Puja",
    tags: ["vedic", "origins", "scripture"],
  },
  {
    id: "arjuna-durga-stotra-mahabharata",
    era: "Ancient",
    year: null,
    title: "Arjuna hymns Durga before battle",
    fact: "In Bhishma Parva chapter 23 of the Mahabharata, Krishna tells Arjuna to invoke Durga before the war; Arjuna steps down from his chariot and praises her. Most scholars read this hymn, like Yudhishthira's parallel prayer in the Virata Parva, as a late interpolation roughly contemporary with the Puranic goddess tradition rather than older than it.",
    bangla: "মহাভারতের ভীষ্মপর্বের ২৩ অধ্যায়ে কৃষ্ণ অর্জুনকে যুদ্ধের আগে দুর্গার স্তব করতে বলেন; অর্জুন রথ থেকে নেমে স্তুতি করেন। তবে অধিকাংশ পণ্ডিতের মতে এই স্তোত্র, বিরাটপর্বে যুধিষ্ঠিরের সমান্তরাল স্তবের মতোই, পরবর্তী সংযোজন, পৌরাণিক দেবী-ঐতিহ্যের প্রায় সমকালীন, তার আগের নয়।",
    source: "Mahabharata, Bhishma Parva 23; Pradip Bhattacharya on the Clay Sanskrit Library edition",
    tags: ["epic", "origins", "scripture"],
  },
  {
    id: "nagar-terracotta-earliest",
    era: "Ancient",
    year: "1st c. BCE - 1st c. CE",
    title: "The oldest Mahishasuramardini is Rajasthani",
    fact: "The earliest known images of Durga slaying the buffalo are terracotta plaques from Nagar in Rajasthan, dated to the 1st century BCE to 1st century CE, evidence of goddess worship there before the Kushans.",
    bangla: "মহিষাসুরমর্দিনীর প্রাচীনতম জ্ঞাত মূর্তি রাজস্থানের নাগর থেকে পাওয়া পোড়ামাটির ফলক, যেগুলির কাল খ্রিস্টপূর্ব প্রথম থেকে খ্রিস্টীয় প্রথম শতক, কুষাণ যুগের আগেই সেখানে শাক্ত উপাসনার প্রমাণ।",
    source: "Centre for Soft Power",
    tags: ["archaeology", "iconography", "earliest"],
  },
  {
    id: "udayagiri-cave-six-401",
    era: "Ancient",
    year: "401 CE",
    title: "A twelve-armed Durga dated by inscription",
    fact: "Cave 6 at Udayagiri near Vidisha holds a multi-armed Durga treading on the buffalo's head, beside an inscription of Chandragupta II dated Gupta year 82, equal to 401 CE, among the earliest securely datable images of the theme in India.",
    bangla: "বিদিশার কাছে উদয়গিরির ৬ নম্বর গুহায় আছে বহুভুজা দুর্গা, মহিষের মাথায় পা রেখে দাঁড়িয়ে, পাশেই দ্বিতীয় চন্দ্রগুপ্তের শিলালিপি, গুপ্তাব্দ ৮২ অর্থাৎ ৪০১ খ্রিস্টাব্দ, ভারতে এই বিষয়ের প্রাচীনতম নিশ্চিতভাবে তারিখযুক্ত মূর্তিগুলির একটি।",
    source: "Wikipedia, Udayagiri Caves",
    tags: ["archaeology", "gupta", "iconography"],
  },
  {
    id: "pala-sena-bengal-durgas",
    era: "Medieval",
    year: "8th-12th c.",
    title: "Bengal's stone goddesses came first",
    fact: "Pala and Sena Bengal produced Mahishasuramardini images in stone and brass in quantity, concentrated in the old districts of Dhaka, Faridpur, Tipperah and Bakarganj, where they served as family and village deities long before any zamindar's festival.",
    bangla: "পাল ও সেন যুগের বাংলায় পাথর ও পিতলে বহু মহিষাসুরমর্দিনী মূর্তি তৈরি হয়েছিল, বিশেষত ঢাকা, ফরিদপুর, ত্রিপুরা ও বাখরগঞ্জ অঞ্চলে, যেখানে কোনো জমিদারি উৎসবের বহু আগেই এঁরা কুলদেবতা ও গ্রামদেবতা হিসেবে পূজিত হতেন।",
    source: "Heritage University of Kerala journal; Met Museum",
    tags: ["archaeology", "bengal", "pala-sena"],
  },
  {
    id: "kalika-purana-blood-chapter",
    era: "Medieval",
    year: "c. 10th-11th c.",
    title: "The blood chapter that forbids itself",
    fact: "The Kalika Purana's Rudhiradhyaya, its 'blood chapter', is the rare Puranic text to discuss human sacrifice, and it hedges the practice about with conditions until almost nothing is left of it. It may be done only with a prince's consent, and only before a war or in imminent danger. Anyone physically disabled, anyone related to a Brahmin, and anyone unwilling to die is unfit for it.",
    bangla: "কালিকাপুরাণের রুধিরাধ্যায় অর্থাৎ 'রক্তের অধ্যায়' সেই বিরল পুরাণ-অংশ যেখানে নরবলির আলোচনা আছে, কিন্তু শর্তের ভারে তা কার্যত অসম্ভব করে তোলা হয়েছে। রাজপুত্রের সম্মতি ছাড়া হবে না, আর তা-ও কেবল যুদ্ধের আগে বা আসন্ন বিপদের সময়ে। শারীরিক প্রতিবন্ধী, ব্রাহ্মণের আত্মীয়, আর মরতে অনিচ্ছুক — এরা কেউই এই আচারের যোগ্য নয়।",
    source: "Wikipedia, Kalika Purana; Wisdomlib",
    tags: ["scripture", "sacrifice", "kalika-purana"],
  },
  {
    id: "akalbodhan-not-in-valmiki",
    era: "Medieval",
    year: "15th c.",
    title: "Rama's autumn puja is not in Valmiki",
    fact: "The story of Rama waking Durga out of season to defeat Ravana, the Akalbodhan on which all of Bengal's autumn festival rests, does not appear in Valmiki's Ramayana. It reaches Bengal through the Kalika Purana and, decisively, through Krittibas Ojha.",
    bangla: "রাবণবধের জন্য রামচন্দ্রের অকালে দুর্গাকে জাগানোর কাহিনি, যে অকালবোধনের উপর গোটা বাঙালির শারদোৎসব দাঁড়িয়ে, বাল্মীকি রামায়ণে নেই। এটি বাংলায় এসেছে কালিকাপুরাণ হয়ে, আর নির্ণায়কভাবে কৃত্তিবাস ওঝার হাত ধরে।",
    source: "Wikipedia, Akalabodhana; Krittibas Ojha",
    tags: ["akalbodhan", "krittibas", "correction"],
  },
  {
    id: "krittibas-108-lotuses",
    era: "Medieval",
    year: "15th c.",
    title: "The hundred and eighth lotus",
    fact: "In the Bengali telling, Rama must offer 108 blue lotuses; one vanishes, and Rama, called Padmalochana, lotus-eyed, reaches to offer one of his own eyes instead. The goddess stops his hand. This scene is Bengali, not Sanskrit.",
    bangla: "বাংলা কাহিনিতে রামকে ১০৮টি নীলপদ্ম নিবেদন করতে হয়; একটি পদ্ম হারিয়ে যায়, আর পদ্মলোচন রাম নিজের একটি চোখই অর্ঘ্য দিতে উদ্যত হন। দেবী তাঁর হাত ধরে ফেলেন। এই দৃশ্য বাংলার, সংস্কৃত রামায়ণের নয়।",
    source: "Krittivasi Ramayan tradition",
    tags: ["akalbodhan", "krittibas", "story"],
  },
  {
    id: "krittibas-text-is-colonial-print",
    era: "Colonial",
    year: "early 1800s",
    title: "The 15th-century text we read is 19th-century",
    fact: "Krittibas lived c. 1381-1461, but the Krittivasi Ramayan everyone quotes is the recension edited by Jaygopal Tarkalankar and printed at the Serampore Mission Press in the early nineteenth century. Manuscript versions differ substantially.",
    bangla: "কৃত্তিবাসের জীবৎকাল আনুমানিক ১৩৮১–১৪৬১, কিন্তু আজ সবাই যে কৃত্তিবাসী রামায়ণ উদ্ধৃত করেন তা জয়গোপাল তর্কালঙ্কার সম্পাদিত এবং ঊনবিংশ শতকের গোড়ায় শ্রীরামপুর মিশন প্রেস থেকে ছাপা পাঠ। পুঁথির পাঠান্তরগুলি যথেষ্ট আলাদা।",
    source: "Wikipedia, Krittibas Ojha",
    tags: ["krittibas", "textual-history", "caveat"],
  },
  {
    id: "medieval-ritual-digests",
    era: "Medieval",
    year: "c. 1375-1575",
    title: "A rulebook before the first zamindar",
    fact: "Three Sanskrit digests codified the Bengali rite long before any landlord's spectacle, Shulapani's Durgotsavaviveka, Vidyapati's Durgabhaktitarangini, and Raghunandana Bhattacharya's Durgapujatattva, which effectively standardised practice.",
    bangla: "কোনো জমিদারি জাঁকজমকের বহু আগেই তিনটি সংস্কৃত নিবন্ধ বাঙালির পূজাপদ্ধতিকে বিধিবদ্ধ করেছিল, শূলপাণির দুর্গোৎসববিবেক, বিদ্যাপতির দুর্গাভক্তিতরঙ্গিণী এবং রঘুনন্দন ভট্টাচার্যের দুর্গাপূজাতত্ত্ব, যা কার্যত আচারকে প্রমিত রূপ দেয়।",
    source: "Bihani Sarkar, JRAS 22.2 (2012)",
    tags: ["ritual-texts", "medieval-bengal", "scholarship"],
  },
  {
    id: "bishnupur-mrinmoyee-997",
    era: "Medieval",
    year: "997 CE (traditional)",
    title: "Bengal's oldest claim is a clay goddess",
    fact: "The Mrinmoyee temple at Bishnupur claims a Durga Puja running since 997 CE, founded by the Malla king Jagat Malla. The 2023 festival was billed as its 1,027th, though the date is dynastic tradition, not epigraphy.",
    bangla: "বিষ্ণুপুরের মৃন্ময়ী মন্দিরের দাবি, মল্লরাজ জগৎ মল্লের প্রতিষ্ঠিত সেই পূজা ৯৯৭ খ্রিস্টাব্দ থেকে অব্যাহত। ২০২৩ সালের উৎসবকে ১০২৭তম বর্ষ বলা হয়েছিল, যদিও তারিখটি রাজবংশীয় ঐতিহ্য, শিলালিপি-প্রমাণিত নয়।",
    source: "Wikipedia, Mrinmoyee Temple; 30Stades",
    tags: ["bishnupur", "oldest", "contested"],
  },
  {
    id: "taherpur-kangshanarayan",
    era: "Medieval",
    year: "c. 1580",
    title: "The most-repeated 'first' puja",
    fact: "Raja Kangshanarayan of Taherpur, in what is now Bangladesh, is the figure most often credited with the first grand autumn Durga Puja, reportedly spending over eight lakh rupees. Dates in the sources range from 1480 to 1606, and historians reject the claim that he invented the rite.",
    bangla: "বর্তমান বাংলাদেশের তাহেরপুরের রাজা কংসনারায়ণকেই সাধারণত প্রথম জাঁকালো শারদীয় দুর্গাপূজার কৃতিত্ব দেওয়া হয়; খরচ নাকি আট লক্ষ টাকারও বেশি। কিন্তু সূত্রভেদে তারিখ ১৪৮০ থেকে ১৬০৬ পর্যন্ত ছড়ানো, আর ঐতিহাসিকেরা তাঁকে পূজার উদ্ভাবক মানেন না।",
    source: "The Business Standard; Amarpujo",
    tags: ["origins", "bengal", "contested"],
  },
  {
    id: "bhabananda-nadia-1606",
    era: "Medieval",
    year: "1606",
    title: "The Nadia Raj began with a puja",
    fact: "Bhabananda Majumdar founded the Nadia Raj in 1606 under Jahangir and began a celebrated Durga Puja at his capital, Matiyari. His descendant Raja Krishnachandra Roy, who ruled 1728-1782, moved the seat to Krishnanagar and expanded the puja into one of Bengal's grandest.",
    bangla: "জাহাঙ্গিরের আমলে ১৬০৬ সালে ভবানন্দ মজুমদার নদিয়া রাজ প্রতিষ্ঠা করেন এবং তাঁর রাজধানী মাটিয়ারিতে খ্যাতনামা দুর্গাপুজো শুরু করেন। তাঁর বংশধর রাজা কৃষ্ণচন্দ্র রায় (১৭২৮-১৭৮২) রাজধানী কৃষ্ণনগরে সরিয়ে আনেন, আর পুজোকে বাংলার অন্যতম জাঁকজমকপূর্ণ উৎসবে পরিণত করেন।",
    source: "Wikipedia: Nadia Raj; GetBengal on Matiyari",
    tags: ["origins", "nadia", "bengal"],
  },
  {
    id: "sabarna-1610-barisha",
    era: "Medieval",
    year: "1610",
    title: "Kolkata's oldest puja is 1610",
    fact: "Lakshmikanta Gangopadhyay Majumdar and his wife Bhagawati Devi began the Sabarna Roy Choudhury Durga Puja at the Barisha Atchala in 1610. It has run continuously ever since and is now spread across eight locations.",
    bangla: "লক্ষ্মীকান্ত গঙ্গোপাধ্যায় মজুমদার ও তাঁর স্ত্রী ভগবতী দেবী ১৬১০ সালে বড়িশার আটচালায় সাবর্ণ রায়চৌধুরী পরিবারের দুর্গাপূজা শুরু করেন। সেই থেকে তা অবিচ্ছিন্নভাবে চলছে এবং এখন আটটি জায়গায় ছড়িয়ে পড়েছে।",
    source: "Millennium Post; Wikipedia, Sabarna Roy Choudhury",
    tags: ["kolkata", "bonedi-bari", "oldest"],
  },
  {
    id: "sabarna-sold-calcutta",
    era: "Colonial",
    year: "1698",
    title: "The family that leased away Calcutta",
    fact: "The Sabarna Roy Choudhurys, whose 1610 puja is widely regarded as Kolkata's oldest, are the family from whom the East India Company obtained the lease of Sutanuti, Gobindapur and Kalikata, the three villages that became the city.",
    bangla: "যে সাবর্ণ রায়চৌধুরী পরিবারের ১৬১০ সালের পূজা কলকাতার প্রাচীনতম, ইস্ট ইন্ডিয়া কোম্পানি সেই পরিবারের কাছ থেকেই সুতানুটি, গোবিন্দপুর ও কলিকাতা, এই তিন গ্রামের ইজারা নিয়েছিল, যা মিলে শহরটি গড়ে ওঠে।",
    source: "Wikipedia, Sabarna Roy Choudhury",
    tags: ["kolkata", "colonial", "history"],
  },
  {
    id: "nabakrishna-deb-1757",
    era: "Colonial",
    year: "1757",
    title: "The puja that followed Plassey",
    fact: "Nabakrishna Deb, later Robert Clive's Persian munshi, began building Shobhabazar Rajbari in 1757 and started its Durga Puja the same year, weeks after the Battle of Plassey. It set the template for the Calcutta babu's puja.",
    bangla: "রবার্ট ক্লাইভের ফারসি মুনশি নবকৃষ্ণ দেব ১৭৫৭ সালে শোভাবাজার রাজবাড়ি নির্মাণ শুরু করেন এবং পলাশির যুদ্ধের কয়েক সপ্তাহের মধ্যেই সেখানে দুর্গাপূজার সূচনা করেন। কলকাতার বাবু-পূজার আদল তৈরি হয় এখান থেকেই।",
    source: "Wikipedia, Nabakrishna Deb; Shobhabazar Rajbari",
    tags: ["colonial", "company-puja", "shobhabazar"],
  },
  {
    id: "clive-story-probably-false",
    era: "Colonial",
    year: "1757",
    title: "Clive probably never came",
    fact: "The famous tale that Robert Clive gave thanks to Durga at Shobhabazar after Plassey is very likely invented. Deb became Clive's munshi only after 1757, and the story rests on a single anonymous painting.",
    bangla: "পলাশির পরে রবার্ট ক্লাইভ শোভাবাজারে দুর্গার কাছে কৃতজ্ঞতা জানিয়েছিলেন, এই বিখ্যাত গল্পটি সম্ভবত বানানো। নবকৃষ্ণ ক্লাইভের মুনশি হন ১৭৫৭-এর পরে, আর গল্পটির একমাত্র ভিত্তি একটি অজ্ঞাতনামা চিত্র।",
    source: "Scroll.in",
    tags: ["colonial", "myth-busting", "company-puja"],
  },
  {
    id: "wellesley-gun-salute-kali",
    era: "Colonial",
    year: "c. 1800",
    title: "A nine-gun salute for Kali",
    fact: "Governor-General Lord Wellesley ordered a nine-gun salute in honour of Kali, and British officials were entertained at Bengali mansions with nautch and alcohol. Conspicuous consumption, not bhakti, was the central motif.",
    bangla: "গভর্নর-জেনারেল লর্ড ওয়েলেসলি কালীর সম্মানে নয়টি কামানের তোপধ্বনির নির্দেশ দিয়েছিলেন, আর বাঙালি বাবুদের বাড়িতে সাহেবদের আপ্যায়ন হত নাচ ও মদ দিয়ে। মূল সুর ছিল ভক্তি নয়, প্রদর্শনী-খরচ।",
    source: "Scroll.in, citing Tapan Raychaudhuri",
    tags: ["colonial", "company-puja", "babu-culture"],
  },
  {
    id: "seven-thousand-idols-1839",
    era: "Colonial",
    year: "1839",
    title: "Seven thousand goddesses a year",
    fact: "In 1839 alone, the Friend of India reported roughly seven thousand Durga images made in Calcutta, a scale of ritual manufacture that already anticipated the modern festival.",
    bangla: "শুধু ১৮৩৯ সালেই কলকাতায় প্রায় সাত হাজার দুর্গাপ্রতিমা তৈরি হয়েছিল বলে ফ্রেন্ড অফ ইন্ডিয়া জানায়, আচারের এমন উৎপাদনমাত্রা আধুনিক উৎসবের আভাস দেয়।",
    source: "Outlook India, 'Englishmen Bewitched By Durga'",
    tags: ["colonial", "kumartuli", "scale"],
  },
  {
    id: "calcutta-gazette-1814",
    era: "Colonial",
    year: "1814",
    title: "A festival listed in the newspaper",
    fact: "The Calcutta Gazette of 20 October 1814 records, 'The Hindu holidays of the Doorga Poojah began yesterday and will continue until the 25th instant.' The festival was already a fixture of the colonial calendar.",
    bangla: "১৮১৪ সালের ২০ অক্টোবরের ক্যালকাটা গেজেটে লেখা, 'হিন্দুদের দুর্গাপূজার ছুটি গতকাল শুরু হয়েছে এবং চলবে এই মাসের ২৫ তারিখ পর্যন্ত।' উৎসবটি তখনই ঔপনিবেশিক পঞ্জিকার স্থায়ী অঙ্গ।",
    source: "Outlook India, 'Englishmen Bewitched By Durga'",
    tags: ["colonial", "archive", "calcutta"],
  },
  {
    id: "company-ban-1840",
    era: "Colonial",
    year: "1840",
    title: "The ban that was a newspaper column",
    fact: "Everyone repeats that in 1840 the Company forbade its servants from attending the babu Pujas. No such order has been produced. Rachel Fell McDermott's full study of the Bengal goddess festivals records no ban; what it records for 1840 is an attack on European attendance in the Bengal Hurkaru of 7 October, and Europeans still attending as late as 1855. Official unease is real and datable elsewhere, the 1833 despatch, the Lords debate on idolatry in August 1840, the March 1841 order withdrawing troops and gun salutes from Hindu festivals. A press campaign has been promoted into a prohibition.",
    bangla: "সবাই বলে ১৮৪০ সালে কোম্পানি তার কর্মচারীদের বাবুদের পূজায় যাওয়া নিষিদ্ধ করেছিল। এমন কোনও নির্দেশ কেউ দেখাতে পারেননি। ১৮৪০ সালের ৭ অক্টোবর 'বেঙ্গল হরকরা'-য় ইউরোপীয়দের উপস্থিতির বিরুদ্ধে একটি কঠোর লেখা বেরোয়, আর ১৮৫৫ সালেও ইউরোপীয়রা যেতেন। একটি সংবাদপত্রের প্রচারকে নিষেধাজ্ঞা বানানো হয়েছে। রেচেল ফেল ম্যাকডারমটের সমীক্ষায় কোনো নিষেধাজ্ঞার হদিস নেই; সরকারি অস্বস্তি অবশ্য সত্যি এবং অন্যত্র নথিভুক্ত, ১৮৩৩ সালের নির্দেশ, ১৮৪০ সালের অগস্টে লর্ডসে পৌত্তলিকতা নিয়ে বিতর্ক, ১৮৪১ সালের মার্চে হিন্দু উৎসব থেকে সেনা ও তোপধ্বনি প্রত্যাহারের আদেশ।",
    source: "Rachel Fell McDermott, Revelry, Rivalry, and Longing for the Goddesses of Bengal, ch. 2, citing Bengal Hurkaru, 7 October 1840 and 15 October 1855",
    tags: ["colonial", "company-puja", "contested", "myth-checked"],
  },
  {
    id: "guptipara-twelve-friends",
    era: "Colonial",
    year: "1790 (some sources 1761)",
    title: "The first people's puja was not to Durga",
    fact: "Twelve men of Guptipara in Hooghly, shut out of a household Puja, raised a subscription and held their own, and baro plus yaar gave the word baroyari. Two things are usually left out. Rachel Fell McDermott writes that the first recorded baroiyari was performed to Jagaddhatri, not Durga. And Tapati Guha-Thakurta, who tells the story, hedges it throughout as what has often been recounted, without vouching for the date. The most solidly documented case of a community taking over a Puja is not Guptipara at all but Bankura in 1793, where people of every caste applied to the East India Company for permission to collect money and hold one.",
    bangla: "হুগলির গুপ্তিপাড়ায় বারোজন যুবককে জমিদারবাড়ির দুর্গাপূজায় ঢুকতে না দেওয়ায় তাঁরা পাড়া থেকে চাঁদা তুলে বিন্ধ্যবাসিনী মন্দিরে নিজেদের পূজা করেন। 'বারো' আর 'ইয়ার' মিলেই তৈরি হল 'বারোয়ারি' শব্দটি। তবে ইতিহাসবিদদের মতে প্রথম নথিভুক্ত বারোয়ারি ছিল জগদ্ধাত্রীর, দুর্গার নয়; আর সবচেয়ে ভালোভাবে নথিভুক্ত দৃষ্টান্ত বাঁকুড়া, ১৭৯৩।",
    source: "Rachel Fell McDermott, Revelry, Rivalry, and Longing, ch. 1; Tapati Guha-Thakurta, In the Name of the Goddess (Primus, 2015), pp. 92-93",
    tags: ["baroyari", "guptipara", "origins", "contested"],
  },
  {
    id: "bhowanipore-first-baroyari-1909",
    era: "Colonial",
    year: "1909/1910",
    title: "Calcutta's first community puja",
    fact: "The Bhowanipore Sanatan Dharmotsahini Sabha organised Calcutta's first baroyari Durga Puja at Balaram Bose Ghat Road. Sri Aurobindo published his Durga Stotra in his Bengali journal Dharma on the occasion.",
    bangla: "ভবানীপুর সনাতন ধর্মোৎসাহিনী সভা বলরাম বসু ঘাট রোডে কলকাতার প্রথম বারোয়ারি দুর্গাপূজার আয়োজন করে। সেই উপলক্ষেই শ্রীঅরবিন্দ তাঁর বাংলা পত্রিকা 'ধর্ম'-এ বিখ্যাত দুর্গাস্তোত্র প্রকাশ করেন।",
    source: "Wikipedia: Barowari",
    tags: ["baroyari", "kolkata", "swadeshi"],
  },
  {
    id: "baghbazar-1919-broke-family",
    era: "Colonial",
    year: "1919",
    title: "A puja born of bankruptcy",
    fact: "Baghbazar Sarbojanin exists because a family ran out of money. In October 1919 the Sarkars of 55 Baghbazar Street could no longer afford their private puja, so the locality took it over as the Nebubagan Baroyari. It was renamed Baghbazar Sarbojanin in 1926.",
    bangla: "বাগবাজার সর্বজনীনের জন্ম এক পরিবারের সামর্থ্য ফুরিয়ে যাওয়ায়। ১৯১৯ সালের অক্টোবরে ৫৫ নং বাগবাজার স্ট্রিটের সরকার পরিবার আর নিজেদের পূজা চালাতে না পারায় পাড়া তা কাঁধে তুলে নেয় 'নেবুবাগান বারোয়ারি' নামে। ১৯২৬ সালে নাম হয় বাগবাজার সর্বজনীন দুর্গোৎসব।",
    source: "Baghbazar Sarbojanin official site; Wikipedia, Barowari",
    tags: ["sarbojanin", "baghbazar", "origins"],
  },
  {
    id: "bande-mataram-1882",
    era: "Colonial",
    year: "1882",
    title: "The Mother as nation",
    fact: "Bankim Chandra Chattopadhyay wrote Bande Mataram in the 1870s and published it inside Anandamath in 1882. Its Mother draws directly on Durga and Kali; Congress first sang it in 1896, and it became the anthem of the 1905 Swadeshi movement after Bengal was partitioned.",
    bangla: "বঙ্কিমচন্দ্র চট্টোপাধ্যায় ১৮৭০-এর দশকে বন্দে মাতরম লেখেন, ১৮৮২ সালে আনন্দমঠের ভিতরে প্রকাশ করেন। এর মা সরাসরি দুর্গা ও কালীর উপর দাঁড়ানো; কংগ্রেসে প্রথম গাওয়া হয় ১৮৯৬ সালে, আর বঙ্গভঙ্গের পর ১৯০৫ সালের স্বদেশি আন্দোলনের সঙ্গীত হয়ে ওঠে।",
    source: "Wikipedia, Vande Mataram; Bharat Mata",
    tags: ["nationalism", "bankim", "swadeshi"],
  },
  {
    id: "simla-byayam-samity-1926",
    era: "Colonial",
    year: "1926",
    title: "A gymnasium's puja for revolutionaries",
    fact: "The Simla Byayam Samity, a gymnasium of the kind that routinely fronted for revolutionary organisation, began its Durga Puja in 1926 under Atindra Nath Bose, with Vivekananda's brother Mahendranath Dutta. It drew Subhas and Sarat Bose and Bhupendranath Dutta.",
    bangla: "সিমলা ব্যায়াম সমিতি, যে ধরনের আখড়া প্রায়ই বিপ্লবী সংগঠনের আড়াল ছিল, ১৯২৬ সালে অতীন্দ্রনাথ বসুর নেতৃত্বে, বিবেকানন্দের ভাই মহেন্দ্রনাথ দত্তের সহায়তায় দুর্গাপূজা শুরু করে। সেখানে আসতেন সুভাষ ও শরৎচন্দ্র বসু, ভূপেন্দ্রনাথ দত্ত।",
    source: "Millennium Post",
    tags: ["nationalism", "subhas-bose", "kolkata"],
  },
  {
    id: "bose-opened-pandal-to-women",
    era: "Colonial",
    year: "1930s",
    title: "Bose kept the pandal open to everyone",
    fact: "As president of the Simla Byayam Samity's Durga Puja committee, Subhas Chandra Bose carried on the practice the Samity had begun at its founding in 1926, of opening the pandal to women and the general public. He presided over the Kumartuli Sarbojanin committee in 1938.",
    bangla: "সিমলা ব্যায়াম সমিতির দুর্গাপুজো কমিটির সভাপতি হিসেবে সুভাষচন্দ্র বসু সমিতির ১৯২৬ সালের প্রতিষ্ঠাকাল থেকে চলে আসা রীতিই বজায় রাখেন, মেয়েরা ও সাধারণ মানুষ যাতে প্যান্ডেলে আসতে পারেন। ১৯৩৮ সালে তিনি কুমোরটুলি সর্বোজনীন কমিটির সভাপতিত্ব করেন।",
    source: "Millennium Post; The Statesman",
    tags: ["nationalism", "subhas-bose", "women"],
  },
  {
    id: "tagores-abolished-durga-puja",
    era: "Colonial",
    year: "19th c.",
    title: "The Tagores gave up Durga Puja",
    fact: "Durga Puja was abolished at Jorasanko Thakurbari when Debendranath Tagore embraced the image-rejecting Brahmo Samaj. He replaced it with the Magh Utsav, in which no image appears. Rabindranath grew up in a house without a pratima.",
    bangla: "মহর্ষি দেবেন্দ্রনাথ ঠাকুর মূর্তিপূজা-বিরোধী ব্রাহ্মসমাজে যোগ দিলে জোড়াসাঁকো ঠাকুরবাড়িতে দুর্গাপূজা বন্ধ হয়ে যায়। তিনি তার বদলে প্রতিমাবিহীন মাঘোৎসব প্রচলন করেন। রবীন্দ্রনাথ বড় হয়েছেন প্রতিমাহীন এক বাড়িতে।",
    source: "Wikipedia, Debendranath Tagore",
    tags: ["brahmo", "tagore", "counter-current"],
  },
  {
    id: "vivekananda-belur-1901",
    era: "Colonial",
    year: "1901",
    title: "A monk holds an image worship",
    fact: "Swami Vivekananda instituted Durga Puja at Belur Math in 1901 with Sarada Devi's permission, remarkable because Hindu sannyasins do not normally perform image worship. He worshipped nine girls as Kumaris himself.",
    bangla: "স্বামী বিবেকানন্দ ১৯০১ সালে সারদা দেবীর অনুমতি নিয়ে বেলুড় মঠে দুর্গাপূজার প্রবর্তন করেন, উল্লেখযোগ্য, কারণ হিন্দু সন্ন্যাসীরা সাধারণত প্রতিমাপূজা করেন না। সেবার তিনি নিজেই নয়জন বালিকাকে কুমারীরূপে পূজা করেন।",
    source: "Belur Math; DailyO",
    tags: ["belur-math", "vivekananda", "kumari-puja"],
  },
  {
    id: "kumari-sixteen-names",
    era: "Medieval",
    year: null,
    title: "A different name for every age",
    fact: "The Kumari is named by her age, and the sixteen names are fixed, Sandhya at one, Saraswati at two, on through Aparajita at ten and Bhairavi at twelve, to Annada or Ambika at sixteen.",
    bangla: "কুমারীর নাম নির্ধারিত হয় তার বয়স অনুসারে, এবং ষোলোটি নামই নির্দিষ্ট, এক বছরে সন্ধ্যা, দুইয়ে সরস্বতী, এভাবে দশে অপরাজিতা, বারোয় ভৈরবী, আর ষোলোয় অন্নদা বা অম্বিকা।",
    source: "Banglapedia: Kumari Puja",
    tags: ["kumari-puja", "ritual", "obscure"],
  },
  {
    id: "kumari-no-caste-bar",
    era: "Modern",
    year: null,
    title: "No caste test for the Kumari",
    fact: "Banglapedia records that no distinction of race, religion or caste is made in choosing the girl for Kumari Puja, and that the philosophical basis of the rite is to establish the value of women.",
    bangla: "বাংলাপিডিয়ার নথি অনুযায়ী, কুমারী পূজার জন্য বালিকা নির্বাচনে জাতি, ধর্ম বা বর্ণের কোনো ভেদ করা হয় না, এবং এই আচারের দার্শনিক ভিত্তি নারীর মর্যাদা প্রতিষ্ঠা।",
    source: "Banglapedia: Kumari Puja",
    tags: ["kumari-puja", "inclusion", "ritual"],
  },
  {
    id: "family-grouping-is-bengali",
    era: "Medieval",
    year: "c. 16th c.",
    title: "Durga has no daughters in any Purana",
    fact: "The family tableau, Lakshmi, Saraswati, Kartikeya and Ganesha flanking Durga, is a Bengali folk invention of roughly the sixteenth century. The sons appear in the Puranas; the daughters do not. That is why the children look uninterested in the battle.",
    bangla: "লক্ষ্মী, সরস্বতী, কার্তিক ও গণেশ ঘেরা সপরিবার দুর্গা আসলে আনুমানিক ষোড়শ শতকের বাঙালি লোকঐতিহ্যের উদ্ভাবন। পুত্রদের কথা পুরাণে আছে, কন্যাদের নেই। সেই কারণেই মায়ের পায়ের কাছে যুদ্ধ চললেও সন্তানদের যেন কোনো ভ্রূক্ষেপ নেই।",
    source: "Jawhar Sircar, Curious Anomalies",
    tags: ["iconography", "bengal", "correction"],
  },
  {
    id: "horse-faced-lion",
    era: "Colonial",
    year: "until the 1880s",
    title: "Durga's lion used to be a horse",
    fact: "Bengali sculptors had never seen a lion, so early zamindari images gave the goddess a creature that looks more like a horse or a donkey. Only after real lions reached the Calcutta zoo in the 1880s did local clay sculptors learn to make a lion that looked like one.",
    bangla: "বাঙালি মৃৎশিল্পীরা কখনও সিংহ দেখেননি, তাই আদি জমিদারি প্রতিমায় দেবীর বাহনটি দেখতে অনেকটা ঘোড়া বা গাধার মতো। ১৮৮০-র দশকে কলকাতার চিড়িয়াখানায় সত্যিকারের সিংহ আসার পরেই শিল্পীরা সিংহের মতো দেখতে সিংহ গড়তে শেখেন।",
    source: "Jawhar Sircar, Curious Anomalies",
    tags: ["iconography", "lion", "obscure"],
  },
  {
    id: "durga-became-a-daughter",
    era: "Medieval",
    year: null,
    title: "Bengal turned a war goddess into a daughter",
    fact: "The terrifying Puranic Chandika underwent what one historian calls a plebeianisation in Bengal, transformed into a commoner's daughter who visits her parents once a year, and received parental tenderness rather than fear.",
    bangla: "পুরাণের ভয়ংকরী চণ্ডিকা বাংলায় যে রূপান্তরের ভিতর দিয়ে যান, এক ঐতিহাসিক তাকে বলেছেন 'লোকায়তকরণ', তিনি হয়ে উঠলেন সাধারণ ঘরের মেয়ে, বছরে একবার বাপের বাড়ি আসেন, আর পেলেন ভয় নয়, বাৎসল্য।",
    source: "Jawhar Sircar, Curious Anomalies",
    tags: ["iconography", "bengal", "culture"],
  },
  {
    id: "bengal-eats-fish-at-puja",
    era: "Medieval",
    year: null,
    title: "The festival everyone else fasts for",
    fact: "Navaratri elsewhere in India is observed with fasting. Bengal vigorously rejected that, Durga Puja is the week of the best fish and meat a household can manage.",
    bangla: "ভারতের অন্যত্র নবরাত্রি পালিত হয় উপবাসে। বাংলা সেটি জোরের সঙ্গে প্রত্যাখ্যান করেছে, দুর্গাপূজা মানেই ঘরের সাধ্যমতো সেরা মাছ-মাংসের সপ্তাহ।",
    source: "Jawhar Sircar, Curious Anomalies",
    tags: ["culture", "food", "bengal"],
  },
  {
    id: "daker-saj-came-by-post",
    era: "Colonial",
    year: "19th c.",
    title: "Ornaments that arrived in the mail",
    fact: "Daker Saj is named after the postal service. The silver foil and sequins were imported, mainly from Germany, and arrived by post, dak in Bengali. Hence 'the dress that came by post'.",
    bangla: "'ডাকের সাজ' নামটি এসেছে ডাকঘর থেকে। রাংতা ও রুপোলি চুমকি আমদানি হত মূলত জার্মানি থেকে, আর আসত ডাকযোগে। তাই এই সাজের নাম হয়ে গেল ডাকের সাজ।",
    source: "GetBengal; Curly Tales",
    tags: ["iconography", "daker-saj", "etymology"],
  },
  {
    id: "world-war-ended-german-foil",
    era: "Modern",
    year: "1939-45",
    title: "The war that changed the goddess's dress",
    fact: "The Second World War cut off the German silver-foil imports that made Daker Saj. Sholapith, the white spongewood of Bengal's wetlands, worked by the Malakar caste, rose as its substitute and never left.",
    bangla: "দ্বিতীয় বিশ্বযুদ্ধ ডাকের সাজের জার্মান রাংতা আমদানি বন্ধ করে দেয়। তার বিকল্প হিসেবে উঠে আসে শোলা, বাংলার জলাভূমির সাদা নরম কাঠ, যা নিয়ে কাজ করেন মালাকাররা, এবং তা আর সরেনি।",
    source: "Sahapedia; GetBengal",
    tags: ["iconography", "shola", "wartime"],
  },
  {
    id: "ekchala-and-chalchitra",
    era: "Colonial",
    year: "c. 300 years",
    title: "One arch, ten Mahavidyas",
    fact: "The classical Bengali image is the ekchala, the whole family under a single arch, against a painted chalchitra backdrop that the patua painters called pata lekha, often carrying the ten Mahavidyas. The craft has nearly vanished in this century.",
    bangla: "চিরায়ত বাংলা প্রতিমা হল একচালা, গোটা পরিবার এক চালার নিচে, পিছনে আঁকা চালচিত্র, পটুয়ারা যাকে বলতেন 'পট লেখা', যেখানে প্রায়ই থাকে দশমহাবিদ্যা। এই শিল্প এই শতকে প্রায় হারিয়ে গেছে।",
    source: "Wikipedia, Chalchitra; Oaklores",
    tags: ["iconography", "ekchala", "chalchitra"],
  },
  {
    id: "gopeshwar-pal-fire-1938",
    era: "Colonial",
    year: "1937-38",
    title: "A fire broke the ekchala",
    fact: "A fire destroyed the idols at Kumartuli Sarbojanin the year Subhas Chandra Bose was asked to preside. Gopeshwar Pal, the self-taught 'lightning sculptor' later honoured in Europe, rebuilt the whole group in about 24 hours, on five separate platforms. That committee's ekchala tradition ended that night.",
    bangla: "সুভাষচন্দ্র বসুকে যে বছর সভাপতি হতে বলা হয়, সেই বছরেই আগুনে পুড়ে যায় কুমোরটুলি সর্বোজনীনের প্রতিমা। স্বশিক্ষিত 'বিদ্যুৎ-ভাস্কর' গোপেশ্বর পাল, যিনি পরে ইউরোপে সম্মানিত হন, প্রায় চব্বিশ ঘণ্টায় গোটা প্রতিমা গড়ে তোলেন, পাঁচটি আলাদা বেদিতে। সেই রাতেই ওই কমিটির একচালা প্রথা শেষ হয়।",
    source: "The Statesman; GetBengal",
    tags: ["iconography", "kumartuli", "gopeshwar-pal"],
  },
  {
    id: "kolabou-is-not-ganeshas-wife",
    era: "Medieval",
    year: null,
    title: "Kola Bou is not Ganesha's wife",
    fact: "The banana-plant bride beside Ganesha is the Nabapatrika, nine plants bound with white aparajita and a yellow thread, each embodying a form of the goddess. She is Durga's vegetal body, not anyone's wife.",
    bangla: "গণেশের পাশে দাঁড়ানো কলাবউ আসলে নবপত্রিকা, সাদা অপরাজিতা লতা ও হলুদ সুতোয় বাঁধা নয়টি গাছ, প্রত্যেকটি দেবীর এক এক রূপ। তিনি দুর্গারই উদ্ভিদ-শরীর, কারও স্ত্রী নন।",
    source: "India Currents; Hindu American Foundation",
    tags: ["nabapatrika", "correction", "ritual"],
  },
  {
    id: "nabapatrika-nine-goddesses",
    era: "Medieval",
    year: null,
    title: "Nine plants, nine goddesses",
    fact: "The Nabapatrika's nine plants each carry a goddess, banana is Brahmani, colocasia Kalika, turmeric Durga, jayanti Kartiki, bel Shiva, pomegranate Raktadantika, ashoka Shokarahita, arum Chamunda, and paddy Lakshmi.",
    bangla: "নবপত্রিকার নয়টি গাছের প্রত্যেকটিতেই এক এক দেবী, কলা ব্রাহ্মণী, কচু কালিকা, হলুদ দুর্গা, জয়ন্তী কার্তিকী, বেল শিবা, ডালিম রক্তদন্তিকা, অশোক শোকরহিতা, মানকচু চামুণ্ডা এবং ধান লক্ষ্মী।",
    source: "DrikPanchang",
    tags: ["nabapatrika", "ritual", "detail"],
  },
  {
    id: "kolabou-beside-ganesha-why",
    era: "Medieval",
    year: null,
    title: "Why she stands beside Ganesha",
    fact: "One folk explanation ties the Nabapatrika's placement beside Ganesha to his epithet Ashtadashaushadhisrishti, creator of eighteen medicinal plants, the herbal goddess beside the lord of herbs. It is not attested in the standard puja manuals, which tell other stories. What is certain is that she is not his bride.",
    bangla: "একটি লোকব্যাখ্যা বলে, গণেশের পাশে নবপত্রিকা বসেন তাঁর অষ্টাদশৌষধিসৃষ্টি নামের কারণে, আঠারো ওষধির স্রষ্টা; ওষধির অধিপতির পাশে ওষধির দেবী। প্রামাণ্য পূজাপদ্ধতিতে এর সমর্থন নেই, সেখানে অন্য কাহিনি আছে। নিশ্চিত যেটুকু, তিনি গণেশের স্ত্রী নন।",
    source: "Folk explanation; not attested in standard puja-vidhi",
    tags: ["nabapatrika", "correction", "ritual"],
  },
  {
    id: "mahalaya-is-an-ancestral-rite",
    era: "Ancient",
    year: null,
    title: "Mahalaya is for the dead, not the goddess",
    fact: "Mahalaya is the new moon that ends Pitri Paksha and begins Devi Paksha. Its central act is Tarpan, offering water with black sesame and kusha grass to the ancestors, standing in a river. The belief that Durga Puja starts on Mahalaya is a modern conflation.",
    bangla: "মহালয়া হল সেই অমাবস্যা যা পিতৃপক্ষের শেষ ও দেবীপক্ষের সূচনা করে। এর মূল কাজ তর্পণ, নদীতে দাঁড়িয়ে কৃষ্ণতিল ও কুশসহ জল দিয়ে পূর্বপুরুষদের স্মরণ। 'মহালয়াতেই দুর্গাপূজা শুরু', এই ধারণা আধুনিক গুলিয়ে ফেলা।",
    source: "Wikipedia, Pitru Paksha; The Statesman",
    tags: ["mahalaya", "ritual", "correction"],
  },
  {
    id: "mahishasuramardini-1931",
    era: "Modern",
    year: "1931",
    title: "The broadcast that made Mahalaya",
    fact: "Mahishasuramardini was first broadcast from Calcutta radio in 1931, script by Bani Kumar, music by Pankaj Kumar Mullick, Chandi recitation by Birendra Krishna Bhadra. More than any scripture, this programme fixed Mahalaya in the Bengali year.",
    bangla: "মহিষাসুরমর্দিনী প্রথম সম্প্রচারিত হয় কলকাতা বেতার থেকে ১৯৩১ সালে, রচনা বাণীকুমার, সুর পঙ্কজকুমার মল্লিক, চণ্ডীপাঠ বীরেন্দ্রকৃষ্ণ ভদ্র। কোনো শাস্ত্রের চেয়েও বেশি করে এই অনুষ্ঠানটিই বাঙালির বছরে মহালয়াকে গেঁথে দিয়েছে।",
    source: "Wikipedia, Mahisasuramardini (radio programme)",
    tags: ["mahalaya", "radio", "modern"],
  },
  {
    id: "uttam-kumar-1976-fiasco",
    era: "Modern",
    year: "1976",
    title: "The year Bengal stoned the radio station",
    fact: "On 23 September 1976 All India Radio replaced Bhadra with a new programme, Deving Durgatiharinim, narrated by Uttam Kumar. AIR offices were stoned, switchboards flooded; the broadcaster apologised and restored Bhadra. Uttam Kumar is said to have called it converting a place of worship into a drawing room.",
    bangla: "১৯৭৬ সালের ২৩ সেপ্টেম্বর আকাশবাণী ভদ্রের বদলে চালায় নতুন অনুষ্ঠান 'দেবীং দুর্গতিহরিণীম', ভাষ্যে উত্তমকুমার। আকাশবাণীর দপ্তরে ঢিল পড়ে, ফোন উপচে যায়; সম্প্রচারক ক্ষমা চেয়ে ভদ্রকে ফিরিয়ে আনে। উত্তমকুমার নাকি বলেছিলেন, এ যেন উপাসনার জায়গাকে বৈঠকখানা বানানো।",
    source: "Wikipedia, Durga Durgatiharini",
    tags: ["mahalaya", "radio", "controversy"],
  },
  {
    id: "sandhi-puja-48-minutes",
    era: "Medieval",
    year: null,
    title: "Exactly forty-eight minutes",
    fact: "Sandhi Puja occupies the last 24 minutes of Ashtami and the first 24 of Nabami, exactly 48 minutes, performed on clock time rather than daylight, with 108 lamps lit and 108 lotuses offered.",
    bangla: "সন্ধিপূজা চলে অষ্টমীর শেষ ২৪ মিনিট আর নবমীর প্রথম ২৪ মিনিট জুড়ে, ঠিক ৪৮ মিনিট, দিনের আলো নয়, ঘড়ির হিসেবে। জ্বলে ১০৮টি প্রদীপ, নিবেদিত হয় ১০৮টি পদ্ম।",
    source: "Wikipedia, Durga Puja; Shubh Panchang",
    tags: ["sandhi-puja", "ritual", "timing"],
  },
  {
    id: "sandhi-puja-is-chamunda",
    era: "Medieval",
    year: null,
    title: "The crack between two tithis",
    fact: "Sandhi Puja commemorates the moment Durga, ambushed by Chanda and Munda against the rules of battle, manifested Chamunda from her third eye. The rite is potent precisely because it belongs to neither tithi.",
    bangla: "সন্ধিপূজা স্মরণ করায় সেই মুহূর্তকে, যখন যুদ্ধের নিয়ম ভেঙে চণ্ড ও মুণ্ডের আক্রমণে ক্রুদ্ধ দুর্গার তৃতীয় নয়ন থেকে আবির্ভূত হন চামুণ্ডা। এই আচার শক্তিশালী ঠিক এই কারণেই যে তা কোনো তিথিরই অন্তর্গত নয়।",
    source: "Shubh Panchang; Devi Mahatmya",
    tags: ["sandhi-puja", "chandi", "ritual"],
  },
  {
    id: "bali-is-a-vegetable",
    era: "Modern",
    year: null,
    title: "Most sacrifice today is a gourd",
    fact: "Under Vaishnava influence, Bengali bali is now usually vegetal, banana, ash gourd, sugarcane, and mashbhakta of rice, banana, cloves and ghee. Belur Math performs the banana, ash gourd and sugarcane bali.",
    bangla: "বৈষ্ণব প্রভাবে বাঙালির বলি এখন সাধারণত নিরামিষ, কলা, চালকুমড়ো, আখ, আর চাল-কলা-লবঙ্গ-ঘিয়ের মাষভক্ত। বেলুড় মঠে কলা, চালকুমড়ো ও আখের বলি হয়।",
    source: "Templesinindia; Belur Math practice",
    tags: ["ritual", "bali", "navami"],
  },
  {
    id: "darpan-bisarjan-mirror",
    era: "Medieval",
    year: null,
    title: "The real immersion is a reflection",
    fact: "On Dashami a vessel of water is set before the goddess and a mirror angled so her reflection falls in it, and the reflection is immersed. Priests hold that this, not the river, is the moment the divinity leaves the clay.",
    bangla: "দশমীতে দেবীর সামনে জলপূর্ণ পাত্র রেখে আয়না এমনভাবে ধরা হয় যাতে তাঁর প্রতিবিম্ব জলে পড়ে, আর সেই প্রতিবিম্বেরই বিসর্জন হয়। পুরোহিতেরা বলেন, নদী নয়, এখানেই মাটির প্রতিমা ছেড়ে দেবত্ব চলে যায়।",
    source: "bdnews24; Prothom Alo",
    tags: ["dashami", "ritual", "bisarjan"],
  },
  {
    id: "sindur-khela-age-unknown",
    era: "Colonial",
    year: null,
    title: "Nobody knows how old Sindoor Khela is",
    fact: "Two traditions compete, that Sindoor Khela began about two hundred years ago in zamindar households to build bonhomie among housewives, or that it is as old as the Bengali festival itself, some four hundred years. Neither is documented.",
    bangla: "দুটি ধারা পাশাপাশি চলে, কেউ বলেন সিঁদুর খেলা শুরু হয়েছিল প্রায় দুশো বছর আগে জমিদারবাড়িতে, গৃহিণীদের মধ্যে সৌহার্দ্য গড়তে; কেউ বলেন এ প্রথা বাঙালির উৎসবের মতোই প্রায় চারশো বছরের পুরোনো। কোনোটিরই নথিপ্রমাণ নেই।",
    source: "Wikipedia: Sindoor Khela",
    tags: ["sindur-khela", "dashami", "contested"],
  },
  {
    id: "mala-mas-2020",
    era: "Contemporary",
    year: "2020",
    title: "The year Puja came 35 days late",
    fact: "In 2020 Ashwin held two new moons, making it a mala mas in which no auspicious rite may be performed. Durga Puja slipped into Kartik and Mahasashthi fell 35 days after Mahalaya instead of six. The last such years were 2001 and 1982.",
    bangla: "২০২০ সালে আশ্বিনে দুটি অমাবস্যা পড়ায় তা হয়ে যায় মলমাস, যাতে কোনো শুভকাজ চলে না। দুর্গাপূজা সরে যায় কার্তিকে, আর মহাষষ্ঠী পড়ে মহালয়ার ছয় দিন নয়, পঁয়ত্রিশ দিন পরে। এর আগে এমন হয়েছিল ২০০১ ও ১৯৮২ সালে।",
    source: "The Statesman; India TV",
    tags: ["calendar", "mala-mas", "2020"],
  },
  {
    id: "agomon-gomon-omens",
    era: "Medieval",
    year: null,
    title: "The goddess's ride forecasts the year",
    fact: "The Bengali panjika reads the goddess's arrival and departure vehicle as an omen, elephant for peace and plenty, boat for flood and a good harvest both, horse for war and unrest, palanquin for epidemic. Newspapers still print the forecast every autumn.",
    bangla: "বাঙালির পঞ্জিকা দেবীর আগমন ও গমনের বাহনকে লক্ষণ হিসেবে পড়ে, হাতি মানে শান্তি ও সমৃদ্ধি, নৌকা মানে একদিকে বন্যা অন্যদিকে ভালো ফসল, ঘোড়া মানে যুদ্ধ ও অশান্তি, দোলা মানে মহামারি। সংবাদপত্রে আজও প্রতি শরতে এই পূর্বাভাস ছাপা হয়।",
    source: "Aaj Tak Bangla",
    tags: ["calendar", "panjika", "folklore"],
  },
  {
    id: "punyi-pukur-no-priest",
    era: "Medieval",
    year: null,
    title: "A girls' rite with no priest",
    fact: "In Punyipukur Vrata, girls of five to nine dig a miniature pond in the courtyard and tend it daily for a month from Chaitra to Baisakh, so the village pond will not run dry. It is an unscriptural women's vow, no mantra and no priest are required.",
    bangla: "পুণ্যিপুকুর ব্রতে পাঁচ থেকে নয় বছরের মেয়েরা উঠোনে ছোট্ট এক পুকুর কেটে চৈত্র থেকে বৈশাখ পর্যন্ত এক মাস তার যত্ন নেয়, যাতে গ্রামের পুকুর শুকিয়ে না যায়। এটি অশাস্ত্রীয় মেয়েলি ব্রত, মন্ত্রও লাগে না, পুরোহিতও নয়।",
    source: "Wikipedia, Punyipukur Vrata",
    tags: ["vrata", "women", "folk-religion"],
  },
  {
    id: "kumartuli-from-krishnanagar",
    era: "Colonial",
    year: "c. 1757",
    title: "The potters were imported",
    fact: "Kumartuli's clay modellers came from Krishnanagar in Nadia, itself a colony of Dhaka migrants, brought to Calcutta around 1757 to make Nabakrishna Deb's Durga, and permitted to settle in the quarter the Company had zoned for potters.",
    bangla: "কুমোরটুলির মৃৎশিল্পীরা এসেছিলেন নদিয়ার কৃষ্ণনগর থেকে, যা নিজেই ঢাকা থেকে আসা কারিগরদের উপনিবেশ, আনুমানিক ১৭৫৭ সালে নবকৃষ্ণ দেবের দুর্গা গড়তে, আর কোম্পানির নির্দিষ্ট করে দেওয়া কুমোরপাড়াতেই তাঁরা থেকে যান।",
    source: "Sahapedia; Chitrolekha Journal",
    tags: ["kumartuli", "colonial", "origins"],
  },
  {
    id: "kathamo-puja-on-rath",
    era: "Colonial",
    year: null,
    title: "The frame is worshipped before the goddess",
    fact: "The bamboo-and-wood armature of the idol, the kathamo, is itself worshipped months before the festival, traditionally on Rath Yatra or Ulto Rath. In many old houses the same kathamo is used year after year.",
    bangla: "প্রতিমার বাঁশ-কাঠের কাঠামোকেই উৎসবের কয়েক মাস আগে পূজা করা হয়, সাধারণত রথযাত্রা বা উল্টোরথের দিন। বহু পুরোনো বাড়িতে বছরের পর বছর একই কাঠামো ব্যবহৃত হয়।",
    source: "The Statesman; Adyar Times",
    tags: ["kumartuli", "kathamo", "ritual"],
  },
  {
    id: "ek-mete-du-mete",
    era: "Colonial",
    year: null,
    title: "Two coats of clay, each with a name",
    fact: "The idol takes two named clay coats, ek mete, sticky entel mati from the Ganga bed mixed with rice husk, sun-dried three or four days; then du mete, fine sandy bele mati, dried five or six. Cracks between them are bridged with strips of cloth.",
    bangla: "প্রতিমায় দুই স্তর মাটি পড়ে, দুটিরই আলাদা নাম, 'এক মেটে', গঙ্গার তলার আঠালো এঁটেল মাটি, তুষ মিশিয়ে, তিন-চার দিন রোদে শুকনো; তারপর 'দু মেটে', মিহি বেলে মাটি, পাঁচ-ছয় দিন শুকনো। মাঝের ফাটল ঢাকা হয় কাপড়ের ফালি দিয়ে।",
    source: "Sahapedia; Chitrolekha",
    tags: ["kumartuli", "craft", "process"],
  },
  {
    id: "idols-are-not-terracotta",
    era: "Colonial",
    year: null,
    title: "Never fired, made to dissolve",
    fact: "Durga idols are sun-dried, never baked, properly terracruda, not terracotta. The clay is engineered to come apart in water, which is exactly what immersion asks of it.",
    bangla: "দুর্গাপ্রতিমা রোদে শুকনো হয়, কখনও পোড়ানো হয় না, একে বলা উচিত টেরাক্রুডা, টেরাকোটা নয়। মাটি এমনভাবেই তৈরি যাতে জলে গলে যায়, বিসর্জন ঠিক সেটুকুই চায়।",
    source: "Chitrolekha Journal",
    tags: ["kumartuli", "craft", "immersion"],
  },
  {
    id: "chokkhu-daan-on-mahalaya",
    era: "Colonial",
    year: null,
    title: "The eyes are given last",
    fact: "Chokkhu Daan, the eye-giving, is the final act of idol-making and a ritual rather than a finish. It is performed on Mahalaya, and is understood to be the moment life enters the clay.",
    bangla: "চক্ষুদান প্রতিমা গড়ার শেষ কাজ, আর তা নিছক শেষ টান নয়, একটি আচার। মহালয়ার দিনে তা সম্পন্ন হয়, আর ধরা হয় ঠিক তখনই মাটিতে প্রাণ আসে।",
    source: "Kumartuli practice; The Statesman",
    tags: ["kumartuli", "chokkhu-daan", "mahalaya"],
  },
  {
    id: "punya-mati-contested",
    era: "Colonial",
    year: null,
    title: "The soil nobody can date",
    fact: "Clay for the idol is said to require punya mati begged from a courtesan's doorway. The custom is real and still practised in places, but it has no textual source and no traceable origin, and sex workers' groups note that the soil is revered for a week while the women are denied everything else.",
    bangla: "প্রতিমার মাটিতে নাকি বারবনিতার দরজা থেকে চেয়ে আনা পুণ্যমাটি লাগে। প্রথাটি সত্যি, কোথাও কোথাও আজও চালু, কিন্তু এর কোনো শাস্ত্রীয় উৎস নেই, উৎপত্তির কালও অজানা; আর যৌনকর্মীদের সংগঠনগুলি মনে করিয়ে দেয়, এক সপ্তাহের জন্য মাটিটুকু পূজ্য হয়, মানুষগুলি নয়।",
    source: "EasternEye; Sahapedia, quoting Tapati Guha-Thakurta",
    tags: ["kumartuli", "punya-mati", "contested"],
  },
  {
    id: "kumartuli-women-sculptors",
    era: "Modern",
    year: "1990s",
    title: "Women broke into Kumartuli in the 1990s",
    fact: "Idol-making was closed to women within living memory. Mala Pal and China Pal entered the trade in the 1990s against considerable resistance and now export their work internationally.",
    bangla: "প্রতিমা গড়ার কাজ জীবিত স্মৃতির মধ্যেই মেয়েদের জন্য বন্ধ ছিল। মালা পাল ও চায়না পাল নব্বইয়ের দশকে যথেষ্ট বাধা পেরিয়ে এই পেশায় ঢোকেন, আর আজ তাঁদের প্রতিমা বিদেশেও যায়।",
    source: "Sahapedia; The Better India",
    tags: ["kumartuli", "women", "modern"],
  },
  {
    id: "kumartuli-exports-fibreglass",
    era: "Contemporary",
    year: "2024-25",
    title: "Three hundred goddesses fly out a year",
    fact: "Kumartuli exported over 240 idols in 2024 and more than 300 the following season, to Russia, the USA, Australia, Japan, Canada, Germany, Italy, France, New Zealand, Uganda and Dubai, almost all in fibreglass, because clay cannot survive air freight.",
    bangla: "কুমোরটুলি ২০২৪ সালে ২৪০-এর বেশি এবং পরের মরসুমে ৩০০-রও বেশি প্রতিমা বিদেশে পাঠায়, রাশিয়া, আমেরিকা, অস্ট্রেলিয়া, জাপান, কানাডা, জার্মানি, ইতালি, ফ্রান্স, নিউজিল্যান্ড, উগান্ডা ও দুবাইয়ে। প্রায় সবই ফাইবারগ্লাসের, কারণ মাটি বিমানযাত্রা সহ্য করে না।",
    source: "ANI; Devdiscourse",
    tags: ["kumartuli", "diaspora", "economy"],
  },
  {
    id: "asian-paints-1985",
    era: "Modern",
    year: "1985",
    title: "Three prizes in the first year",
    fact: "The Asian Paints Sharad Shamman, inaugurated in October 1985, is the oldest and still the most coveted Puja award. Only three prizes were given in its first year; Adi Ballygunge was among the winners.",
    bangla: "১৯৮৫ সালের অক্টোবরে চালু হওয়া এশিয়ান পেন্টস শারদ সম্মান পুজোর পুরস্কারগুলির মধ্যে প্রাচীনতম এবং আজও সবচেয়ে কাঙ্ক্ষিত। প্রথম বছরে দেওয়া হয়েছিল মাত্র তিনটি পুরস্কার; বিজয়ীদের মধ্যে ছিল আদি বালিগঞ্জ।",
    source: "Wikipedia, Asian Paints Sharad Shamman",
    tags: ["awards", "modern", "kolkata"],
  },
  {
    id: "meera-mukherjee-1990-durga",
    era: "Modern",
    year: "1990",
    title: "A Santhal sari for the goddess",
    fact: "A decade before 'theme puja' had a name, the sculptor-anthropologist Meera Mukherjee made the Durga for Bakul Bagan Sarbojanin in 1990, rendering her in an Adivasi idiom and draping her in a Santhal sari.",
    bangla: "'থিম পুজো' শব্দটি চালু হওয়ার এক দশক আগে, ১৯৯০ সালে ভাস্কর-নৃতাত্ত্বিক মীরা মুখোপাধ্যায় বকুলবাগান সর্বজনীনের দুর্গা গড়েন আদিবাসী আঙ্গিকে, পরিয়ে দেন সাঁওতালি শাড়ি।",
    source: "Meera Mukherjee's 1990 commission for a Kolkata puja, documented in exhibition literature",
    tags: ["theme-puja", "art", "modern"],
  },
  {
    id: "theme-puja-turn-of-millennium",
    era: "Contemporary",
    year: "c. 2001",
    title: "When the pandal became an artwork",
    fact: "Around the turn of the millennium, art-school graduates turned the pandal into a composite installation, structure, idol, decor, colour, lighting and music designed as one work. Bosepukur Sitala Mandir is most often credited with launching the wave.",
    bangla: "সহস্রাব্দের সন্ধিক্ষণে আর্ট কলেজের স্নাতকদের হাতে মণ্ডপ হয়ে ওঠে একটি সম্পূর্ণ শিল্পস্থাপনা, কাঠামো, প্রতিমা, সজ্জা, রং, আলো ও সঙ্গীত মিলিয়ে একটিই কাজ। এই ঢেউয়ের সূচনার কৃতিত্ব সাধারণত দেওয়া হয় বোসপুকুর শীতলা মন্দিরকে।",
    source: "Tapati Guha-Thakurta; kolkatadurgotsav.com",
    tags: ["theme-puja", "contemporary", "art"],
  },
  {
    id: "chandannagar-running-lights-1965",
    era: "Modern",
    year: "1965",
    title: "Running lights invented on a plank",
    fact: "Sridhar Das offered to illuminate Narua's Jagaddhatri Puja in 1965 and built the first running lights on a flat wooden board. Kashinath Neogy brought LEDs to Chandannagar in 2005; today's masters were all trained by Das.",
    bangla: "১৯৬৫ সালে শ্রীধর দাস নারুয়ার জগদ্ধাত্রী পুজোয় আলোকসজ্জার দায়িত্ব নেন, আর সমতল কাঠের বোর্ডে তৈরি করেন প্রথম চলমান আলো। ২০০৫ সালে কাশীনাথ নিয়োগী চন্দননগরে এলইডি আনেন; আজকের কারিগরেরা সকলেই দাসের হাতে গড়া।",
    source: "GetBengal",
    tags: ["chandannagar", "lighting", "craft"],
  },
  {
    id: "british-council-32377-crore",
    era: "Contemporary",
    year: "2019-21",
    title: "2.58 per cent of a state's economy",
    fact: "The British Council study, led by Queen Mary University of London with IIT Kharagpur, valued the creative economy around Durga Puja in West Bengal at ₹32,377 crore, equal to 2.58 per cent of the state's GDP. It was among the most rigorous studies of its kind in India, building on earlier work such as a 2013 ASSOCHAM report.",
    bangla: "কুইন মেরি ইউনিভার্সিটি অফ লন্ডন ও আইআইটি খড়্গপুরের নেতৃত্বে ব্রিটিশ কাউন্সিলের সমীক্ষা পশ্চিমবঙ্গে দুর্গাপুজোকে ঘিরে গড়ে ওঠা সৃজনশীল অর্থনীতির মূল্য নির্ধারণ করে ৩২,৩৭৭ কোটি টাকা, রাজ্যের জিডিপির ২.৫৮ শতাংশ। ভারতে এই ধরনের সবচেয়ে নিখুঁত সমীক্ষাগুলির একটি, যা ২০১৩ সালের অ্যাসোচেম রিপোর্টের মতো আগের কাজের উপর দাঁড়িয়ে।",
    source: "British Council; Down To Earth",
    tags: ["economy", "contemporary", "research"],
  },
  {
    id: "unesco-16com-decision",
    era: "Contemporary",
    year: "2021",
    title: "Decision 16.COM 8.b.15",
    fact: "'Durga Puja in Kolkata' was inscribed on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity at the sixteenth session of the Intergovernmental Committee, held 13-18 December 2021, under decision 16.COM 8.b.15, nomination file 00703.",
    bangla: "'দুর্গা পূজা ইন কলকাতা' ইউনেস্কোর মানবজাতির অপার্থিব সাংস্কৃতিক ঐতিহ্যের প্রতিনিধিত্বমূলক তালিকায় অন্তর্ভুক্ত হয় আন্তঃসরকারি কমিটির ষোড়শ অধিবেশনে, ১৩–১৮ ডিসেম্বর ২০২১, সিদ্ধান্ত নম্বর ১৬.COM ৮.বি.১৫, মনোনয়ন ফাইল ০০৭০৩।",
    source: "UNESCO ICH element 00703",
    tags: ["unesco", "contemporary", "heritage"],
  },
  {
    id: "unesco-not-durga-puja-of-india",
    era: "Contemporary",
    year: "2019",
    title: "The title was fought over",
    fact: "The Ministry of Culture wanted the element pitched as a nationwide phenomenon, 'Durga Puja of India'. The historian Tapati Guha-Thakurta, who prepared the dossier, argued that Kolkata was where the festival's longest continuous history and community character could actually be shown, and won. Hence the inscribed title, 'Durga Puja in Kolkata'.",
    bangla: "সংস্কৃতি মন্ত্রক চেয়েছিল বিষয়টি সর্বভারতীয় হিসেবে পেশ হোক, 'দুর্গা পূজা অফ ইন্ডিয়া'। নথি তৈরি করেছিলেন ইতিহাসবিদ তপতী গুহঠাকুরতা; তিনি যুক্তি দেন, উৎসবের দীর্ঘতম অবিচ্ছিন্ন ইতিহাস আর সমষ্টিগত চরিত্র দেখানো যায় কলকাতাতেই। তাঁর যুক্তিই টেকে। তাই তালিকাভুক্ত নাম, 'দুর্গা পূজা ইন কলকাতা'।",
    source: "The Wire; The Better India",
    tags: ["unesco", "contemporary", "politics"],
  },
  {
    id: "deshapriya-park-88-feet",
    era: "Contemporary",
    year: "2015",
    title: "The 88-foot Durga that had to be shut",
    fact: "Deshapriya Park installed an 88-foot Durga in 2015, billed as the world's tallest. About 5.5 lakh people converged, a near-stampede injured eleven, and Kolkata Police closed the ground and turned the crowds back.",
    bangla: "২০১৫ সালে দেশপ্রিয় পার্কে বসে ৮৮ ফুট উঁচু দুর্গা, প্রচার হয় বিশ্বের উচ্চতম বলে। প্রায় সাড়ে পাঁচ লক্ষ মানুষ ভিড় করেন, পদপিষ্ট হওয়ার উপক্রমে এগারো জন আহত হন, আর কলকাতা পুলিশ মাঠ বন্ধ করে ভিড় ফিরিয়ে দেয়।",
    source: "Business Standard; Deccan Herald",
    tags: ["contemporary", "kolkata", "spectacle"],
  },
  {
    id: "covid-2020-no-entry-pandals",
    era: "Contemporary",
    year: "2020",
    title: "Thirty-four thousand empty pandals",
    fact: "In 2020 the Calcutta High Court declared all roughly 34,000 pandals in West Bengal no-entry zones for visitors, with barricades five metres out for small pandals and ten for large. It later relented to let the dhakis inside.",
    bangla: "২০২০ সালে কলকাতা হাইকোর্ট পশ্চিমবঙ্গের প্রায় ৩৪ হাজার মণ্ডপকেই দর্শনার্থীদের জন্য 'নো-এন্ট্রি' ঘোষণা করে, ছোট মণ্ডপে পাঁচ মিটার, বড় মণ্ডপে দশ মিটার পর্যন্ত ব্যারিকেড। পরে আদালত ঢাকিদের ভিতরে ঢোকার অনুমতি দেয়।",
    source: "DNA India; Tribune India",
    tags: ["contemporary", "covid", "kolkata"],
  },
  {
    id: "london-1963-russell-square",
    era: "Modern",
    year: "1963",
    title: "London's first Durga came by donation",
    fact: "In autumn 1963 Bengali students held London's first Durga Puja at the Mary Ward Centre, Russell Square. The editor Tushar Kanti Ghosh, then in London, donated the pratima. The puja moved to Camden's Hampstead Town Hall in 1966 and has stayed.",
    bangla: "১৯৬৩ সালের শরতে কয়েকজন বাঙালি ছাত্র রাসেল স্কোয়ারের মেরি ওয়ার্ড সেন্টারে লন্ডনের প্রথম দুর্গাপূজা করেন। তখন লন্ডনে থাকা সম্পাদক তুষারকান্তি ঘোষ প্রতিমাটি দান করেন। ১৯৬৬ সালে পুজো উঠে আসে ক্যামডেনের হ্যাম্পস্টেড টাউন হলে, আজও সেখানেই।",
    source: "Global Indian; London Durga Puja Dusserah Association",
    tags: ["diaspora", "london", "modern"],
  },
  {
    id: "usa-first-puja-1970-columbia",
    era: "Modern",
    year: "1970",
    title: "America's first puja was at Columbia",
    fact: "The oldest community Durga Puja in the United States was held at Columbia University in 1970, organised by the East Coast Durga Puja Association, still the oldest Bengali association in North America. People drove hundreds of miles for it.",
    bangla: "যুক্তরাষ্ট্রের প্রাচীনতম সর্বজনীন দুর্গাপূজা হয় ১৯৭০ সালে কলম্বিয়া বিশ্ববিদ্যালয়ে, ইস্ট কোস্ট দুর্গা পূজা অ্যাসোসিয়েশনের উদ্যোগে, যা আজও উত্তর আমেরিকার প্রাচীনতম বাঙালি সংগঠন। মানুষ কয়েকশো মাইল গাড়ি চালিয়ে সেখানে এসেছিলেন।",
    source: "ECDPA; The Space",
    tags: ["diaspora", "usa", "modern"],
  },
  {
    id: "delhi-1910-railway-doctor",
    era: "Colonial",
    year: "1910",
    title: "A railway doctor started Delhi's puja",
    fact: "The Delhi Durga Puja Samiti was founded at Kashmiri Gate in 1910, largely through the efforts of a railway doctor, Hemchandra Sen, beginning as a baroyari at the Roshanpura Kali Mandir near Nai Sarak.",
    bangla: "দিল্লি দুর্গাপূজা সমিতি প্রতিষ্ঠিত হয় ১৯১০ সালে কাশ্মীরি গেটে, মূলত রেলের চিকিৎসক হেমচন্দ্র সেনের উদ্যোগে, নই সড়কের কাছে রোশনপুরা কালীমন্দিরে বারোয়ারি পূজা হিসেবে।",
    source: "Wikipedia, Delhi Durga Puja Samiti",
    tags: ["probashi", "delhi", "colonial"],
  },
  {
    id: "cr-park-refugee-colony",
    era: "Modern",
    year: "1960s-1977",
    title: "Delhi's Bengali quarter was a refugee colony",
    fact: "Chittaranjan Park began in the early 1960s as EPDP Colony, East Pakistan Displaced Persons Colony, and was renamed for Chittaranjan Das in the 1980s. Its first Durga Puja was in 1970; the Kali Mandir held its first in 1977.",
    bangla: "চিত্তরঞ্জন পার্কের সূচনা ষাটের দশকের গোড়ায়, ইপিডিপি কলোনি অর্থাৎ 'ইস্ট পাকিস্তান ডিসপ্লেসড পার্সনস কলোনি' হিসেবে; আশির দশকে নাম হয় চিত্তরঞ্জন দাশের নামে। প্রথম দুর্গাপূজা ১৯৭০ সালে, আর কালীমন্দিরে প্রথম পূজা ১৯৭৭-এ।",
    source: "Wikipedia, Chittaranjan Park",
    tags: ["probashi", "delhi", "partition"],
  },
  {
    id: "bangalore-1949-ghot-puja",
    era: "Modern",
    year: "1949",
    title: "Bangalore's puja began with a pot",
    fact: "Durga Puja in Bangalore is said to have begun around 1949 with a simple ghot puja in Malleswaram, the goddess represented by a pot of consecrated water rather than an image, organised by Bengalis from the Indian Institute of Science and the new public-sector industries. The city's first Sarbojanin puja followed in 1950.",
    bangla: "বলা হয়, বেঙ্গালুরুতে দুর্গাপুজোর শুরু আনুমানিক ১৯৪৯ সালে মল্লেশ্বরমে সামান্য ঘট পুজো দিয়ে, প্রতিমার বদলে পূর্ণঘটে দেবীর প্রতিষ্ঠা, উদ্যোক্তা ভারতীয় বিজ্ঞান সংস্থা আর নতুন রাষ্ট্রায়ত্ত শিল্পের বাঙালিরা। শহরের প্রথম সর্বোজনীন পুজো হয় তার পরের বছর, ১৯৫০ সালে।",
    source: "Oral tradition, not yet confirmed against an archival record",
    tags: ["probashi", "bangalore", "south-india"],
  },
  {
    id: "dhakeshwari-named-the-city",
    era: "Medieval",
    year: "12th c. (traditional)",
    title: "Dhaka is named after a goddess",
    fact: "By tradition Ballal Sen of the Sena dynasty dreamt of a buried image of the goddess, recovered it and enshrined her as Dhakeshwari, 'Goddess of Dhaka'. The city is widely held to take its name from her; the temple is today Bangladesh's only state-owned National Temple.",
    bangla: "প্রচলিত কাহিনি অনুযায়ী সেন বংশের বল্লাল সেন স্বপ্নে মাটির নিচে পোঁতা দেবীমূর্তির সন্ধান পান, তা উদ্ধার করে ঢাকেশ্বরী অর্থাৎ 'ঢাকার ঈশ্বরী' নামে প্রতিষ্ঠা করেন। বহুল বিশ্বাস, শহরের নামই এসেছে তাঁর থেকে; মন্দিরটি আজ বাংলাদেশের একমাত্র রাষ্ট্রায়ত্ত জাতীয় মন্দির।",
    source: "Wikipedia, Dhakeshwari Temple; Hindu American Foundation",
    tags: ["bangladesh", "dhaka", "history"],
  },
  {
    id: "dhakeshwari-ammunition-1971",
    era: "Modern",
    year: "1971",
    title: "A worship hall used as an ammunition dump",
    fact: "During the 1971 Liberation War the Pakistan Army took over Dhakeshwari's main worship hall and used it as an ammunition store. The temple was damaged again in communal attacks between 1989 and 1992.",
    bangla: "১৯৭১ সালের মুক্তিযুদ্ধের সময় পাকিস্তানি সেনাবাহিনী ঢাকেশ্বরী মন্দিরের প্রধান পূজামণ্ডপ দখল করে সেখানে গোলাবারুদের গুদাম বানায়। ১৯৮৯ থেকে ১৯৯২-এর সাম্প্রদায়িক হামলায় মন্দিরটি আবারও ক্ষতিগ্রস্ত হয়।",
    source: "Wikipedia, Dhakeshwari Temple",
    tags: ["bangladesh", "1971", "history"],
  },
  {
    id: "bangladesh-33355-mandaps",
    era: "Contemporary",
    year: "2025",
    title: "Thirty-three thousand mandaps in Bangladesh",
    fact: "Durga Puja in Bangladesh is observed at over 33,000 mandaps and temples nationwide, 33,355 in the most recent count, up from 31,461 the year before. Dhaka city alone had 252 mandaps in 2024, rising to 259 in 2025.",
    bangla: "বাংলাদেশে দুর্গাপুজো হয় তেত্রিশ হাজারেরও বেশি মণ্ডপ ও মন্দিরে, সাম্প্রতিকতম হিসেবে ৩৩,৩৫৫টি, আগের বছরের ৩১,৪৬১ থেকে বেড়ে। শুধু ঢাকা শহরেই ২০২৪ সালে ছিল ২৫২টি মণ্ডপ, ২০২৫ সালে ২৫৯টি।",
    source: "Prothom Alo; The Daily Star",
    tags: ["bangladesh", "contemporary", "scale"],
  },
  {
    id: "asur-community-mourns",
    era: "Contemporary",
    year: null,
    title: "The community that mourns during Puja",
    fact: "The Asur people of Jharkhand, upwards of thirty thousand in the 2011 Census, practising an animist tradition of nature and ancestor worship and not considering themselves Hindu, regard Mahishasura as their ancestor. Many stay indoors through Durga Puja to mourn him.",
    bangla: "ঝাড়খণ্ডের অসুর জনগোষ্ঠী, ২০১১ সালের জনগণনায় ত্রিশ হাজারেরও বেশি, প্রকৃতি ও পূর্বপুরুষ-পূজার ধারা মানেন, নিজেদের হিন্দু বলে মনে করেন না, আর মহিষাসুরকে পূর্বপুরুষ বলে গণ্য করেন। অনেকে দুর্গাপুজোর দিনগুলিতে শোক পালন করে ঘরে থাকেন।",
    source: "Wikipedia, Asur people; The Wire",
    tags: ["adivasi", "mahishasura", "contemporary"],
  },
  {
    id: "women-priests-66-pally-2021",
    era: "Contemporary",
    year: "2021",
    title: "Four women ran an entire Durga Puja",
    fact: "After its veteran male priest died, the 66 Pally committee in Kolkata engaged four women of the collective Shubhamastu, Nandini Bhowmick, Ruma Roy, Semanti Banerjee and Poulomi Chakrabarti, to conduct all the 2021 rituals. The theme, 'the Mother invoked by mothers'.",
    bangla: "বহু বছরের পুরোহিতের মৃত্যুর পরে কলকাতার ৬৬ পল্লি পুজো কমিটি ২০২১ সালের সমস্ত আচার সম্পন্ন করার ভার দেয় 'শুভমস্তু' দলের চার নারীকে, নন্দিনী ভৌমিক, রুমা রায়, সেমন্তী বন্দ্যোপাধ্যায় ও পৌলমী চক্রবর্তী। থিম ছিল 'মায়ের হাতে মায়ের আবাহন'।",
    source: "Business Standard; India.com",
    tags: ["women", "contemporary", "kolkata"],
  },
  {
    id: "women-dhakis-2010",
    era: "Contemporary",
    year: "2010",
    title: "Women dhakis are barely fifteen years old",
    fact: "Gokul Chandra Das of Maslandapur trained Bengal's first troupe of women dhakis, six women and four men, who played their first Durga Puja in 2010. His group now includes about thirty women.",
    bangla: "মসলন্দপুরের গোকুলচন্দ্র দাস বাংলার প্রথম নারী-ঢাকি দল গড়েন, ছয়জন মহিলা ও চারজন পুরুষ, যাঁরা ২০১০ সালে প্রথম দুর্গাপূজায় ঢাক বাজান। তাঁর দলে এখন প্রায় ত্রিশজন মহিলা।",
    source: "30Stades",
    tags: ["women", "dhaki", "contemporary"],
  },
  {
    id: "dhak-dhol-kanshi-difference",
    era: "Medieval",
    year: null,
    title: "Dhak, dhol and kanshi are three things",
    fact: "The dhak is the large barrel drum slung from the shoulder and struck with two sticks on one head only; the dhol is smaller and played on both heads, stick in the right hand and palm in the left; the kanshi is a brass plate. In Puja the dhak leads and the others follow.",
    bangla: "ঢাক হল কাঁধে ঝোলানো বড় খোল, দুটি কাঠি দিয়ে কেবল এক দিকেই বাজে; ঢোল ছোট, দুই দিকেই বাজে, ডান হাতে কাঠি, বাঁ হাতে চাপড়; আর কাঁসি একটি পিতলের থালা। পুজোয় নেতৃত্ব দেয় ঢাক, বাকিরা সঙ্গত করে।",
    source: "The Business Standard; Wikipedia, Dhak",
    tags: ["music", "dhak", "detail"],
  },
  {
    id: "dhakis-migrate-to-sealdah",
    era: "Modern",
    year: null,
    title: "Hired off a railway platform",
    fact: "Dhakis come from Murshidabad, Nadia, Bankura, Bardhaman, Malda, Hooghly, Purulia and Midnapore, converge on Sealdah station in the days before the Puja, and are hired off the platform. For the other eleven months many farm or pull rickshaws.",
    bangla: "ঢাকিরা আসেন মুর্শিদাবাদ, নদিয়া, বাঁকুড়া, বর্ধমান, মালদহ, হুগলি, পুরুলিয়া ও মেদিনীপুর থেকে; পুজোর আগের দিনগুলিতে শিয়ালদহ স্টেশনে জড়ো হন, আর প্ল্যাটফর্ম থেকেই বায়না হয়ে যায়। বাকি এগারো মাস তাঁদের অনেকেই চাষ করেন বা রিকশা টানেন।",
    source: "PARI; The Citizen",
    tags: ["dhaki", "labour", "migration"],
  },
  {
    id: "shobhabazar-no-grain-bhog",
    era: "Colonial",
    year: null,
    title: "No rice at the Shobhabazar puja",
    fact: "At Shobhabazar Rajbari no grain is offered, not to the goddess, not to visitors. Only monda-mithai, pantua, peraki, radhaballabhi, motichur laddu, cooked on the premises by Brahmin cooks.",
    bangla: "শোভাবাজার রাজবাড়িতে অন্ন নিবেদন হয় না, দেবীকেও নয়, দর্শনার্থীকেও নয়। কেবল মণ্ডা-মিঠাই, পান্তুয়া, পেরাকি, রাধাবল্লভী, মতিচুরের লাড্ডু, রাজবাড়ির ভিতরেই ব্রাহ্মণ পাচকদের হাতে তৈরি।",
    source: "The Quint; bonedi bari accounts",
    tags: ["bonedi-bari", "bhog", "shobhabazar"],
  },
  {
    id: "sabarna-khirer-putul",
    era: "Colonial",
    year: null,
    title: "A doll of milk instead of blood",
    fact: "At the Sabarna Roy Choudhury puja in Barisha, rice and potato are excluded from the goddess's bhog, and the sacrifice offered before her is a khirer putul, a doll made of thickened milk.",
    bangla: "বড়িশার সাবর্ণ রায়চৌধুরী বাড়ির পুজোয় দেবীর ভোগে চাল ও আলু পড়ে না, আর তাঁর সামনে বলি হিসেবে নিবেদিত হয় ক্ষীরের পুতুল, ঘন দুধে গড়া এক পুতুল।",
    source: "cultureandheritage.org; The Quint",
    tags: ["bonedi-bari", "bhog", "sabarna"],
  },
  {
    id: "bijoya-mishti-mukh",
    era: "Medieval",
    year: null,
    title: "No guest may leave unsweetened",
    fact: "Bijoya extends the festival by up to a fortnight, juniors touch elders' feet, men exchange the triple embrace of kolakuli, and no visitor may leave without mishti-mukh. To send a guest away unsweetened is inauspicious.",
    bangla: "বিজয়া উৎসবকে টেনে নিয়ে যায় আরও প্রায় পক্ষকাল, ছোটরা বড়দের পায়ে হাত দেয়, পুরুষেরা করে কোলাকুলি, আর কোনো অতিথিই মিষ্টিমুখ না করে ফেরেন না। অতিথিকে মিষ্টি না খাইয়ে বিদায় দেওয়া অমঙ্গল।",
    source: "The Statesman; Bengali custom",
    tags: ["bijoya", "custom", "dashami"],
  },
];

/** A deterministic spread, so server and client agree on what to show. */
export function pickFacts(n: number, offset = 0): Fact[] {
  const step = 7;
  const out: Fact[] = [];
  for (let i = 0; i < n && i < FACTS.length; i++) {
    out.push(FACTS[(offset + i * step) % FACTS.length]);
  }
  return out;
}

export function factsByEra(era: Era): Fact[] {
  return FACTS.filter((f) => f.era === era);
}

export function factsByTag(tag: string): Fact[] {
  return FACTS.filter((f) => f.tags.includes(tag));
}

export const ALL_TAGS: string[] = Array.from(
  new Set(FACTS.flatMap((f) => f.tags)),
).sort();
