/**
 * The listening room.
 *
 * Two different things with two different rules.
 *
 * The ambient layers are freely licensed recordings, CC0 or CC BY,
 * every licence checked individually. They can be hosted and mixed,
 * and every one is credited on the page as its licence requires.
 *
 * The songs are not ours and are never hosted. They are embedded from
 * the rights holder's own upload, which is the only honest way to put
 * Bengali film and folk recordings on a website. Each video id was
 * checked to resolve to the right song and to allow embedding at all,
 * because roughly a quarter of the obvious uploads quietly do not.
 *
 * Generated from research/music.json.
 */

export type AmbienceLayer = {
  id: string;
  bangla: string;
  roman: string;
  description: string;
  sourceUrl: string;
  /** Used until the committee downloads a local copy. */
  remoteUrl: string;
  licence: string;
  licenceUrl: string;
  attribution: string;
  durationSeconds: number | null;
  caveat: string | null;
};

export type Track = {
  titleBangla: string;
  titleRoman: string;
  artist: string;
  year: number | null;
  note: string;
  youtubeId: string;
  channel: string;
};

export type Collection = {
  id: string;
  bangla: string;
  roman: string;
  blurb: string;
  tracks: Track[];
};

export const AMBIENCE: AmbienceLayer[] = [
  {
    id: "dhak",
    bangla: "ঢাক",
    roman: "Dhak",
    description: "Real Durga Puja dhak, recorded in Kolkata on Dashami 2021 with dhakis from Barasat. Nearly six minutes, so it loops without sounding like a loop. This is the best free dhak recording in existence and it should be the centrepiece of the mixer.",
    sourceUrl: "https://freesound.org/people/AnneshaGhosh/sounds/592301/",
    remoteUrl: "https://cdn.freesound.org/previews/592/592301_13274041-hq.mp3",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "\"Dhaak beats from Kolkata - Durga Puja Durga Pujo\" by AnneshaGhosh (freesound.org/people/AnneshaGhosh/sounds/592301/), licensed CC BY 4.0",
    durationSeconds: 357,
    caveat: null,
  },
  {
    id: "dhak_cc0",
    bangla: "ঢোল-তাশা (বিকল্প)",
    roman: "Dhol-Tasha (CC0 alternate)",
    description: "A CC0 fallback for the drum layer if you want a mixer with zero attribution obligations. Long, loud, well recorded.",
    sourceUrl: "https://freesound.org/people/prospekt42/sounds/712286/",
    remoteUrl: "https://cdn.freesound.org/previews/712/712286_6742895-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"Dhol_Tasha_Maharashtra_Urban_2\" by prospekt42, CC0.",
    durationSeconds: 413,
    caveat: "This is Maharashtrian dhol-tasha, NOT a Bengali dhak. Different instrument, different rhythm. Use only as a fallback and never label it as dhak.",
  },
  {
    id: "kanshor_ghanta",
    bangla: "কাঁসর ঘণ্টা",
    roman: "Kanshor Ghanta",
    description: "Bell-metal ghanta struck with a mallet, long decay, close-miked. The nearest free equivalent to the kansar struck during arati.",
    sourceUrl: "https://freesound.org/people/the_very_Real_Horst/sounds/274330/",
    remoteUrl: "https://cdn.freesound.org/previews/274/274330_3597112-hq.mp3",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "\"Ghanta-Ivory-Mallet-2015-05-16-Space-Sound\" by the_very_Real_Horst (freesound.org/people/the_very_Real_Horst/sounds/274330/), licensed CC BY 4.0",
    durationSeconds: 102,
    caveat: "This is a ritual handbell ghanta, not the flat Bengali kansar disc. No genuine kansar recording exists under a free licence on Freesound, Wikimedia Commons, archive.org or Openverse. Recording one at this year's Puja would be a real contribution.",
  },
  {
    id: "shankha",
    bangla: "শঙ্খ",
    roman: "Shankha",
    description: "A single clean conch blow, eight seconds, no room noise. Best used as a one-shot triggered by a button rather than a continuous layer.",
    sourceUrl: "https://freesound.org/people/rsn267/sounds/746592/",
    remoteUrl: "https://cdn.freesound.org/previews/746/746592_2251150-lq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"Shankh Sound\" by rsn267, CC0.",
    durationSeconds: 9,
    caveat: "Freesound.org was unreachable directly from this network (TCP connections time out). Spot-check this page from a normal browser before shipping.",
  },
  {
    id: "shankha_commons",
    bangla: "শঙ্খ (বিকল্প)",
    roman: "Shankha (Commons alternate)",
    description: "A six-second conch blow from Wikimedia Commons. Hosted by Wikimedia, so the file URL is permanent and hotlinkable without a Freesound account.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Conch_shell.ogg",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/2/24/Conch_shell.ogg",
    licence: "CC BY 2.5",
    licenceUrl: "https://creativecommons.org/licenses/by/2.5",
    attribution: "\"Conch shell\" by David Bolton (User:Dbolton), Wikimedia Commons, licensed CC BY 2.5",
    durationSeconds: 7,
    caveat: "Multi-licensed CC BY 2.5 / CC BY-SA 3.0 / GFDL. Take the CC BY 2.5 option, which carries no ShareAlike obligation.",
  },
  {
    id: "ulu_dhwani",
    bangla: "উলুধ্বনি",
    roman: "Ulu-dhwani",
    description: "Twenty seconds of ululation, clean studio recording. Stands in for the ulu until a genuine Bengali recording exists.",
    sourceUrl: "https://freesound.org/people/PhonosUPF/sounds/488213/",
    remoteUrl: "https://cdn.freesound.org/previews/488/488213_9497060-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"ululation\" by PhonosUPF (Universitat Pompeu Fabra), CC0.",
    durationSeconds: 21,
    caveat: "This is NOT Bengali ulu-dhwani. There is no free-licensed recording of Bengali ululation anywhere on Freesound, Wikimedia Commons, archive.org or Openverse, and every Commons hit for 'ululation' is a dictionary pronunciation of the English word. This is the largest genuine gap in the ambience set; twenty seconds recorded at the IISc pandal would fix it permanently.",
  },
  {
    id: "mandir_ghanta",
    bangla: "মন্দিরের ঘণ্টা",
    roman: "Mandirer Ghanta",
    description: "Thirty seconds of an Indian temple bell being rung, with the natural decay intact. Loops cleanly under everything else.",
    sourceUrl: "https://freesound.org/people/ganiket/sounds/466652/",
    remoteUrl: "https://cdn.freesound.org/previews/466/466652_9226170-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"Indian Temple Bell\" by ganiket, CC0.",
    durationSeconds: 31,
    caveat: null,
  },
  {
    id: "adda",
    bangla: "আড্ডা / ভিড়ের গুঞ্জন",
    roman: "Adda / Bhirer Gunjan",
    description: "Recorded inside the Kali temple at Kalighat, Kolkata, at 96kHz stereo. Voices, feet, bells, the particular pitch of a Bengali crowd that is half worshipping and half chatting. Exactly the pandal murmur this page needs.",
    sourceUrl: "https://freesound.org/people/Calcuttan/sounds/186745/",
    remoteUrl: "https://cdn.freesound.org/previews/186/186745_2474372-hq.mp3",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "\"Kali Temple Soundscape\" by Calcuttan (freesound.org/people/Calcuttan/sounds/186745/), licensed CC BY 4.0",
    durationSeconds: 137,
    caveat: null,
  },
  {
    id: "brishti",
    bangla: "বৃষ্টি",
    roman: "Brishti",
    description: "Eleven and a half minutes of a monsoon thunderstorm over Bhag Bazar, North Kolkata, and the uploader has already prepared it as a seamless loop. Puja weather, recorded in the right city.",
    sourceUrl: "https://freesound.org/people/rcrath/sounds/671465/",
    remoteUrl: "https://cdn.freesound.org/previews/671/671465_5029-hq.mp3",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "\"1906141937 north Kolkata thunderstorm looped\" by rcrath (freesound.org/people/rcrath/sounds/671465/), licensed CC BY 4.0",
    durationSeconds: 703,
    caveat: null,
  },
  {
    id: "sandhya_arati",
    bangla: "সন্ধ্যারতি",
    roman: "Sandhya Arati",
    description: "Seven minutes of evening arati on a Ganga ghat at Varanasi: bells, voices, the swell and fall of the whole ceremony. The best single arati bed available under any free licence, and it is CC0.",
    sourceUrl: "https://freesound.org/people/rucisko/sounds/468040/",
    remoteUrl: "https://cdn.freesound.org/previews/468/468040_2978883-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"river Ganges evening Aarti ceremony 05\" by rucisko, CC0.",
    durationSeconds: 415,
    caveat: null,
  },
  {
    id: "gangar_dhara",
    bangla: "গঙ্গার ধারা",
    roman: "Gangar Dhara",
    description: "Recorded from a small wooden boat on the Ganga near Varanasi, two boats passing each other. Water, oars, distant voices. This is the layer that puts the village on the riverbank.",
    sourceUrl: "https://freesound.org/people/kevp888/sounds/578754/",
    remoteUrl: "https://cdn.freesound.org/previews/578/578754_9034501-hq.mp3",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "\"BR_049_India_GangesRiver\" by kevp888 (freesound.org/people/kevp888/sounds/578754/), licensed CC BY 4.0",
    durationSeconds: 41,
    caveat: "Only 41 seconds, so it needs a crossfade to loop convincingly.",
  },
  {
    id: "jhijhi_poka",
    bangla: "ঝিঁঝিঁ পোকা",
    roman: "Jhijhi Poka",
    description: "Three and a half minutes of crickets in a village at night. Put this under the Baul tracks and the page stops being a webpage.",
    sourceUrl: "https://freesound.org/people/savvah/sounds/400353/",
    remoteUrl: "https://cdn.freesound.org/previews/400/400353_3722909-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"Village Night Crickets\" by savvah, CC0.",
    durationSeconds: 221,
    caveat: null,
  },
  {
    id: "mantra_path",
    bangla: "মন্ত্রপাঠ",
    roman: "Mantra Path",
    description: "Two minutes of Sanskrit arati chanting in a female voice, recorded in Jaipur. Sits under the shankha and the bell without fighting either.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sanskrit_chanting_for_Aarti_Puja_Prayer_-_Female_Voice.ogg",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Sanskrit_chanting_for_Aarti_Puja_Prayer_-_Female_Voice.ogg",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"Sanskrit chanting for Aarti Puja Prayer - Female Voice\", Wikimedia Commons, CC0.",
    durationSeconds: 132,
    caveat: "The CC0 tag is the Commons uploader's own claim and the Credit field points at a third-party archive.org item (Aarti Shri Radha Govind Dev Ji, Jaipur). The tag is on the file page, but the chain of title behind it is not independently documented. Low risk for a non-commercial university page; check before any commercial use.",
  },
  {
    id: "tanpura_drone",
    bangla: "তানপুরা",
    roman: "Tanpura Drone",
    description: "A one-minute 24-bit tanpura drone. Not ritual sound, but a drone under the whole mixer glues the other layers together and keeps the page from sounding like a sound-effects board.",
    sourceUrl: "https://freesound.org/people/MieliTietty/sounds/619263/",
    remoteUrl: "https://cdn.freesound.org/previews/619/619263_10486071-hq.mp3",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "None required. Courtesy credit: \"tanpura drone#3\" by MieliTietty, CC0.",
    durationSeconds: 61,
    caveat: null,
  },
];

export const COLLECTIONS: Collection[] = [
  {
    id: "mahalaya",
    bangla: "মহালয়া",
    roman: "Mahalaya",
    blurb: "Four in the morning, the radio already on, and a voice that has been waking Bengal since before most of us were born. The whole Mahishasuramardini, and the songs inside it taken one at a time. Every track here is Saregama's own upload of the 1966 All India Radio master - embedded, never hosted.",
    tracks: [
      {
        titleBangla: "মহিষাসুরমর্দিনী (সম্পূর্ণ)",
        titleRoman: "Mahishasuramardini (full programme)",
        artist: "Birendra Krishna Bhadra, Pankaj Kumar Mullick, Bani Kumar and company",
        year: 1966,
        note: "The whole ninety minutes, exactly as Akashvani has played it at four in the morning for sixty years. Put this on and it is Mahalaya, wherever in the world you happen to be standing.",
        youtubeId: "YQyo8QeoYhc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "চণ্ডীপাঠ",
        titleRoman: "Chandipath",
        artist: "Birendra Krishna Bhadra",
        year: null,
        note: "Just the Sanskrit recitation, lifted clear of the songs. Thirty minutes of that famous unhurried voice reading the Chandi, for anyone who wants the scripture without the orchestra.",
        youtubeId: "AnrGifI3WHk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বাজলো তোমার আলোর বেণু",
        titleRoman: "Bajlo Tomar Alor Benu",
        artist: "Supriti Ghosh",
        year: null,
        note: "The song every Bengali can hum before they are fully awake. This upload keeps Bhadra's spoken introduction attached, so you get the handover from voice to flute intact.",
        youtubeId: "2Zqlb00ttCU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জাগো দুর্গা দশপ্রহরণধারিণী",
        titleRoman: "Jago Durga Dashapraharanadharini",
        artist: "Dwijen Mukhopadhyay",
        year: null,
        note: "Dwijen Mukhopadhyay calling the goddess awake, ten weapons and all. Two minutes, no fat on it, and the whole programme tilts upward from here.",
        youtubeId: "E_3DoeyToto",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "যা চণ্ডী মধুকৈটভাদি",
        titleRoman: "Ya Chandi Madhukaitabhadi",
        artist: "Chorus, composed by Pankaj Kumar Mullick",
        year: null,
        note: "Sanskrit chorus in Malkauns, dark and level. Mullick's arrangement makes a ritual stotra sound like a chorus of people walking toward something in the dark.",
        youtubeId: "8FytVk54-dw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "অখিল বিমানে তব জয়গানে",
        titleRoman: "Akhila Bimane Tabo Jaya Gane",
        artist: "Krishna Dasgupta",
        year: null,
        note: "Krishna Dasgupta's voice opening the whole sky out. One of the pieces people mean when they say the Mahalaya songs are better than anything on the radio the rest of the year.",
        youtubeId: "FrHp3pXxeNU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বিমানে বিমানে আলোকের গানে",
        titleRoman: "Bimane Bimane Aloker Gane",
        artist: "Sandhya Mukhopadhyay",
        year: null,
        note: "Sandhya Mukhopadhyay at her most weightless. Light travelling through light, which is more or less what the lyric says and exactly what her voice does with it.",
        youtubeId: "-ZJtci1_Ih0",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "ওগো আমার আগমনী আলো",
        titleRoman: "Ogo Amar Agomoni Alo",
        artist: "Shipra Bose",
        year: null,
        note: "The Agomoni light itself, addressed directly. Shipra Bose sings it as a greeting rather than a prayer, which is why it carries so easily into the rest of the Puja week.",
        youtubeId: "2RZZzJdzGPM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "শান্তি দিলে ভরি",
        titleRoman: "Shanti Dile Bhori",
        artist: "Utpala Sen",
        year: null,
        note: "Utpala Sen, quiet and steady, asking to be filled with peace. It sits in the programme like a held breath between two louder passages.",
        youtubeId: "VAV6OQMe-to",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "তব অচিন্ত্য রূপচরিতমহিমা",
        titleRoman: "Tabo Achintya Rupacharita-Mahima",
        artist: "Manabendra Mukhopadhyay",
        year: null,
        note: "Manabendra Mukhopadhyay's great set piece, all classical shading and long lines. Four minutes that justify the claim that this was radio made by serious musicians.",
        youtubeId: "6rwF1iQPVzc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জয় জয় জপ্য জয়ে",
        titleRoman: "Jaya Jaya Japya Jaye",
        artist: "Chorus, composed by Pankaj Kumar Mullick",
        year: null,
        note: "The victory chorus. If you only want one piece of the programme to signal that the battle has been won, this is the one people reach for.",
        youtubeId: "AB4IUcvuEXs",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "অহং রুদ্রেভির্বসুভিশ্চরামি",
        titleRoman: "Aham Rudrebhir Vasubhishcharami",
        artist: "Chorus",
        year: null,
        note: "The Devi Sukta, the goddess declaring herself in the first person. Four minutes of massed voices that make the Sanskrit sound less like scripture and more like an announcement.",
        youtubeId: "GJccKU4_5wg",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মা গো তব বীণে সঙ্গীতা",
        titleRoman: "Ma Go Tabo Bine Sangeeta",
        artist: "Sumitra Sen",
        year: null,
        note: "Sumitra Sen, the quietest voice in the whole programme. Easy to miss on a first listen and impossible to forget once you have noticed it.",
        youtubeId: "qdx842oMwnA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নারায়ণী নমোস্তুতে",
        titleRoman: "Narayani Namostute",
        artist: "Birendra Krishna Bhadra",
        year: null,
        note: "Bhadra reciting the Narayani Stuti from the Durga Vandana sessions. The same voice, the same stillness, in a piece short enough to loop on a page.",
        youtubeId: "lb2Fwp5y_U0",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মহিষাসুরমর্দিনী, দ্বিতীয় পর্ব",
        titleRoman: "Mahishasuramardini, Part II",
        artist: "Birendra Krishna Bhadra and company",
        year: 1966,
        note: "The second half on its own, for the listener who already knows the opening by heart and wants to start where the fighting does.",
        youtubeId: "KSait1b91Kw",
        channel: "Saregama Bengali",
      },
    ],
  },
  {
    id: "agomoni-bijoya",
    bangla: "আগমনী ও বিজয়া",
    roman: "Agomoni o Bijoya",
    blurb: "The oldest story Bengal tells itself: a daughter comes home for four days and then has to go back. Ramprasad, Kamalakanta, Dasarathi Ray and Nazrul, sung by Dhananjay Bhattacharya, Ramkumar Chattopadhyay and a handful of people still writing new ones. Agomoni is the arrival, Bijoya is the leaving, and Bengalis have never quite got over either.",
    tracks: [
      {
        titleBangla: "আমার গৌরীরে লয়ে",
        titleRoman: "Amar Gouri Re Loye",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Menaka pleading for her daughter, sung by the voice that defined Agomoni on 78rpm. The ache in it is a mother's, not a devotee's, and that is the whole point.",
        youtubeId: "Y7D9kh0YDUw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "শরৎ-কমল মুখে আধ আধ বাণী",
        titleRoman: "Sharat Kamal Mukhe Adho Adho Bani",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Autumn lotus, half-formed words, a small daughter remembered. Pure Agomoni imagery, and Dhananjay Bhattacharya sings it without a gram of sentimentality.",
        youtubeId: "i_z7Q84a-Ks",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নবমী নিশি পোহালো",
        titleRoman: "Nabami Nishi Pohalo",
        artist: "Kamala Jharia",
        year: null,
        note: "Navami night has ended, and everyone in the house knows what tomorrow means. Kamala Jharia's shellac-era voice makes the dread of Dashami feel very close.",
        youtubeId: "fPNrD2TH5OQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এবারে উমা এলে আবার",
        titleRoman: "Ebare Uma Ele Abar",
        artist: "Abhayapada Chattopadhyay",
        year: null,
        note: "Uma has come again, and this time the mother bargains for longer. A plain, direct Agomoni from the old Aay Ma Uma record.",
        youtubeId: "plhPinMfUJQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "উমাকে বিদায় দিয়া",
        titleRoman: "Umake Biday Diya",
        artist: "K. Mullick",
        year: null,
        note: "The Bijoya counterpart: having sent Uma away, what does a house do with itself. Three minutes that explain why Dashami in Bengal feels like a small bereavement.",
        youtubeId: "Kdk-7ntIA3o",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এলো গিরিনন্দিনী",
        titleRoman: "Elo Girinandini",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "The mountain king's daughter has arrived. Bright, processional, the sound of a household throwing its doors open, and a good opener for any Agomoni set.",
        youtubeId: "6OghjYRe2to",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "কেমনে মা ভুলেছিলি",
        titleRoman: "Kemone Ma Bhulechhili",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "How could you forget us, mother. The reproach every Bengali parent has delivered to a child who moved away, sung straight at the goddess.",
        youtubeId: "69KKacIQyLY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "হে শিব শঙ্কর",
        titleRoman: "He Shiv Shankar",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Addressed to the famously unreliable son-in-law up on Kailash. Agomoni is a family drama, and this is the song where the in-laws get a word in.",
        youtubeId: "XKwHFP5puUA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এবার নবীন মন্ত্রে হবে",
        titleRoman: "Ebar Nabin Mantre Hobe",
        artist: "Anup Ghoshal",
        year: null,
        note: "A newer Puja song that asks for the worship to be renewed rather than repeated. Anup Ghoshal's clarity keeps it from tipping into piety.",
        youtubeId: "GtmxMUkSEJ8",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আজি শঙ্খে শঙ্খে মঙ্গল গাও",
        titleRoman: "Aji Shankhe Shankhe Mangala Gao",
        artist: "Anup Ghoshal",
        year: null,
        note: "Conch answering conch across a courtyard. The lyric is basically an instruction for how to make a morning auspicious, and it works as one.",
        youtubeId: "ZeVok4tMfSs",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এত গয়না বেটী কোথায় পেলি",
        titleRoman: "Eto Goyna Beti Kothay Peli",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "A mother inspecting her daughter's jewellery and asking, with narrowed eyes, where it all came from. Agomoni as tappa, gossipy and affectionate at once.",
        youtubeId: "joiwefTFzBI",
        channel: "Inreco Devotional",
      },
      {
        titleBangla: "যাও যাও গিরি আনিতে গৌরী",
        titleRoman: "Jao Jao Giri Anite Gouri",
        artist: "Swami Samapriyananda",
        year: null,
        note: "Ramprasad's famous command to the mountain king: go, fetch our daughter. Sung here in the Baghbazar math's own recording, unhurried and completely unshowy.",
        youtubeId: "gNursnkOVsQ",
        channel: "Udbodhan - Ramakrishna Math Baghbazar",
      },
      {
        titleBangla: "গিরি গণেশ আমার শুভকারী",
        titleRoman: "Giri Ganesh Amar Shubhokari",
        artist: "Agomoni recital at Belur Math",
        year: 2019,
        note: "The Agomoni sung live at Belur Math, with the room audible around it. A useful reminder that these songs belong to courtyards, not studios.",
        youtubeId: "iaFdu3yilUA",
        channel: "Ramakrishna Math & Ramakrishna Mission, Belur Math",
      },
      {
        titleBangla: "নবমী নিশিরে",
        titleRoman: "Nabami Nishire",
        artist: "Hemanta Mukhopadhyay",
        year: 1958,
        note: "Hemanta taking the Navami-night lament into his own low register. Less folk, more midnight radio, and it lands somewhere very tender. Released 1958, composed by Robin Chatterjee.",
        youtubeId: "8cIMHSg8Aew",
        channel: "Saregama India Ltd (auto-generated YouTube Topic channel)",
      },
      {
        titleBangla: "আমার আনন্দিনী উমা",
        titleRoman: "Amar Anandini Uma",
        artist: "Payel Kar",
        year: null,
        note: "Nazrul's Agomoni, written by a Muslim poet about a Hindu mother's daughter, which is a very Bengali fact worth keeping on a Puja page.",
        youtubeId: "CUDl3xltHPM",
        channel: "Payel Kar (Topic)",
      },
      {
        titleBangla: "আগমনীর গান",
        titleRoman: "Agomonir Gaan",
        artist: "Anupam Roy",
        year: 2018,
        note: "Anupam Roy writing a new Agomoni for people who commute. It keeps the old shape, the coming and the leaving, and swaps the courtyard for a city.",
        youtubeId: "MsqpjM09MrY",
        channel: "SVF Music",
      },
      {
        titleBangla: "আগমনী আলো",
        titleRoman: "Agomoni Aalo",
        artist: "Jayati Chakraborty",
        year: 2019,
        note: "Jayati Chakraborty's contemporary Agomoni, sung with a folk singer's patience. Proof that the form is still being written and not just archived.",
        youtubeId: "bvij2HdGgv4",
        channel: "Jayati Chakraborty",
      },
      {
        titleBangla: "বিজয়ার গান",
        titleRoman: "Bijoyar Gaan",
        artist: "Ramkumar Chattopadhyay, Chandidas Mal, Sreeradha Bandyopadhyay, Sayantani Majumder",
        year: null,
        note: "A full half hour of Dashami songs in one place. Save it for the evening of the immersion, when nobody wants anything faster than this.",
        youtubeId: "psjbjwSwq7E",
        channel: "Perennial Records",
      },
    ],
  },
  {
    id: "city",
    bangla: "শহরের পুজো",
    roman: "Sohorer Pujo",
    blurb: "Kolkata in the Puja week: the pandal-hopping, the new clothes, the coffee house, the rock band at a volume nobody licensed. This is the HMV Pujor gaan tradition and everything it turned into - Hemanta, Manna Dey, Sandhya, Kishore, Cactus, Fossils, Bhoomi, Anjan Dutt, Anupam Roy, Lakkhichhara.",
    tracks: [
      {
        titleBangla: "কফি হাউসের সেই আড্ডাটা",
        titleRoman: "Coffee Houser Sei Addata Aaj Aar Nei",
        artist: "Manna Dey",
        year: 1983,
        note: "The national anthem of Bengali adda and of everyone who has ever left a city and come back to find the table empty. Seven minutes, and nobody talks over it.",
        youtubeId: "kvadzdVaTtg",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "যদি কাগজে লেখো নাম",
        titleRoman: "Jodi Kagoje Lekho Naam",
        artist: "Manna Dey",
        year: null,
        note: "Manna Dey doing the thing only he could do, classical training worn lightly over a pop song. A staple of the Puja-release era and still a request every year.",
        youtubeId: "jIaIXjBqyjE",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এই মেঘলা দিনে একলা",
        titleRoman: "Ei Meghla Dine Ekla",
        artist: "Hemanta Mukhopadhyay",
        year: null,
        note: "The overcast-afternoon song. Bengal's Puja weather is exactly this, bright then suddenly grey, and Hemanta's voice is the sound of waiting it out.",
        youtubeId: "aFEPYpcmkEM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমায় প্রশ্ন করে নীল ধ্রুবতারা",
        titleRoman: "Amay Prashna Kare Neel Dhrubatara",
        artist: "Hemanta Mukhopadhyay",
        year: null,
        note: "A Puja release that outlived its season by sixty years. The blue pole star asks a question and Hemanta declines, beautifully, to answer it.",
        youtubeId: "Quw_xNFSfik",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এই পথ যদি না শেষ হয়",
        titleRoman: "Ei Poth Jodi Na Shesh Hoy",
        artist: "Hemanta Mukhopadhyay and Sandhya Mukhopadhyay",
        year: 1961,
        note: "From Saptapadi, and the duet every Bengali couple has hummed on a scooter. If the road never ended. On Puja nights in Kolkata, briefly, it doesn't.",
        youtubeId: "MV7NxsPLkmA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মধুমালতী ডাকে আয়",
        titleRoman: "Madhumalati Dake Aay",
        artist: "Sandhya Mukhopadhyay",
        year: null,
        note: "Sandhya Mukhopadhyay at full brightness, a flower calling a child out to play. Put it on in the morning and the whole page feels like a holiday.",
        youtubeId: "yUAG20NEhZI",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "সেদিনের সোনাঝরা সন্ধ্যা",
        titleRoman: "Sediner Sonajhara Sandhya",
        artist: "Shyamal Mitra",
        year: null,
        note: "That one gold-drenched evening, remembered later. Shyamal Mitra's speciality was nostalgia arriving on schedule, which is what Puja does to people anyway.",
        youtubeId: "xw4_01zGsAk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "সেই রাতে রাত ছিল পূর্ণিমা",
        titleRoman: "Sei Rate Raat Chhilo Purnima",
        artist: "Kishore Kumar",
        year: null,
        note: "Kishore Kumar's Bengali voice, which is a different instrument from his Hindi one, warmer and less hurried. A permanent fixture of the Pujor gaan lists.",
        youtubeId: "07BadGcIEe4",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নয়ন সরসী কেন ভরেছে জলে",
        titleRoman: "Nayan Sarasi Keno Bhoreche Jale",
        artist: "Kishore Kumar",
        year: null,
        note: "Why are your eyes full of water. Kishore asks it gently and then spends three minutes not pressing for an answer. Peak Bengali modern song.",
        youtubeId: "EQBo0OVSGXQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "টাপুর টুপুর সারা দুপুর",
        titleRoman: "Tapur Tupur Sara Dupur",
        artist: "Arati Mukhopadhyay",
        year: null,
        note: "Rain on a tin roof all afternoon, rendered as a tune. Arati Mukhopadhyay sings it like someone genuinely delighted to have nowhere to be.",
        youtubeId: "J_NRMfOVRXY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমার নয়ন-ভুলানো এলে",
        titleRoman: "Amar Nayan-Bhulano Ele",
        artist: "Suchitra Mitra",
        year: null,
        note: "Tagore's Sharat song, and arguably the finest thing ever written about the Bengali autumn. Suchitra Mitra sings it with no decoration at all.",
        youtubeId: "S80EQpRWrzc",
        channel: "Suchitra Mitra (Topic)",
      },
      {
        titleBangla: "হলুদ পাখি",
        titleRoman: "Halud Pakhi",
        artist: "Cactus",
        year: null,
        note: "The Bengali rock song that a whole generation learned on a borrowed guitar. Six minutes, and by the last chorus the pandal crowd is singing it back.",
        youtubeId: "fpMH2DW_lmM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "একলা ঘর",
        titleRoman: "Ekla Ghor",
        artist: "Fossils (Rupam Islam)",
        year: null,
        note: "Fossils at their loudest and loneliest. Every Kolkata Puja has one pandal playing this at a volume the licence probably does not permit.",
        youtubeId: "8Abt_zhpjak",
        channel: "Fossils (Topic)",
      },
      {
        titleBangla: "বারান্দায় রোদ্দুর",
        titleRoman: "Barandaye Roddur",
        artist: "Bhoomi",
        year: null,
        note: "Sunlight on a balcony, which is the single most Bengali image available. Bhoomi took folk instruments into pop and the Puja circuit never recovered.",
        youtubeId: "E70oxtms_qg",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "২৪৪১১৩৯ (বেলা বোস)",
        titleRoman: "2441139 (Bela Bose)",
        artist: "Anjan Dutt",
        year: null,
        note: "A landline number, a boy with no job, and the nerve to call anyway. Anjan Dutt wrote Kolkata's most quotable song and it still gets shouted back at him.",
        youtubeId: "0iUmptTmJ2k",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমাকে আমার মতো থাকতে দাও",
        titleRoman: "Amake Amar Moto Thakte Dao",
        artist: "Anupam Roy",
        year: 2010,
        note: "The song that reset Bengali songwriting for everyone under forty. Let me be as I am, sung by a man who clearly means it.",
        youtubeId: "ilgT99XFUq8",
        channel: "Anupam Roy (Topic)",
      },
      {
        titleBangla: "পুজো পুজো গন্ধ",
        titleRoman: "Pujo Pujo Gondho",
        artist: "Anupam Roy",
        year: 2024,
        note: "A modern Pujo-release single about the smell of Pujo arriving before Pujo does. Shiuli, new clothes, damp air; it names the thing exactly.",
        youtubeId: "V5rSZgw0xfk",
        channel: "SVF",
      },
      {
        titleBangla: "পদবি",
        titleRoman: "Padabi",
        artist: "Lakkhichhara",
        year: 2026,
        note: "Lakkhichhara back after a decade, still arguing with the city. Included because a Kolkata Puja page that skips the rock bands is telling only half the story.",
        youtubeId: "eri590rFW2I",
        channel: "Lakkhichhara Music",
      },
    ],
  },
  {
    id: "village",
    bangla: "গ্রামের পুজো",
    roman: "Gramer Pujo",
    blurb: "The same four days on the bank of a river. Baul and bhatiali and dhamail and jhumur, Lalon's questions, Abbasuddin's boatmen, Dohar's Agomoni sung with hand percussion in a courtyard. This is the register the Agomoni songs were written in before the recording studios found them.",
    tracks: [
      {
        titleBangla: "গৌরী এলো",
        titleRoman: "Gouri Elo",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "Gouri has come, go and look at her. Dohar sing Agomoni the way a village actually sings it, with hand percussion and no ceremony whatsoever.",
        youtubeId: "VLUppccFWrA",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "ঢাকের বোলে বাংলা দোলে",
        titleRoman: "Dhaker Bole Bangla Dole",
        artist: "Dohar",
        year: null,
        note: "Bengal swaying to the dhak's syllables. This is the song to reach for when the ambience mixer is already running the drum layer and you want the two to meet.",
        youtubeId: "SDCcfKvIcyQ",
        channel: "Dohar (Topic)",
      },
      {
        titleBangla: "একবার নাচো মা",
        titleRoman: "Ekbar Nacho Maa",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "Shyama sangeet with a dancing pulse instead of a mournful one. Forty million people have played this; it turns out the village register travels.",
        youtubeId: "EZbQ-uaDbw4",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "হৃদমাঝারে রাখব",
        titleRoman: "Hrid Majhare Rakhbo",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "I will keep you in the middle of my heart and never let you go. A Baul line that works as devotion, as love song and as farewell, which is why it never leaves.",
        youtubeId: "DXx9gMpj9k0",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "বন্ধু বিনে প্রাণ বাঁচে না",
        titleRoman: "Bandhu Bine Pran Bache Na",
        artist: "Dohar, Radharaman Dutta (dhamail)",
        year: null,
        note: "A dhamail from Sylhet, the circle song women sing at weddings. It belongs on a Puja page because Puja in a village is mostly women singing in a circle.",
        youtubeId: "TYAG2HmhlZ4",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "শুভ্র শারদ রাঙা",
        titleRoman: "Shubhra Sharad Ranga",
        artist: "Dohar",
        year: 2024,
        note: "Dohar's own Durga Puja single, written for the season rather than borrowed into it. White autumn light, folk instruments, and a tune that walks rather than marches.",
        youtubeId: "2tUkXTPKcvA",
        channel: "Hindusthan Record",
      },
      {
        titleBangla: "হৃদমাঝারে রাখব",
        titleRoman: "Hrid Majhare Rakhbo",
        artist: "Purna Das Baul",
        year: null,
        note: "The same song from the Baul Samrat himself, ektara and all. Set it next to the Dohar version and you can hear a tradition being handed across a generation.",
        youtubeId: "MF8pLSGzdWE",
        channel: "Baul Samrat Purna Das",
      },
      {
        titleBangla: "গোলেমালে গোলেমালে পিরিত কইরো না",
        titleRoman: "Golemale Golemale Pirit Koiro Na",
        artist: "Purna Das Baul",
        year: null,
        note: "Do not fall in love in a hurry, warns the Baul, plainly enjoying himself. Folk wisdom delivered as a joke, which is the Baul house style.",
        youtubeId: "uZSlIdIlW_U",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "দেখেছি রূপসাগরে মনের মানুষ",
        titleRoman: "Dekhechhi Rup-Sagare Moner Manush",
        artist: "Purna Das Baul",
        year: null,
        note: "Lalan's moner manush, the person of the heart, glimpsed in an ocean of form. The central idea of Baul thought, sung by its most travelled voice.",
        youtubeId: "8Edxs3WVMyQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আসছে জামাই দিগম্বর",
        titleRoman: "Ashchhe Jamai Digombor",
        artist: "Parvathy Baul",
        year: 2024,
        note: "The naked son-in-law is on his way. Shiva turning up to collect his wife, treated with exactly the mixture of alarm and affection a Bengali family would use.",
        youtubeId: "Fuhyx9iCUJI",
        channel: "SVF Music",
      },
      {
        titleBangla: "কিছুদিন মনে মনে",
        titleRoman: "Kichhu Din Mone Mone",
        artist: "Parvathy Baul",
        year: null,
        note: "Parvathy Baul alone with an ektara and a duggi, singing about keeping something inside for a while. Five minutes that make a webpage feel like a riverbank.",
        youtubeId: "tNh2kjmSzPw",
        channel: "ajab shahar - kabir project",
      },
      {
        titleBangla: "আমার বন্ধুর সাথে প্রেম করো",
        titleRoman: "Amar Bondhur Sathe Prem Koro",
        artist: "Parvathy Baul",
        year: 2026,
        note: "A long-form Baul performance from her own channel, unedited. Worth putting somewhere quiet on the page for people who want to stay a while.",
        youtubeId: "ZBwi-yV5MLU",
        channel: "Parvathy Baul",
      },
      {
        titleBangla: "সব লোকে কয় লালন কী জাত",
        titleRoman: "Shob Loke Koy Lalon Ki Jat",
        artist: "Arati Mukhopadhyay",
        year: null,
        note: "Everyone asks what caste Lalon is. The most necessary song in the Bengali language, and a good thing to have playing in a Puja pandal.",
        youtubeId: "lVH0C2lfktM",
        channel: "Arati Mukherjee (Topic)",
      },
      {
        titleBangla: "সব লোকে কয় লালন",
        titleRoman: "Sob Loke Koy Lalon",
        artist: "Fakira",
        year: null,
        note: "The same Lalon song in a contemporary band arrangement. Useful for showing that the fakir's question is still being asked, and still not answered.",
        youtubeId: "TaGMMbYF5yc",
        channel: "Inreco Bangla",
      },
      {
        titleBangla: "আমায় ভাসাইলি রে",
        titleRoman: "Amay Bhasaili Re",
        artist: "Abbasuddin Ahmed",
        year: null,
        note: "The great bhatiali, sung by a boatman to a river that has both floated and drowned him. If the page wants the Ganga in it, this is the sound of the Ganga.",
        youtubeId: "vwmx1Keh7tg",
        channel: "Abbas Uddin Ahamed (Topic)",
      },
      {
        titleBangla: "নদীর কূল নাই কিনার নাই",
        titleRoman: "Nodir Kul Nai Kinar Nai",
        artist: "Abbasuddin Ahmed, words by Jasimuddin",
        year: null,
        note: "The river has no bank and no edge. Jasimuddin's line and Abbasuddin's voice, the definitive statement of what a Bengali river does to a person.",
        youtubeId: "BWJNVhysc7w",
        channel: "Abbas Uddin Ahamed (Topic)",
      },
      {
        titleBangla: "এবার আমার উমা এলে",
        titleRoman: "Ebar Amar Uma Ele",
        artist: "Amar Pal",
        year: null,
        note: "Ramprasad's Agomoni sung in full folk register by a lokgeeti master. This is what Agomoni sounds like before the recording studios got hold of it.",
        youtubeId: "_f6rpEoqBgw",
        channel: "Perennial Records",
      },
      {
        titleBangla: "রাই জাগো রাই জাগো",
        titleRoman: "Rai Jago Rai Jago Bole",
        artist: "Amar Pal",
        year: null,
        note: "The pre-dawn waking song, sung by villagers walking the lanes before sunrise. The exact rural counterpart to what Akashvani does for the city on Mahalaya.",
        youtubeId: "tzNeTDxuMd4",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জয় জয় বিজয়াগমন",
        titleRoman: "Joyo Joyo Bijoyagaman",
        artist: "Dohar and Iman Chakraborty",
        year: 2023,
        note: "Dohar's folk chorus meeting a contemporary singer for a Dashami song. Written for a film, but it walks straight back into the village it came from.",
        youtubeId: "zu07LXoyxro",
        channel: "WINDOWS",
      },
      {
        titleBangla: "পাহাড়ের রানী",
        titleRoman: "Paharer Rani",
        artist: "Josna Mahato",
        year: 2024,
        note: "Jhumur from Jhargram, the Puja music of western Bengal that Kolkata mostly forgets. Included so the village on this page is not only a riverside one.",
        youtubeId: "-Jl_MMjtNMk",
        channel: "Josna Rani Jhumur Official",
      },
    ],
  },
  {
    id: "funny",
    bangla: "হাসির গান",
    roman: "Hashir Gaan",
    blurb: "Pujo is mostly adda, and adda is mostly people trying to make each other laugh. Chandrabindoo's deadpan, Nachiketa's satire, Ramkumar Chattopadhyay's hymn to the luchi, and the shellac-era comic songs of Ranjit Roy and Mintoo Dasgupta that invented the whole genre. Warm throughout, and safe to play in front of anyone's grandmother.",
    tracks: [
      {
        titleBangla: "গীত গোবিন্দ",
        titleRoman: "Geet Gobindo",
        artist: "Chandrabindoo",
        year: null,
        note: "Chandrabindoo's finest piece of deadpan, a whole relationship conducted in the wrong register. The joke lands, then keeps landing on later listens.",
        youtubeId: "4IWOO9luQr4",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "আমরা বাঙালি জাতি",
        titleRoman: "Amra Bangali Jaati",
        artist: "Chandrabindoo",
        year: null,
        note: "We, the Bengali people, gently and comprehensively taken apart by three Bengalis. Affectionate, merciless, and the single best adda-starter on this list.",
        youtubeId: "E6zKpNDQQlM",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "যুযু",
        titleRoman: "Juju",
        artist: "Chandrabindoo",
        year: null,
        note: "The bogeyman song. Three minutes of absurdist nonsense delivered with a completely straight face, which is the Chandrabindoo method in miniature.",
        youtubeId: "IR6du_cY2Q4",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "রোগা বল না",
        titleRoman: "Roga Bolo Na",
        artist: "Chandrabindoo",
        year: null,
        note: "Please do not call me skinny. A small domestic grievance turned into a pop song, which is roughly ninety percent of what Chandrabindoo does.",
        youtubeId: "XeXikL8dyo8",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "ব্যাঙাখোকা",
        titleRoman: "Byanakhoka",
        artist: "Chandrabindoo, featuring Anindya Chatterjee",
        year: null,
        note: "Frog-child. Nonsense verse in the Sukumar Ray line of descent, which every Bengali child is raised on and every Bengali adult still finds funny.",
        youtubeId: "RSREUs8zhKo",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "বাথরুম",
        titleRoman: "Bathroom",
        artist: "Chandrabindoo",
        year: null,
        note: "A love song set entirely in a bathroom, sung with total sincerity. Silly in the best way and completely safe to play in front of anyone's grandmother.",
        youtubeId: "5Z8b0DtlLBk",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "লাল বল নীল বল",
        titleRoman: "Laal Ball Neel Ball",
        artist: "Chandrabindoo (Upal Sengupta)",
        year: 2025,
        note: "Upal Sengupta on cricket, colour and the passage of time, from the band's own channel. Newer, funnier and a little sadder than it first looks.",
        youtubeId: "jCPUEx_xcV8",
        channel: "Chandrabindoo",
      },
      {
        titleBangla: "ওগো লুচি, তোমার মান্য ত্রিভুবনে",
        titleRoman: "Ogo Luchi Tomar Manyo Tribhubane",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "A formal hymn of praise addressed to the luchi. Amritalal Basu wrote it in the nineteenth century and Bengalis have not stopped agreeing with it since.",
        youtubeId: "IjwkqgVipeI",
        channel: "Perennial Records",
      },
      {
        titleBangla: "কাদের কুলের বৌ গো তুমি",
        titleRoman: "Kader Kuler Bou Go Tumi",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "Old Kolkata baithaki comedy, a whole neighbourhood's curiosity about a new bride compressed into three minutes. Warm, gossipy, never unkind.",
        youtubeId: "livUpNNgKVg",
        channel: "INRECO BENGALI",
      },
      {
        titleBangla: "আমি হজমি বটিকা",
        titleRoman: "Aami Hojmi Botika",
        artist: "Ranjit Roy",
        year: 1937,
        note: "A shellac-era parody in which a man introduces himself as a digestive tablet. Bengali comic song at its origin point, and genuinely still funny.",
        youtubeId: "G3zZ3lNcfmY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বুড়োকে ব্লাফ দিয়ে",
        titleRoman: "Buroke Bluff Diye",
        artist: "Mintoo Dasgupta",
        year: null,
        note: "Mintoo Dasgupta was the great Bengali parodist, setting domestic mischief to borrowed tunes. Bluffing the old man, four minutes, entirely affectionate.",
        youtubeId: "-Iu8BO4QQ8I",
        channel: "Mintoo Dasgupta (Topic)",
      },
      {
        titleBangla: "শোনো গো প্রাণের রাণু",
        titleRoman: "Sono Go Praner Ranu",
        artist: "Mintoo Dasgupta and Neela Banerjee",
        year: null,
        note: "A comic duet issued as a Pujor gaan, from the era when the Puja record releases carried the jokes as well as the romance.",
        youtubeId: "qoLyrlxtxMY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "পেটকাটি চাঁদিয়াল",
        titleRoman: "Petkati Chandiyal",
        artist: "Kabir Suman",
        year: 1992,
        note: "Kite names as a list of everything a Kolkata childhood contained. Not a joke song exactly, but it produces the same grin, and it belongs at every adda.",
        youtubeId: "nFuXgbnvglc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমি মুখ্যু সুখ্যু মানুষ",
        titleRoman: "Ami Mukkhu Sukkhu Manush",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "I am a simple uneducated man, says the narrator, before demolishing everyone cleverer than him. Nachiketa's satire, sharp but never sour.",
        youtubeId: "ucJ-RRFOyKU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "কপাল আমার মন্দ",
        titleRoman: "Kapal Amar Mondo",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "A comprehensive and very funny complaint about bad luck. The self-pity is the joke, and Nachiketa knows exactly when to let the listener in on it.",
        youtubeId: "JMlEKWyKoUk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "পচা কাকা",
        titleRoman: "Pocha Kaka",
        artist: "Bhoomi",
        year: null,
        note: "Every Bengali neighbourhood has a Pocha Kaka, and Bhoomi wrote him a theme tune. Silly, singable, and the reason this song outlives its album.",
        youtubeId: "bVdKik75E8A",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "রঞ্জনা আমি আর আসবো না",
        titleRoman: "Ranjana Ami Ar Ashbo Na",
        artist: "Anjan Dutt",
        year: null,
        note: "A breakup delivered as a shrug and a suitcase. The humour is in the timing, and by the second chorus a whole room is shouting the title back.",
        youtubeId: "tbi2eYL89Uk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মায়া",
        titleRoman: "Maya (full album)",
        artist: "Mohiner Ghoraguli",
        year: null,
        note: "The album that invented Bengali band music, wry and shambolic and forty years ahead of itself. Includes Telephone, the funniest sad song in the language.",
        youtubeId: "cwjzEa8xrbc",
        channel: "Asha Audio",
      },
    ],
  },
];

/** Why the Mahalaya recitation is embedded and never hosted. */
export const MAHALAYA_RIGHTS = "Mahishasuramardini cannot be self-hosted, and the IISc site should not put an audio file of it on its own server. The chain of rights is unusually well documented. The script is by Bani Kumar, the music by Pankaj Kumar Mullick and the narration by Birendra Krishna Bhadra; the programme went out live on All India Radio from the mid-1930s and was committed to a definitive studio recording in 1966, which is the version broadcast ever since. Copyright therefore sits in two places at once. Prasar Bharati / All India Radio holds the broadcast and the underlying programme, and its published copyright policy (prasarbharati.gov.in/copyright-policy/) is restrictive and explicit: \"You may only access and use the material for personal or educational purposes\" and \"you may not reproduce, republish, post, transmit or distribute any material\" without written consent. That is not a licence to host or to re-serve an audio file. Separately, the commercial sound-recording rights to the 1966 master were acquired from AIR by HMV-RPG, now Saregama India Ltd, which has released it on LP, cassette, CD and digitally, and which operates the Saregama Bengali YouTube channel. Nothing in this is public domain: the 1966 recording is comfortably inside the Indian sound-recording term, and the compositions of Pankaj Mullick (d. 1978) and the text of Bani Kumar (d. 1980) are still in copyright in India as well. The one legal, zero-cost route is to EMBED the rights-holder's own YouTube upload, which is what this research recommends. Saregama Bengali's full-programme upload at youtube.com/watch?v=YQyo8QeoYhc is the rights holder publishing its own master, embedding is enabled on it (verified), and the YouTube embed carries the licence with it. There is also a channel called \"Akashvani AIR\" (UCdwm5QNss1TpY_whBkql0dw) carrying a 1966 Mahishasuramardini and a Bengali full version; it presents itself as All India Radio, but I could NOT confirm from Prasar Bharati's own site that it is an official Prasar Bharati channel, so it is listed here only as a secondary option and the Saregama upload should be preferred. Practical rule for the build: embed, never download; never rip to MP3 and serve it from the IISc domain; never put it behind a wall or over a donation prompt; and credit it on the page as \"Mahishasuramardini, All India Radio, 1966. Narration Birendra Krishna Bhadra, script Bani Kumar, music Pankaj Kumar Mullick. Recording courtesy Saregama India Ltd.\"";
