/**
 * The listening room.
 *
 * Two different things with two different rules.
 *
 * The ambient layers are freely licensed recordings, CC0 or CC BY,
 * every licence checked individually. They can be hosted and mixed,
 * and every one is credited on the page as its licence requires.
 *
 * The songs are not ours and are never hosted. They are embedded from
 * the rights holder's own upload, which is the only honest way to put
 * Bengali film and folk recordings on a website. Each video id was
 * checked to resolve to the right song and to allow embedding at all,
 * because roughly a quarter of the obvious uploads quietly do not.
 *
 * Generated from research/music.json.
 */

export type AmbienceLayer = {
  id: string;
  bangla: string;
  roman: string;
  description: string;
  sourceUrl: string;
  /** Used until the committee downloads a local copy. */
  remoteUrl: string;
  licence: string;
  licenceUrl: string;
  attribution: string;
  durationSeconds: number | null;
  caveat: string | null;
};

export type Track = {
  titleBangla: string;
  titleRoman: string;
  artist: string;
  year: number | null;
  note: string;
  youtubeId: string;
  channel: string;
};

export type Collection = {
  id: string;
  bangla: string;
  roman: string;
  blurb: string;
  tracks: Track[];
};

export const AMBIENCE: AmbienceLayer[] = [
  {
    id: "dhak",
    bangla: "ঢাক",
    roman: "Dhak",
    description: "The barrel drum itself, slung from the shoulder and struck with two canes. Uploaded to Wikimedia by a Bengali contributor who recorded it for exactly this purpose: to show what a dhak sounds like at a Durga Puja. Two minutes of it, which is long enough that the loop stops announcing itself.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rhythm_of_Dhak_a_huge_membranophone_instrument_from_Bengal_and_Assam,_used_in_Hindu_religious_festivals,_especially_Durga_Puja.mp3",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Rhythm_of_Dhak_a_huge_membranophone_instrument_from_Bengal_and_Assam%2C_used_in_Hindu_religious_festivals%2C_especially_Durga_Puja.mp3",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "“Rhythm of Dhak…” by Sumita Roy Dutta, via Wikimedia Commons, CC BY-SA 4.0",
    durationSeconds: 130,
    caveat: null,
  },
  {
    id: "kanshor_ghanta",
    bangla: "কাঁসর ঘণ্টা",
    roman: "Gong",
    description: "A struck bell-metal gong, standing in for the kansar, the flat disc beaten during arati. It is not a kansar and we are not going to pretend it is. No recording of one exists under any licence we can use.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gong_or_bell_vibrant.ogg",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Gong_or_bell_vibrant.ogg",
    licence: "Public domain (PD-author release)",
    licenceUrl: "https://commons.wikimedia.org/wiki/File:Gong_or_bell_vibrant.ogg",
    attribution: "“Gong or Bell, vibrant” by stephan, originally from pdsounds.org, public domain, via Wikimedia Commons",
    durationSeconds: 64,
    caveat: "A stand-in. This is a generic bell-metal gong, not a Bengali kansar.",
  },
  {
    id: "shankha",
    bangla: "শঙ্খ",
    roman: "Shankha",
    description: "A conch, blown once. Six and a half seconds, which is all a conch is, and the reason this fader sets how often it sounds rather than how loudly it drones. Recorded for the Wikipedia article on conches.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Conch_shell.ogg",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/2/24/Conch_shell.ogg",
    licence: "CC BY 2.5",
    licenceUrl: "https://creativecommons.org/licenses/by/2.5",
    attribution: "“Conch shell” by David Bolton (User:Dbolton), via Wikimedia Commons, CC BY 2.5",
    durationSeconds: 7,
    caveat: null,
  },
  {
    id: "mandir_ghanta",
    bangla: "মন্দিরের ঘণ্টা",
    roman: "Temple Bells",
    description: "Temple bells in Delhi, recorded for the radio aporee sound map. Irregular, overlapping, a dozen hands at once, which is what a temple actually sounds like and what a single sampled bell never does.",
    sourceUrl: "https://archive.org/details/aporee_51432_58687",
    remoteUrl: "https://archive.org/download/aporee_51432_58687/09PiotrekZylaPrakrtiTempleBells.mp3",
    licence: "Public Domain Mark 1.0",
    licenceUrl: "http://creativecommons.org/publicdomain/mark/1.0/",
    attribution: "“14, New Moti Bagh, New Delhi, Delhi 110023, India – 09 Temple bells” by Piotrek Zyla, radio aporee ::: maps, via the Internet Archive, Public Domain Mark 1.0",
    durationSeconds: 176,
    caveat: null,
  },
  {
    id: "adda",
    bangla: "আড্ডা",
    roman: "Adda",
    description: "Krishnarajendra Market in Bengaluru: several hundred people talking at once, none of them to you. The nearest thing to pandal adda that exists under a licence we can use, and recorded in this city, which feels right for a Puja held in it.",
    sourceUrl: "https://archive.org/details/aporee_7598_9345",
    remoteUrl: "https://archive.org/download/aporee_7598_9345/FrancoisEmmanuelFodereBangaloreKrishnarajendramarket.mp3",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "“Bangalore, Krishnarajendra-market, City market” by François-Emmanuel Fodéré, radio aporee ::: maps, via the Internet Archive, CC BY-SA 3.0",
    durationSeconds: 136,
    caveat: null,
  },
  {
    id: "brishti",
    bangla: "বৃষ্টি",
    roman: "Brishti",
    description: "Summer rain and a storm, recorded in Kolkata. Not rain in general; rain there. Seven minutes of it in the original, trimmed here to three.",
    sourceUrl: "https://archive.org/details/aporee_55111_63012",
    remoteUrl: "https://archive.org/download/aporee_55111_63012/summerrainandstorm.mp3",
    licence: "Public Domain Mark 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    attribution: "“Chittaranjan Colony, Kolkata, West Bengal, India – Summer rain and storm” by Sukanta Majumdar, radio aporee ::: maps, via the Internet Archive, Public Domain Mark 1.0",
    durationSeconds: 443,
    caveat: null,
  },
  {
    id: "sandhya_arati",
    bangla: "সন্ধ্যারতি",
    roman: "Sandhya Arati",
    description: "Bells, chanting and a crowd together at a math in Hubli on Maha Shivaratri. A different festival and a different state, but the sound of an evening arati is the sound of an evening arati.",
    sourceUrl: "https://archive.org/details/aporee_9667_11575",
    remoteUrl: "https://archive.org/download/aporee_9667_11575/FrancoisEmmanuelFodereHubliSriGurunathrudhaSwamiMathBellsandCo.mp3",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "“Hubli, Sri Gurunathrudha Swami Math, Bells & Co” by François-Emmanuel Fodéré, radio aporee ::: maps, via the Internet Archive, CC BY-SA 3.0",
    durationSeconds: 241,
    caveat: null,
  },
  {
    id: "gangar_dhara",
    bangla: "গঙ্গার ধারা",
    roman: "Gangar Dhara",
    description: "Bathing in the Ganga at Varanasi. Water, steps, distant voices. The river this festival ends in, recorded a long way upstream of where it ends.",
    sourceUrl: "https://archive.org/details/aporee_5155_59723",
    remoteUrl: "https://archive.org/download/aporee_5155_59723/d57Gath6hamBAINSnowindscreen2.mp3",
    licence: "Public Domain Mark 1.0",
    licenceUrl: "http://creativecommons.org/publicdomain/mark/1.0/",
    attribution: "“varanasi: by the ghats – Bath in the Ganga river (Varanasi)” by antonixfelinski, radio aporee ::: maps, via the Internet Archive, Public Domain Mark 1.0",
    durationSeconds: 108,
    caveat: null,
  },
  {
    id: "jhijhi_poka",
    bangla: "ঝিঁঝিঁ পোকা",
    roman: "Jhijhi Poka",
    description: "Evening beside a pond in Bhului, West Bengal, in the monsoon. Crickets, frogs and insects, dense and close. The recordist's own filename says it better than we can, and this is the most regionally exact thing on the desk.",
    sourceUrl: "https://archive.org/details/aporee_64030_73837",
    remoteUrl: "https://archive.org/download/aporee_64030_73837/EVENINGPONDSIDEDENSECRCIKETCLOSEFROGCLOSEINSECTS.mp3",
    licence: "Public Domain Mark 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    attribution: "“Bhului, Jot-Sriram, West Bengal 722143, India – Bhului, Evening, Monsoon” by Prabuddha Mukhopadhyay, radio aporee ::: maps, via the Internet Archive, Public Domain Mark 1.0",
    durationSeconds: 425,
    caveat: null,
  },
  {
    id: "mantra_path",
    bangla: "মন্ত্রপাঠ",
    roman: "Mantra Path",
    description: "The Guru Stotram, chanted in Sanskrit. Released into the public domain by whoever recorded it, which is a generous thing to have done.",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sanskrit_Chanting_Guru_Stotram.ogg",
    remoteUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Sanskrit_Chanting_Guru_Stotram.ogg",
    licence: "CC0 1.0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "“Sanskrit Chanting Guru Stotram” chanted by Swami Atmananda, via Wikimedia Commons, CC0 1.0 (no attribution required, but credit is courteous)",
    durationSeconds: 295,
    caveat: null,
  },
  {
    id: "drone",
    bangla: "সুরের রেখা",
    roman: "Drone",
    description: "A sustained Indian drone, released under CC0. It is labelled drone rather than tanpura because the person who uploaded it wrote only \"loop like indian drone\", and nobody here has been able to confirm whether it is a played instrument or a synthesised one. Calling it a tanpura would be a guess with a confident face.",
    sourceUrl: "https://archive.org/details/23IndianDrone",
    remoteUrl: "https://archive.org/download/23IndianDrone/IndianDrone.ogg",
    licence: "CC0 1.0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "“23 indian drone” by abeattie23, via the Internet Archive, CC0 1.0 (no attribution required)",
    durationSeconds: 3681,
    caveat: "Labelled drone, not tanpura. Nobody has confirmed the instrument.",
  },
];

export const COLLECTIONS: Collection[] = [
  {
    id: "mahalaya",
    bangla: "মহালয়া",
    roman: "Mahalaya",
    blurb: "Four in the morning, the radio already on, and a voice that has been waking Bengal since before most of us were born. The whole Mahishasuramardini, and the songs inside it taken one at a time. Every track here is Saregama's own upload of the 1966 All India Radio master - embedded, never hosted.",
    tracks: [
      {
        titleBangla: "মহিষাসুরমর্দিনী (সম্পূর্ণ)",
        titleRoman: "Mahishasuramardini (full programme)",
        artist: "Birendra Krishna Bhadra, Pankaj Kumar Mullick, Bani Kumar and company",
        year: 1966,
        note: "The whole ninety minutes, exactly as Akashvani has played it at four in the morning for sixty years. Put this on and it is Mahalaya, wherever in the world you happen to be standing.",
        youtubeId: "YQyo8QeoYhc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "চণ্ডীপাঠ",
        titleRoman: "Chandipath",
        artist: "Birendra Krishna Bhadra",
        year: null,
        note: "Just the Sanskrit recitation, lifted clear of the songs. Thirty minutes of that famous unhurried voice reading the Chandi, for anyone who wants the scripture without the orchestra.",
        youtubeId: "AnrGifI3WHk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বাজলো তোমার আলোর বেণু",
        titleRoman: "Bajlo Tomar Alor Benu",
        artist: "Supriti Ghosh",
        year: null,
        note: "The song every Bengali can hum before they are fully awake. This upload keeps Bhadra's spoken introduction attached, so you get the handover from voice to flute intact.",
        youtubeId: "2Zqlb00ttCU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জাগো দুর্গা দশপ্রহরণধারিণী",
        titleRoman: "Jago Durga Dashapraharanadharini",
        artist: "Dwijen Mukhopadhyay",
        year: null,
        note: "Dwijen Mukhopadhyay calling the goddess awake, ten weapons and all. Two minutes, no fat on it, and the whole programme tilts upward from here.",
        youtubeId: "E_3DoeyToto",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "যা চণ্ডী মধুকৈটভাদি",
        titleRoman: "Ya Chandi Madhukaitabhadi",
        artist: "Chorus, composed by Pankaj Kumar Mullick",
        year: null,
        note: "Sanskrit chorus in Malkauns, dark and level. Mullick's arrangement makes a ritual stotra sound like a chorus of people walking toward something in the dark.",
        youtubeId: "8FytVk54-dw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "অখিল বিমানে তব জয়গানে",
        titleRoman: "Akhila Bimane Tabo Jaya Gane",
        artist: "Krishna Dasgupta",
        year: null,
        note: "Krishna Dasgupta's voice opening the whole sky out. One of the pieces people mean when they say the Mahalaya songs are better than anything on the radio the rest of the year.",
        youtubeId: "FrHp3pXxeNU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বিমানে বিমানে আলোকের গানে",
        titleRoman: "Bimane Bimane Aloker Gane",
        artist: "Sandhya Mukhopadhyay",
        year: null,
        note: "Sandhya Mukhopadhyay at her most weightless. Light travelling through light, which is more or less what the lyric says and exactly what her voice does with it.",
        youtubeId: "-ZJtci1_Ih0",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "ওগো আমার আগমনী আলো",
        titleRoman: "Ogo Amar Agomoni Alo",
        artist: "Shipra Bose",
        year: null,
        note: "The Agomoni light itself, addressed directly. Shipra Bose sings it as a greeting rather than a prayer, which is why it carries so easily into the rest of the Puja week.",
        youtubeId: "2RZZzJdzGPM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "শান্তি দিলে ভরি",
        titleRoman: "Shanti Dile Bhori",
        artist: "Utpala Sen",
        year: null,
        note: "Utpala Sen, quiet and steady, asking to be filled with peace. It sits in the programme like a held breath between two louder passages.",
        youtubeId: "VAV6OQMe-to",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "তব অচিন্ত্য রূপচরিতমহিমা",
        titleRoman: "Tabo Achintya Rupacharita-Mahima",
        artist: "Manabendra Mukhopadhyay",
        year: null,
        note: "Manabendra Mukhopadhyay's great set piece, all classical shading and long lines. Four minutes that justify the claim that this was radio made by serious musicians.",
        youtubeId: "6rwF1iQPVzc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জয় জয় জপ্য জয়ে",
        titleRoman: "Jaya Jaya Japya Jaye",
        artist: "Chorus, composed by Pankaj Kumar Mullick",
        year: null,
        note: "The victory chorus. If you only want one piece of the programme to signal that the battle has been won, this is the one people reach for.",
        youtubeId: "AB4IUcvuEXs",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "অহং রুদ্রেভির্বসুভিশ্চরামি",
        titleRoman: "Aham Rudrebhir Vasubhishcharami",
        artist: "Chorus",
        year: null,
        note: "The Devi Sukta, the goddess declaring herself in the first person. Four minutes of massed voices that make the Sanskrit sound less like scripture and more like an announcement.",
        youtubeId: "GJccKU4_5wg",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মা গো তব বীণে সঙ্গীতা",
        titleRoman: "Ma Go Tabo Bine Sangeeta",
        artist: "Sumitra Sen",
        year: null,
        note: "Sumitra Sen, the quietest voice in the whole programme. Easy to miss on a first listen and impossible to forget once you have noticed it.",
        youtubeId: "qdx842oMwnA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নারায়ণী নমোস্তুতে",
        titleRoman: "Narayani Namostute",
        artist: "Birendra Krishna Bhadra",
        year: null,
        note: "Bhadra reciting the Narayani Stuti from the Durga Vandana sessions. The same voice, the same stillness, in a piece short enough to loop on a page.",
        youtubeId: "lb2Fwp5y_U0",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মহিষাসুরমর্দিনী, দ্বিতীয় পর্ব",
        titleRoman: "Mahishasuramardini, Part II",
        artist: "Birendra Krishna Bhadra and company",
        year: 1966,
        note: "The second half on its own, for the listener who already knows the opening by heart and wants to start where the fighting does.",
        youtubeId: "KSait1b91Kw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মহালয়া — মহিষাসুরমর্দিনী",
        titleRoman: "Mahalaya (Mahishasuramardini)",
        artist: "Birendra Krishna Bhadra",
        year: null,
        note: "The broadcast itself. Bhadra's voice at four in the morning is the actual starting gun of Bengali autumn; nothing else on this list carries that much accumulated habit.",
        youtubeId: "A-nMCu2y_PM",
        channel: "Arnip's creativity",
      },
      {
        titleBangla: "অহং রুদ্রে",
        titleRoman: "Ahang Rudre",
        artist: "Sourendro & Soumyojit",
        year: null,
        note: "Sourendro-Soumyojit setting the Devi Sukta with a trained chorus. Sanskrit, stately, and built for the pre-dawn hour rather than the pandal — squarely Mahalaya material.",
        youtubeId: "zZ4dYYcPxUY",
        channel: "Sourendro Soumyojit",
      },
      {
        titleBangla: "বাজলো তোমার আলোর বেণু",
        titleRoman: "Bajlo Tomar Alor Benu",
        artist: "Debolina",
        year: null,
        note: "The song that opens Mahishasuramardini, covered by Debolina. Everyone knows the first line; hearing another voice sing it is genuinely disorienting, in a useful way.",
        youtubeId: "yzEbF55ywtM",
        channel: "Sm STUDIO FILM & MUSIC",
      },
      {
        titleBangla: "রূপং দেহি জয়ং দেহি",
        titleRoman: "Rupang Dehi Jayang Dehi",
        artist: "Pandit Tushar Dutta",
        year: null,
        note: "The Argala Stotram sung by a classical vocalist rather than a playback singer. Sanskrit, unhurried, and the closest thing here to the pre-dawn radio texture.",
        youtubeId: "tXXwsHeS_T0",
        channel: "Mukta Creation",
      },
      {
        titleBangla: "অয়ি গিরি নন্দিনী",
        titleRoman: "Aigiri Nandini",
        artist: "Iman Chakraborty",
        year: null,
        note: "The Mahishasura Mardini Stotram, sung by Iman Chakraborty with Nilanjan Ghosh's arrangement. Sanskrit devotional rather than pujo pop — it belongs to the dawn.",
        youtubeId: "Qgvav0w0EFU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "দুর্গে দুর্গে দুর্গতিনাশিনী",
        titleRoman: "Durge Durge Durgatinashini",
        artist: "Asha Bhosle",
        year: null,
        note: "Asha Bhosle singing the Durgatinashini invocation with Swapan Chakraborty. Devotional rather than festive, which puts it with the Mahalaya material rather than the pandal.",
        youtubeId: "45O8KBhSZ0I",
        channel: "Saregama Bengali",
      },
    ],
  },
  {
    id: "agomoni-bijoya",
    bangla: "আগমনী ও বিজয়া",
    roman: "Agomoni o Bijoya",
    blurb: "The oldest story Bengal tells itself: a daughter comes home for four days and then has to go back. Ramprasad, Kamalakanta, Dasarathi Ray and Nazrul, sung by Dhananjay Bhattacharya, Ramkumar Chattopadhyay and a handful of people still writing new ones. Agomoni is the arrival, Bijoya is the leaving, and Bengalis have never quite got over either.",
    tracks: [
      {
        titleBangla: "আমার গৌরীরে লয়ে",
        titleRoman: "Amar Gouri Re Loye",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Menaka pleading for her daughter, sung by the voice that defined Agomoni on 78rpm. The ache in it is a mother's, not a devotee's, and that is the whole point.",
        youtubeId: "Y7D9kh0YDUw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "শরৎ-কমল মুখে আধ আধ বাণী",
        titleRoman: "Sharat Kamal Mukhe Adho Adho Bani",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Autumn lotus, half-formed words, a small daughter remembered. Pure Agomoni imagery, and Dhananjay Bhattacharya sings it without a gram of sentimentality.",
        youtubeId: "i_z7Q84a-Ks",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নবমী নিশি পোহালো",
        titleRoman: "Nabami Nishi Pohalo",
        artist: "Kamala Jharia",
        year: null,
        note: "Nabami night has ended, and everyone in the house knows what tomorrow means. Kamala Jharia's shellac-era voice makes the dread of Dashami feel very close.",
        youtubeId: "fPNrD2TH5OQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এবারে উমা এলে আবার",
        titleRoman: "Ebare Uma Ele Abar",
        artist: "Abhayapada Chattopadhyay",
        year: null,
        note: "Uma has come again, and this time the mother bargains for longer. A plain, direct Agomoni from the old Aay Ma Uma record.",
        youtubeId: "plhPinMfUJQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "উমাকে বিদায় দিয়া",
        titleRoman: "Umake Biday Diya",
        artist: "K. Mullick",
        year: null,
        note: "The Bijoya counterpart: having sent Uma away, what does a house do with itself. Three minutes that explain why Dashami in Bengal feels like a small bereavement.",
        youtubeId: "Kdk-7ntIA3o",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এলো গিরিনন্দিনী",
        titleRoman: "Elo Girinandini",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "The mountain king's daughter has arrived. Bright, processional, the sound of a household throwing its doors open, and a good opener for any Agomoni set.",
        youtubeId: "6OghjYRe2to",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "কেমনে মা ভুলেছিলি",
        titleRoman: "Kemone Ma Bhulechhili",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "How could you forget us, mother. The reproach every Bengali parent has delivered to a child who moved away, sung straight at the goddess.",
        youtubeId: "69KKacIQyLY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "হে শিব শঙ্কর",
        titleRoman: "He Shiv Shankar",
        artist: "Dhananjay Bhattacharya",
        year: null,
        note: "Addressed to the famously unreliable son-in-law up on Kailash. Agomoni is a family drama, and this is the song where the in-laws get a word in.",
        youtubeId: "XKwHFP5puUA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এবার নবীন মন্ত্রে হবে",
        titleRoman: "Ebar Nabin Mantre Hobe",
        artist: "Anup Ghoshal",
        year: null,
        note: "A newer Puja song that asks for the worship to be renewed rather than repeated. Anup Ghoshal's clarity keeps it from tipping into piety.",
        youtubeId: "GtmxMUkSEJ8",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আজি শঙ্খে শঙ্খে মঙ্গল গাও",
        titleRoman: "Aji Shankhe Shankhe Mangala Gao",
        artist: "Anup Ghoshal",
        year: null,
        note: "Conch answering conch across a courtyard. The lyric is basically an instruction for how to make a morning auspicious, and it works as one.",
        youtubeId: "ZeVok4tMfSs",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এত গয়না বেটী কোথায় পেলি",
        titleRoman: "Eto Goyna Beti Kothay Peli",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "A mother inspecting her daughter's jewellery and asking, with narrowed eyes, where it all came from. Agomoni as tappa, gossipy and affectionate at once.",
        youtubeId: "joiwefTFzBI",
        channel: "Inreco Devotional",
      },
      {
        titleBangla: "যাও যাও গিরি আনিতে গৌরী",
        titleRoman: "Jao Jao Giri Anite Gouri",
        artist: "Swami Samapriyananda",
        year: null,
        note: "Ramprasad's famous command to the mountain king: go, fetch our daughter. Sung here in the Baghbazar math's own recording, unhurried and completely unshowy.",
        youtubeId: "gNursnkOVsQ",
        channel: "Udbodhan - Ramakrishna Math Baghbazar",
      },
      {
        titleBangla: "গিরি গণেশ আমার শুভকারী",
        titleRoman: "Giri Ganesh Amar Shubhokari",
        artist: "Agomoni recital at Belur Math",
        year: 2019,
        note: "The Agomoni sung live at Belur Math, with the room audible around it. A useful reminder that these songs belong to courtyards, not studios.",
        youtubeId: "iaFdu3yilUA",
        channel: "Ramakrishna Math & Ramakrishna Mission, Belur Math",
      },
      {
        titleBangla: "নবমী নিশিরে",
        titleRoman: "Nabami Nishire",
        artist: "Hemanta Mukhopadhyay",
        year: 1958,
        note: "Hemanta taking the Nabami-night lament into his own low register. Less folk, more midnight radio, and it lands somewhere very tender. Released 1958, composed by Robin Chatterjee.",
        youtubeId: "8cIMHSg8Aew",
        channel: "Saregama India Ltd (auto-generated YouTube Topic channel)",
      },
      {
        titleBangla: "আমার আনন্দিনী উমা",
        titleRoman: "Amar Anandini Uma",
        artist: "Payel Kar",
        year: null,
        note: "Nazrul's Agomoni, written by a Muslim poet about a Hindu mother's daughter, which is a very Bengali fact worth keeping on a Puja page.",
        youtubeId: "CUDl3xltHPM",
        channel: "Payel Kar (Topic)",
      },
      {
        titleBangla: "আগমনীর গান",
        titleRoman: "Agomonir Gaan",
        artist: "Anupam Roy",
        year: 2018,
        note: "Anupam Roy writing a new Agomoni for people who commute. It keeps the old shape, the coming and the leaving, and swaps the courtyard for a city.",
        youtubeId: "MsqpjM09MrY",
        channel: "SVF Music",
      },
      {
        titleBangla: "আগমনী আলো",
        titleRoman: "Agomoni Aalo",
        artist: "Jayati Chakraborty",
        year: 2019,
        note: "Jayati Chakraborty's contemporary Agomoni, sung with a folk singer's patience. Proof that the form is still being written and not just archived.",
        youtubeId: "bvij2HdGgv4",
        channel: "Jayati Chakraborty",
      },
      {
        titleBangla: "বিজয়ার গান",
        titleRoman: "Bijoyar Gaan",
        artist: "Ramkumar Chattopadhyay, Chandidas Mal, Sreeradha Bandyopadhyay, Sayantani Majumder",
        year: null,
        note: "A full half hour of Dashami songs in one place. Save it for the evening of the immersion, when nobody wants anything faster than this.",
        youtubeId: "psjbjwSwq7E",
        channel: "Perennial Records",
      },
      {
        titleBangla: "দুগ্গা মা",
        titleRoman: "Dugga Ma",
        artist: "Arijit Singh",
        year: 2017,
        note: "Arijit singing to the goddess directly, from Bolo Dugga Maiki. Modern production, but the address is old — a son talking to his mother, which is what agomoni always was.",
        youtubeId: "3Gg0GP8DxhU",
        channel: "SVF Music",
      },
      {
        titleBangla: "আইলো উমা বাড়িতে",
        titleRoman: "Ailo Uma Barite",
        artist: "Monami Ghosh",
        year: null,
        note: "Uma has arrived at the house. The entire agomoni tradition in one line, and Monami Ghosh sings it as family news rather than scripture — which is the correct reading.",
        youtubeId: "4zyCkmAS1Oo",
        channel: "MONAMI GHOSH",
      },
      {
        titleBangla: "এলো যে মা",
        titleRoman: "Elo Je Maa",
        artist: "Abhijeet Bhattacharya & Shreya Ghoshal",
        year: 2012,
        note: "Challenge 2's arrival song. Jeet Gannguli writes it big, Abhijeet and Shreya sing it bigger, and the goddess gets a full film-scale welcome.",
        youtubeId: "NAUA2LM9hZc",
        channel: "SVF Music",
      },
      {
        titleBangla: "জয় দুগ্গা ঠাকুর",
        titleRoman: "Joy Dugga Thakur",
        artist: "Shreya Ghoshal & Jolly Das",
        year: 2025,
        note: "Eskay's pujo 2025 single. Newest thing on the list by some distance, and useful proof that the agomoni song is still being written rather than only remembered.",
        youtubeId: "Xv9JcvNqmRM",
        channel: "Eskay Music",
      },
      {
        titleBangla: "উমা আসে নতুন সাজে",
        titleRoman: "Uma Ashe Notun Saje",
        artist: "Ankita Bhattacharyya",
        year: null,
        note: "Uma arriving in new clothes — the domestic detail that agomoni songs always reach for. Ankita Bhattacharyya sings it bright and unfussy, closer to folk than to hymn.",
        youtubeId: "hnkfDCbULxk",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "ও মেনকা ও মেনকা",
        titleRoman: "O Menoka O Menoka",
        artist: "Antara Nandy & Ankita Nandy",
        year: null,
        note: "Sung at Menoka, Uma's mother, rather than at the goddess — the oldest and most human angle in the agomoni repertoire. The Nandy sisters keep it conversational.",
        youtubeId: "xUMhpMmwAmM",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "দশভুজা",
        titleRoman: "Dashabhuja",
        artist: "Monali Thakur & Jeet Gannguli",
        year: null,
        note: "A brand-commissioned pujo song that turned out better than it needed to. Monali Thakur and Jeet Gannguli on the ten-armed goddess, with a chorus built for a loudspeaker.",
        youtubeId: "G9DnRI1J2wo",
        channel: "Sunrise Pure",
      },
      {
        titleBangla: "দুগ্গা এলো",
        titleRoman: "Dugga Elo",
        artist: "Monali Thakur",
        year: null,
        note: "Monali Thakur announcing the arrival, with Indranil Das's production keeping it airy rather than thunderous. A good opener for the agomoni stretch before the dhak comes in.",
        youtubeId: "xlElO06nQy8",
        channel: "Zee Music Bangla",
      },
      {
        titleBangla: "এল রে পুজো এল",
        titleRoman: "Elo Re Pujo Elo",
        artist: "Nakash Aziz & Senjuti",
        year: null,
        note: "The pujo has come — announced rather than argued. An SVF seasonal single that does its one job well and gets out before it wears thin.",
        youtubeId: "UElpQ1D3CkA",
        channel: "SVF Music",
      },
      {
        titleBangla: "ঢাক বাজা কাঁসর বাজা",
        titleRoman: "Dhak Baja Kashor Baja",
        artist: "Shreya Ghoshal",
        year: 2016,
        note: "Shreya Ghoshal and Jeet Gannguli's standalone pujo single. Dhak and kanshor named in the title, and the arrangement delivers both — the most literal track on the list.",
        youtubeId: "id5_3dKvEBg",
        channel: "T-Series",
      },
      {
        titleBangla: "জয় জয় দুর্গা মা",
        titleRoman: "Joy Joy Durga Maa",
        artist: "Sourav, Raj & Jeet Gannguli",
        year: null,
        note: "A steel company's pujo song with half of Tollywood in the video. Brand-funded, but Jeet Gannguli turned in a real tune, and the chorus works in a crowd.",
        youtubeId: "3E_qefwPA0E",
        channel: "Captain Steel India Limited",
      },
      {
        titleBangla: "আমার দুগ্গা এসেছে",
        titleRoman: "Amar Dugga Esheche",
        artist: "Akriti Kakar",
        year: null,
        note: "My Dugga has come — the possessive is what makes it work. Akriti Kakar sings it as household news, which is the correct register for an agomoni song.",
        youtubeId: "ZkywC2p1E6Q",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এবার পুজোয় চাই",
        titleRoman: "Aebar Pujoye Chaaye",
        artist: "Alka Yagnik",
        year: null,
        note: "Alka Yagnik on a Bengali pujo song — a reminder that the seasonal single used to draw Bombay's biggest voices. Audio-only upload with no video to carry it.",
        youtubeId: "7CwcrZw8Kns",
        channel: "Alka Yagnik - Topic",
      },
      {
        titleBangla: "মা গো তুই",
        titleRoman: "Maa Go Tui",
        artist: "Manomay Bhattacharya & Somchanda",
        year: 2019,
        note: "Durgeshgorer Guptodhon's song to the mother, scored by Bickram Ghosh. A film song that behaves like a devotional one, and the percussion is better than most.",
        youtubeId: "60tSbJWJCr0",
        channel: "SVF Music",
      },
      {
        titleBangla: "বলো দুগ্গা এলো",
        titleRoman: "Bolo Dugga Elo",
        artist: "Sunidhi Chauhan",
        year: null,
        note: "Sunidhi Chauhan brought in for a Bengali pujo single and singing it properly. Indranil Das's arrangement is big, but the announcement at the centre stays clear.",
        youtubeId: "avHnTk8lzzg",
        channel: "SVF Music",
      },
      {
        titleBangla: "দুগ্গা মা আসছে",
        titleRoman: "Dugga Ma Asche",
        artist: "Infra",
        year: null,
        note: "A small brand-commissioned lyric video about the goddess on her way. Modest production, but the sentiment is unforced and it sits fine beside the bigger arrivals.",
        youtubeId: "FpM4yZfktnM",
        channel: "Infra",
      },
      {
        titleBangla: "ও ঠাকুর",
        titleRoman: "O Thakur",
        artist: "Upal Sengupta & Prashmita Paul",
        year: 2015,
        note: "Belaseshe's address to the deity, sung by Upal Sengupta. A film about an old marriage borrowing devotional language for something much more domestic.",
        youtubeId: "7GYJcXSLwYo",
        channel: "Times Music Bangla",
      },
    ],
  },
  {
    id: "city",
    bangla: "শহরের পুজো",
    roman: "Sohorer Pujo",
    blurb: "Kolkata in the Puja week: the pandal-hopping, the new clothes, the coffee house, the rock band at a volume nobody licensed. This is the HMV Pujor gaan tradition and everything it turned into - Hemanta, Manna Dey, Sandhya, Kishore, Cactus, Fossils, Bhoomi, Anjan Dutt, Anupam Roy, Lakkhichhara.",
    tracks: [
      {
        titleBangla: "কফি হাউসের সেই আড্ডাটা",
        titleRoman: "Coffee Houser Sei Addata Aaj Aar Nei",
        artist: "Manna Dey",
        year: 1983,
        note: "The national anthem of Bengali adda and of everyone who has ever left a city and come back to find the table empty. Seven minutes, and nobody talks over it.",
        youtubeId: "kvadzdVaTtg",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "যদি কাগজে লেখো নাম",
        titleRoman: "Jodi Kagoje Lekho Naam",
        artist: "Manna Dey",
        year: null,
        note: "Manna Dey doing the thing only he could do, classical training worn lightly over a pop song. A staple of the Puja-release era and still a request every year.",
        youtubeId: "jIaIXjBqyjE",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এই মেঘলা দিনে একলা",
        titleRoman: "Ei Meghla Dine Ekla",
        artist: "Hemanta Mukhopadhyay",
        year: null,
        note: "The overcast-afternoon song. Bengal's Puja weather is exactly this, bright then suddenly grey, and Hemanta's voice is the sound of waiting it out.",
        youtubeId: "aFEPYpcmkEM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমায় প্রশ্ন করে নীল ধ্রুবতারা",
        titleRoman: "Amay Prashna Kare Neel Dhrubatara",
        artist: "Hemanta Mukhopadhyay",
        year: null,
        note: "A Puja release that outlived its season by sixty years. The blue pole star asks a question and Hemanta declines, beautifully, to answer it.",
        youtubeId: "Quw_xNFSfik",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "এই পথ যদি না শেষ হয়",
        titleRoman: "Ei Poth Jodi Na Shesh Hoy",
        artist: "Hemanta Mukhopadhyay and Sandhya Mukhopadhyay",
        year: 1961,
        note: "From Saptapadi, and the duet every Bengali couple has hummed on a scooter. If the road never ended. On Puja nights in Kolkata, briefly, it doesn't.",
        youtubeId: "MV7NxsPLkmA",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মধুমালতী ডাকে আয়",
        titleRoman: "Madhumalati Dake Aay",
        artist: "Sandhya Mukhopadhyay",
        year: null,
        note: "Sandhya Mukhopadhyay at full brightness, a flower calling a child out to play. Put it on in the morning and the whole page feels like a holiday.",
        youtubeId: "yUAG20NEhZI",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "সেদিনের সোনাঝরা সন্ধ্যা",
        titleRoman: "Sediner Sonajhara Sandhya",
        artist: "Shyamal Mitra",
        year: null,
        note: "That one gold-drenched evening, remembered later. Shyamal Mitra's speciality was nostalgia arriving on schedule, which is what Puja does to people anyway.",
        youtubeId: "xw4_01zGsAk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "সেই রাতে রাত ছিল পূর্ণিমা",
        titleRoman: "Sei Rate Raat Chhilo Purnima",
        artist: "Kishore Kumar",
        year: null,
        note: "Kishore Kumar's Bengali voice, which is a different instrument from his Hindi one, warmer and less hurried. A permanent fixture of the Pujor gaan lists.",
        youtubeId: "07BadGcIEe4",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "নয়ন সরসী কেন ভরেছে জলে",
        titleRoman: "Nayan Sarasi Keno Bhoreche Jale",
        artist: "Kishore Kumar",
        year: null,
        note: "Why are your eyes full of water. Kishore asks it gently and then spends three minutes not pressing for an answer. Peak Bengali modern song.",
        youtubeId: "EQBo0OVSGXQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "টাপুর টুপুর সারা দুপুর",
        titleRoman: "Tapur Tupur Sara Dupur",
        artist: "Arati Mukhopadhyay",
        year: null,
        note: "Rain on a tin roof all afternoon, rendered as a tune. Arati Mukhopadhyay sings it like someone genuinely delighted to have nowhere to be.",
        youtubeId: "J_NRMfOVRXY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমার নয়ন-ভুলানো এলে",
        titleRoman: "Amar Nayan-Bhulano Ele",
        artist: "Suchitra Mitra",
        year: null,
        note: "Tagore's Sharat song, and arguably the finest thing ever written about the Bengali autumn. Suchitra Mitra sings it with no decoration at all.",
        youtubeId: "S80EQpRWrzc",
        channel: "Suchitra Mitra (Topic)",
      },
      {
        titleBangla: "হলুদ পাখি",
        titleRoman: "Halud Pakhi",
        artist: "Cactus",
        year: null,
        note: "The Bengali rock song that a whole generation learned on a borrowed guitar. Six minutes, and by the last chorus the pandal crowd is singing it back.",
        youtubeId: "fpMH2DW_lmM",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "একলা ঘর",
        titleRoman: "Ekla Ghor",
        artist: "Fossils (Rupam Islam)",
        year: null,
        note: "Fossils at their loudest and loneliest. Every Kolkata Puja has one pandal playing this at a volume the licence probably does not permit.",
        youtubeId: "8Abt_zhpjak",
        channel: "Fossils (Topic)",
      },
      {
        titleBangla: "বারান্দায় রোদ্দুর",
        titleRoman: "Barandaye Roddur",
        artist: "Bhoomi",
        year: null,
        note: "Sunlight on a balcony, which is the single most Bengali image available. Bhoomi took folk instruments into pop and the Puja circuit never recovered.",
        youtubeId: "E70oxtms_qg",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "২৪৪১১৩৯ (বেলা বোস)",
        titleRoman: "2441139 (Bela Bose)",
        artist: "Anjan Dutt",
        year: null,
        note: "A landline number, a boy with no job, and the nerve to call anyway. Anjan Dutt wrote Kolkata's most quotable song and it still gets shouted back at him.",
        youtubeId: "0iUmptTmJ2k",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমাকে আমার মতো থাকতে দাও",
        titleRoman: "Amake Amar Moto Thakte Dao",
        artist: "Anupam Roy",
        year: 2010,
        note: "The song that reset Bengali songwriting for everyone under forty. Let me be as I am, sung by a man who clearly means it.",
        youtubeId: "ilgT99XFUq8",
        channel: "Anupam Roy (Topic)",
      },
      {
        titleBangla: "পুজো পুজো গন্ধ",
        titleRoman: "Pujo Pujo Gondho",
        artist: "Anupam Roy",
        year: 2024,
        note: "A modern Pujo-release single about the smell of Pujo arriving before Pujo does. Shiuli, new clothes, damp air; it names the thing exactly.",
        youtubeId: "V5rSZgw0xfk",
        channel: "SVF",
      },
      {
        titleBangla: "পদবি",
        titleRoman: "Padabi",
        artist: "Lakkhichhara",
        year: 2026,
        note: "Lakkhichhara back after a decade, still arguing with the city. Included because a Kolkata Puja page that skips the rock bands is telling only half the story.",
        youtubeId: "eri590rFW2I",
        channel: "Lakkhichhara Music",
      },
      {
        titleBangla: "পৃথিবী হারিয়ে গেল",
        titleRoman: "Prithibi Hariye Gelo",
        artist: "Mohammed Aziz",
        year: 1987,
        note: "From Guru Dakshina, the Bengali film that made this the sound of 1987 Kolkata. Mohammed Aziz singing Bengali with full-throated conviction; every para pandal played it that year.",
        youtubeId: "feK5VIyzsfM",
        channel: "Angel Bengali Songs",
      },
      {
        titleBangla: "পৃথিবী বদলে গেছে",
        titleRoman: "Prithibi Bodle Gechhe",
        artist: "Kishore Kumar",
        year: 1977,
        note: "Ananda Ashram, Uttam and Sharmila, and Kishore singing that the world has changed. A film song that turned into a general-purpose Bengali lament for time passing.",
        youtubeId: "9TUlI7KFi3s",
        channel: "ECHO BENGALI MUZIK",
      },
      {
        titleBangla: "চিরদিনই তুমি যে আমার",
        titleRoman: "Chirodini Tumi Je Aamar",
        artist: "Kishore Kumar",
        year: 1987,
        note: "Bappi Lahiri's tune, Kishore's last great Bengali film romance, from Amar Sanghi. The title alone has been borrowed by a later film and a thousand wedding slideshows.",
        youtubeId: "AJTkBqJXAv4",
        channel: "Ishtar Regional",
      },
      {
        titleBangla: "কথা হয়েছিল",
        titleRoman: "Katha Hoyechilo",
        artist: "Asha Bhosle",
        year: 1982,
        note: "Troyee, Bappi Lahiri, and Asha turning a small remembered conversation into a full ache. The definitive version, against which every cover on this list is measured.",
        youtubeId: "EEe4tVkaDWY",
        channel: "Angel Bengali Songs",
      },
      {
        titleBangla: "আর কত রাত একা থাকবো",
        titleRoman: "Aar Koto Raat Eka Thakbo",
        artist: "Asha Bhosle",
        year: 1989,
        note: "From Chokher Aloy, Bappi Lahiri's score. Asha asks how many more nights she must spend alone and makes it sound like a real question, not a film cue.",
        youtubeId: "64vvyOokAn4",
        channel: "Angel Bengali Songs",
      },
      {
        titleBangla: "ঢাকের তালে",
        titleRoman: "Dhaker Taley",
        artist: "Abhijeet Bhattacharya, Parinita & Sudipto",
        year: 2009,
        note: "Poran Jai Jolia Re's pujo number, and the reason 'dhaker taley komor dole' is a complete sentence in Bengali. Pure pandal-hopping energy, no devotion required.",
        youtubeId: "Xy5S9j4lTaE",
        channel: "SVF Music",
      },
      {
        titleBangla: "এবার যেন অন্য রকম পুজো",
        titleRoman: "Ebar Jeno Onno Rokom Pujo",
        artist: "Dev & Mimi (Yoddha)",
        year: 2014,
        note: "A film song wishing for a different kind of pujo this year — which is, reliably, what everyone says every year. Yoddha's contribution to the seasonal canon.",
        youtubeId: "E2zfQEo7Q_M",
        channel: "SVF",
      },
      {
        titleBangla: "চোখ তুলে দেখো না",
        titleRoman: "Chokh Tule Dekho Na",
        artist: "Babul Supriyo",
        year: 2000,
        note: "Sasurbari Zindabad, Prosenjit at his peak, Babul Supriyo asking someone to just look up. Turn-of-the-millennium Tollywood romance, unembarrassed about every bit of it.",
        youtubeId: "resVyxe_i2Y",
        channel: "SVF",
      },
      {
        titleBangla: "কিশোরী",
        titleRoman: "Kishori",
        artist: "Antara Mitra",
        year: 2024,
        note: "From Khadaan, the Dev film that swallowed Bengali cinema in December 2024. Rathijit's tune, Antara Mitra's voice — the newest entry in the Tollywood dance-song lineage.",
        youtubeId: "hjBMTHOj00M",
        channel: "Surinder Films",
      },
      {
        titleBangla: "সুন্দরী কমলা",
        titleRoman: "Shundori Komola",
        artist: "Armaan Malik & Antara Mitra",
        year: 2018,
        note: "Villain's take on the old folk song, rebuilt by Subho as a film dance number. The tune is centuries older than the production, which is most of the fun.",
        youtubeId: "E_6K3no0PD0",
        channel: "SVF Music",
      },
      {
        titleBangla: "মালা রে",
        titleRoman: "Mala Re",
        artist: "Jeet Gannguli",
        year: 2011,
        note: "Romeo, Dev and Subhashree, and Jeet Gannguli in his most efficient hook-writing years. Nobody claims it is deep; everybody remembers the chorus.",
        youtubeId: "MCTeyUeHDyM",
        channel: "SVF Music",
      },
      {
        titleBangla: "খোকাবাবু",
        titleRoman: "Khokababu (Dance Mix)",
        artist: "Samidh Mukerjee",
        year: 2010,
        note: "Shedin Dekha Hoyechilo's dance mix. This is the song that gave Dev the nickname, which makes it a small piece of Tollywood history as well as a pandal staple.",
        youtubeId: "ejWZSlO9Bhs",
        channel: "SVF Music",
      },
      {
        titleBangla: "লে পাগলু ড্যান্স",
        titleRoman: "Le Paglu Dance",
        artist: "Priyo Chattopadhyay",
        year: 2011,
        note: "Paglu. The single most inescapable Bengali dance song of the 2010s, and still the fastest way to get a reluctant crowd moving. Use it, don't apologise for it.",
        youtubeId: "Se6HAC3bonE",
        channel: "Surinder Films",
      },
      {
        titleBangla: "দুষ্টু কোকিল",
        titleRoman: "Dushtu Kokil",
        artist: "Kona & Akassh",
        year: 2024,
        note: "Toofan's naughty-cuckoo number, Shakib Khan and Mimi, and the biggest Bangladeshi film song of 2024.",
        youtubeId: "WRHz0g-GMVA",
        channel: "SVF",
      },
      {
        titleBangla: "রিমিক্স কাওয়ালি",
        titleRoman: "Remix Qawwali",
        artist: "Nakash Aziz & Neha Kakkar",
        year: 2014,
        note: "Bindaas, Savvy's production, a qawwali dragged onto a dance floor. Not subtle, but it does the specific job of lifting the room at the ninety-minute mark.",
        youtubeId: "Srg6AfoApVs",
        channel: "SVF Music",
      },
      {
        titleBangla: "তুই আমার হিরো",
        titleRoman: "Tui Amar Hero",
        artist: "Mika Singh & Akriti Kakar",
        year: 2013,
        note: "Rangbaaz, Jeet Gannguli, and Mika Singh bringing full Bollywood swagger to Bengali. Audio-only upload, so no video to lean on — it lives or dies on the hook.",
        youtubeId: "oW2JpFGaGpE",
        channel: "Mika Singh - Topic",
      },
      {
        titleBangla: "লাটাই",
        titleRoman: "Latai",
        artist: "Vinod Rathod & Akriti Kakkar",
        year: 2014,
        note: "Bachchan's kite-string song, Jeet Gannguli writing for Jeet the actor. Solid mid-period Tollywood — the sort of track that fills the gap between two better-known ones.",
        youtubeId: "xcIR08WEdrE",
        channel: "T-Series Bangla",
      },
      {
        titleBangla: "ভজ গৌরাঙ্গ",
        titleRoman: "Bhojo Gourango",
        artist: "Jeet Gannguli",
        year: 2009,
        note: "A kirtan refrain repurposed as a Challenge dance number. The devotional root is real, but the arrangement is pure 2009 Tollywood, so it sits in the city room.",
        youtubeId: "Kqt8KpxpdJc",
        channel: "SVF Music",
      },
      {
        titleBangla: "প্যার কা ঝটকা",
        titleRoman: "Pyar Ka Jhatka",
        artist: "Mika Singh & Mamta Sharma",
        year: 2012,
        note: "Khokababu's Hindi-inflected dance number. Nakash and Nandini's arrangement is loud and unembarrassed; it exists to be played at a volume that annoys neighbours.",
        youtubeId: "Enx64_5ZcRY",
        channel: "Eskay Movies",
      },
      {
        titleBangla: "ও মধু",
        titleRoman: "O Madhu",
        artist: "Benny Dayal & Monali Thakur",
        year: 2013,
        note: "Rangbaaz, Jeet Gannguli, Benny Dayal and Monali Thakur. One of the better-produced Tollywood dance songs of its year, and it has aged better than most of its neighbours.",
        youtubeId: "FGPgoSC_IAg",
        channel: "Surinder Films",
      },
      {
        titleBangla: "যতোই করো বাহানা",
        titleRoman: "Jotoi Koro Bahana",
        artist: "Kumar Sanu",
        year: 1996,
        note: "Biyer Phool, Prosenjit, and Kumar Sanu doing the thing he did better than anyone in Bengali — a mid-tempo film romance that sounds like it was recorded in one take.",
        youtubeId: "Shh-Axv5uts",
        channel: "Channel B Music",
      },
      {
        titleBangla: "প্যারেলাল",
        titleRoman: "Pyarelal",
        artist: "Samidh Mukerjee",
        year: 2010,
        note: "Dui Prithibi, Dev and Jeet in the same frame, and a song named after nobody in particular. Enjoyably nonsensical mid-period Tollywood.",
        youtubeId: "Dxa_ChwzzQw",
        channel: "SVF Music",
      },
      {
        titleBangla: "লাগে উরা ধুরা",
        titleRoman: "Laage Ura Dhura",
        artist: "Pritom Hasan & Raihan",
        year: 2024,
        note: "Toofan's monster hit — Shakib Khan, Pritom Hasan, and a hook that crossed the border within a week.",
        youtubeId: "jpSiIbswTLM",
        channel: "SVF",
      },
      {
        titleBangla: "ওঠো ওঠো সূর্যাই রে",
        titleRoman: "Otho Otho Surjai Re Jhiki Miki Diya",
        artist: "Lata Mangeshkar",
        year: 1981,
        note: "Anusandhan, R.D. Burman, and Lata singing a sunrise into existence. A film song that behaves like a folk song, which is exactly what Pancham was aiming at.",
        youtubeId: "q0XM-31W4_U",
        channel: "INRECO BENGALI",
      },
      {
        titleBangla: "এমন মধুর সন্ধ্যায়",
        titleRoman: "Emon Madhur Sandhyay",
        artist: "Asha Bhosle",
        year: 1987,
        note: "Ekanta Apan, and Asha finding the exact weight for a sweet evening. The original against which the Mita Chatterjee cover later on this list should be heard.",
        youtubeId: "uBNSBgO-Imw",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "প্যার কা বুখার",
        titleRoman: "Pyaar Ka Bukhar",
        artist: "Suraj Jagan",
        year: 2012,
        note: "Challenge 2, Savvy's arrangement, and fever treated as a romantic condition. Loud, fast, and completely uninterested in being taken seriously — which is exactly why it still fills a dance floor.",
        youtubeId: "g1QIbIcXP2s",
        channel: "SVF Music",
      },
      {
        titleBangla: "তোমারই চলার পথে",
        titleRoman: "Tomari Chalar Pathe",
        artist: "Asha Bhosle",
        year: 1987,
        note: "The other Ekanta Apan song on this list. Asha walking alongside someone rather than pining for them — a rarer mood in Bengali film music than you'd expect.",
        youtubeId: "UrXTysrtBK8",
        channel: "Angel Bengali Songs",
      },
      {
        titleBangla: "সুন্দরী কমলা",
        titleRoman: "Sundori Kamala",
        artist: "Jeet Gannguli",
        year: 2014,
        note: "Bachchan's version of the folk song, four years before Villain's. Two readings of the same old tune on one playlist is interesting; make sure they are spaced far apart.",
        youtubeId: "xu0e02wkKv8",
        channel: "T-Series Regional",
      },
      {
        titleBangla: "বাউন্ডুলে ঘুড়ি",
        titleRoman: "Baundule Ghuri (Reprise)",
        artist: "Anupam Roy",
        year: 2023,
        note: "Anupam Roy singing his own Dawshom Awbotaar song back, stripped down. The reprise is the better recording — fewer instruments, more of the writing showing through.",
        youtubeId: "1reZByeUhPY",
        channel: "SVF Music",
      },
      {
        titleBangla: "আইটেম বোম",
        titleRoman: "Item Bomb",
        artist: "Madhubanti Bagchi",
        year: 2016,
        note: "Kelor Kirti's item number, arranged by Indraadip Dasgupta. Knowingly over the top, which is the register the whole film was operating in.",
        youtubeId: "rhL2iNl7EFg",
        channel: "SVF",
      },
      {
        titleBangla: "কঠিন",
        titleRoman: "Kothin",
        artist: "Bojhena Shey Bojhena",
        year: 2012,
        note: "From the film that defined a certain kind of Bengali campus romance. The song is about difficulty and sounds entirely comfortable, which is very 2012 Tollywood.",
        youtubeId: "fhJViO9WyLw",
        channel: "SVF Music",
      },
      {
        titleBangla: "একশো বৃন্দাবন",
        titleRoman: "Eksho Vrindavan",
        artist: "Payel Dev",
        year: 2016,
        note: "Haripada Bandwala, Ankush and Nusrat. Payel Dev's tune is brighter than the film deserved and the hook outlasted the plot by several years.",
        youtubeId: "kmaRdH-BbHA",
        channel: "SVF",
      },
      {
        titleBangla: "তুমি আশে পাশে",
        titleRoman: "Tumi Aashe Paashe",
        artist: "Parbona Ami Chartey Tokey",
        year: 2015,
        note: "A quieter Tollywood love song than most on this list — useful precisely because it lowers the temperature between two dance numbers.",
        youtubeId: "bnFiJ_e_dEg",
        channel: "SVF Music",
      },
      {
        titleBangla: "ওরে মন উদাসী",
        titleRoman: "Ore Mon Udashi",
        artist: "Arijit Singh",
        year: 2014,
        note: "Arijit in Bengali, Bangali Babu English Mem, Ravi Kinagi's film. He sings it as if he is embarrassed by the arrangement, which somehow improves it.",
        youtubeId: "OGj3b6Gw1tI",
        channel: "SVF",
      },
      {
        titleBangla: "চারপাশে আলো হোক",
        titleRoman: "Chaarpashe Aalo Hok",
        artist: "SVF Music",
        year: 2023,
        note: "SVF's 2023 pujo song of unity — a corporate brief, handled with more care than usual. Light rather than devotion is the subject, so it belongs with the city material.",
        youtubeId: "mDEzESGA0h8",
        channel: "SVF Music",
      },
      {
        titleBangla: "লাভ মি",
        titleRoman: "Love Me",
        artist: "Dev Sen",
        year: 2016,
        note: "Kelor Kirti again, Raja Chanda directing. Lightweight by design; it works as connective tissue rather than as a destination track.",
        youtubeId: "ltGCEgzCg1o",
        channel: "SVF Music",
      },
      {
        titleBangla: "ঝিরি ঝিরি",
        titleRoman: "Jhiri Jhiri",
        artist: "Rahul & Priyanka",
        year: 2008,
        note: "Chirodini Tumi Je Amar — the film that borrowed Kishore's title. June Banerjee and Jeet Gannguli's song, and one of the earliest tracks here from the modern Tollywood era.",
        youtubeId: "MpMpKZ4Mb6Q",
        channel: "SVF",
      },
      {
        titleBangla: "দেখেছি তোমাকে শ্রাবণে",
        titleRoman: "Dekhechi Tomake Srabone",
        artist: "Shaan & June Banerjee",
        year: 2009,
        note: "Challenge's monsoon song, Shaan and June Banerjee. Jeet Gannguli writing a genuine melody rather than a hook, which he did less often than he should have.",
        youtubeId: "KCBtz-I738A",
        channel: "SVF Music",
      },
      {
        titleBangla: "হারিয়ে যাওয়ার গান",
        titleRoman: "Hariye Jawar Gaan",
        artist: "Anupam Roy",
        year: 2018,
        note: "Srijit's Uma, Anupam Roy writing about disappearing. One of the few songs here that would survive being taken out of its film entirely.",
        youtubeId: "9s7_dnARi6o",
        channel: "SVF",
      },
      {
        titleBangla: "শুধু তোমারই জন্য",
        titleRoman: "Shudhu Tomari Jonyo",
        artist: "Arijit Singh & Shreya Ghoshal",
        year: 2015,
        note: "Arijit and Shreya together in Bengali, Indraadip Dasgupta arranging. The two biggest playback voices of the era singing in their own language, which happened less than you'd think.",
        youtubeId: "_DKjY1eTFws",
        channel: "SVF Music",
      },
      {
        titleBangla: "আজ আমায়",
        titleRoman: "Aaj Amaye",
        artist: "Jeet Gannguli",
        year: 2016,
        note: "Power, Jeet and Nusrat. Late-period Jeet Gannguli — the formula is visible but the craft is still there, and the chorus does land.",
        youtubeId: "S3DkFKWJU00",
        channel: "SVF Music",
      },
      {
        titleBangla: "ফুল কলি",
        titleRoman: "Phool Koli",
        artist: "Dev Sen",
        year: 2012,
        note: "Awara, Ravi Kinagi, Sayantika Banerjee. A flower-bud song played as a dance number, which is the standard Tollywood move of that decade.",
        youtubeId: "zIkN5G3psNI",
        channel: "SVF",
      },
      {
        titleBangla: "ওহ মাই লাভ",
        titleRoman: "Oh My Love",
        artist: "Kunal Ganjawala & Shreya Ghoshal",
        year: 2010,
        note: "Amanush, Soham and Srabanti, Jeet Gannguli. Kunal Ganjawala and Shreya make an English title sound entirely Bengali, which was a specific skill of that period.",
        youtubeId: "Sa6K696xLrA",
        channel: "SVF Music",
      },
      {
        titleBangla: "কেন আজকাল",
        titleRoman: "Keno Aajkal",
        artist: "Nachiketa Chakraborty",
        year: 2010,
        note: "Josh, and one of the few times Nachiketa's voice turned up in a mainstream Tollywood film. The contrast between his grain and Jeet Gannguli's polish is the point.",
        youtubeId: "5zhWszIWKWU",
        channel: "SVF",
      },
      {
        titleBangla: "বেঁচে থাকার গান",
        titleRoman: "Benche Thakar Gaan",
        artist: "Rupam Islam",
        year: 2010,
        note: "Autograph, Srijit's debut, Rupam Islam singing about staying alive. Bangla rock arriving in mainstream cinema, and it still sounds like a statement.",
        youtubeId: "ep52mT-w_TI",
        channel: "SVF Music",
      },
      {
        titleBangla: "তারে ভোলানো গেল না কিছুতে",
        titleRoman: "Tare Bholano Gelo Na Kichute",
        artist: "Asha Bhosle",
        year: 1978,
        note: "Lal Kuthi, and Asha singing about someone who cannot be consoled. Late-seventies Bengali film scoring at its most elegant — strings used sparingly, voice left exposed.",
        youtubeId: "Sedwlz3Yfgg",
        channel: "INRECO BENGALI",
      },
      {
        titleBangla: "একটা দেশলাই কাঠি জ্বালাও",
        titleRoman: "Ekta Deshlai Kathi Jwalao",
        artist: "Asha Bhosle",
        year: null,
        note: "Light one matchstick. A Puja Hits release with a genuinely strange central image, and Asha treats it as completely reasonable, which is why it works.",
        youtubeId: "g4Z7lV1Posg",
        channel: "Saregama Bengali",
      },
    ],
  },
  {
    id: "village",
    bangla: "গ্রামের পুজো",
    roman: "Gramer Pujo",
    blurb: "The same four days on the bank of a river. Baul and bhatiali and dhamail and jhumur, Lalon's questions, Abbasuddin's boatmen, Dohar's Agomoni sung with hand percussion in a courtyard. This is the register the Agomoni songs were written in before the recording studios found them.",
    tracks: [
      {
        titleBangla: "গৌরী এলো",
        titleRoman: "Gouri Elo",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "Gouri has come, go and look at her. Dohar sing Agomoni the way a village actually sings it, with hand percussion and no ceremony whatsoever.",
        youtubeId: "VLUppccFWrA",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "ঢাকের বোলে বাংলা দোলে",
        titleRoman: "Dhaker Bole Bangla Dole",
        artist: "Dohar",
        year: null,
        note: "Bengal swaying to the dhak's syllables. This is the song to reach for when the ambience mixer is already running the drum layer and you want the two to meet.",
        youtubeId: "SDCcfKvIcyQ",
        channel: "Dohar (Topic)",
      },
      {
        titleBangla: "একবার নাচো মা",
        titleRoman: "Ekbar Nacho Maa",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "Shyama sangeet with a dancing pulse instead of a mournful one. Forty million people have played this; it turns out the village register travels.",
        youtubeId: "EZbQ-uaDbw4",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "হৃদমাঝারে রাখব",
        titleRoman: "Hrid Majhare Rakhbo",
        artist: "Dohar, led by Kalikaprasad Bhattacharya",
        year: null,
        note: "I will keep you in the middle of my heart and never let you go. A Baul line that works as devotion, as love song and as farewell, which is why it never leaves.",
        youtubeId: "DXx9gMpj9k0",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "বন্ধু বিনে প্রাণ বাঁচে না",
        titleRoman: "Bandhu Bine Pran Bache Na",
        artist: "Dohar, Radharaman Dutta (dhamail)",
        year: null,
        note: "A dhamail from Sylhet, the circle song women sing at weddings. It belongs on a Puja page because Puja in a village is mostly women singing in a circle.",
        youtubeId: "TYAG2HmhlZ4",
        channel: "DOHAR FOLK",
      },
      {
        titleBangla: "শুভ্র শারদ রাঙা",
        titleRoman: "Shubhra Sharad Ranga",
        artist: "Dohar",
        year: 2024,
        note: "Dohar's own Durga Puja single, written for the season rather than borrowed into it. White autumn light, folk instruments, and a tune that walks rather than marches.",
        youtubeId: "2tUkXTPKcvA",
        channel: "Hindusthan Record",
      },
      {
        titleBangla: "হৃদমাঝারে রাখব",
        titleRoman: "Hrid Majhare Rakhbo",
        artist: "Purna Das Baul",
        year: null,
        note: "The same song from the Baul Samrat himself, ektara and all. Set it next to the Dohar version and you can hear a tradition being handed across a generation.",
        youtubeId: "MF8pLSGzdWE",
        channel: "Baul Samrat Purna Das",
      },
      {
        titleBangla: "গোলেমালে গোলেমালে পিরিত কইরো না",
        titleRoman: "Golemale Golemale Pirit Koiro Na",
        artist: "Purna Das Baul",
        year: null,
        note: "Do not fall in love in a hurry, warns the Baul, plainly enjoying himself. Folk wisdom delivered as a joke, which is the Baul house style.",
        youtubeId: "uZSlIdIlW_U",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "দেখেছি রূপসাগরে মনের মানুষ",
        titleRoman: "Dekhechhi Rup-Sagare Moner Manush",
        artist: "Purna Das Baul",
        year: null,
        note: "Lalan's moner manush, the person of the heart, glimpsed in an ocean of form. The central idea of Baul thought, sung by its most travelled voice.",
        youtubeId: "8Edxs3WVMyQ",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আসছে জামাই দিগম্বর",
        titleRoman: "Ashchhe Jamai Digombor",
        artist: "Parvathy Baul",
        year: 2024,
        note: "The naked son-in-law is on his way. Shiva turning up to collect his wife, treated with exactly the mixture of alarm and affection a Bengali family would use.",
        youtubeId: "Fuhyx9iCUJI",
        channel: "SVF Music",
      },
      {
        titleBangla: "কিছুদিন মনে মনে",
        titleRoman: "Kichhu Din Mone Mone",
        artist: "Parvathy Baul",
        year: null,
        note: "Parvathy Baul alone with an ektara and a duggi, singing about keeping something inside for a while. Five minutes that make a webpage feel like a riverbank.",
        youtubeId: "tNh2kjmSzPw",
        channel: "ajab shahar - kabir project",
      },
      {
        titleBangla: "আমার বন্ধুর সাথে প্রেম করো",
        titleRoman: "Amar Bondhur Sathe Prem Koro",
        artist: "Parvathy Baul",
        year: 2026,
        note: "A long-form Baul performance from her own channel, unedited. Worth putting somewhere quiet on the page for people who want to stay a while.",
        youtubeId: "ZBwi-yV5MLU",
        channel: "Parvathy Baul",
      },
      {
        titleBangla: "সব লোকে কয় লালন কী জাত",
        titleRoman: "Shob Loke Koy Lalon Ki Jat",
        artist: "Arati Mukhopadhyay",
        year: null,
        note: "Everyone asks what caste Lalon is. The most necessary song in the Bengali language, and a good thing to have playing in a Puja pandal.",
        youtubeId: "lVH0C2lfktM",
        channel: "Arati Mukherjee (Topic)",
      },
      {
        titleBangla: "সব লোকে কয় লালন",
        titleRoman: "Sob Loke Koy Lalon",
        artist: "Fakira",
        year: null,
        note: "The same Lalon song in a contemporary band arrangement. Useful for showing that the fakir's question is still being asked, and still not answered.",
        youtubeId: "TaGMMbYF5yc",
        channel: "Inreco Bangla",
      },
      {
        titleBangla: "আমায় ভাসাইলি রে",
        titleRoman: "Amay Bhasaili Re",
        artist: "Abbasuddin Ahmed",
        year: null,
        note: "The great bhatiali, sung by a boatman to a river that has both floated and drowned him. If the page wants the Ganga in it, this is the sound of the Ganga.",
        youtubeId: "vwmx1Keh7tg",
        channel: "Abbas Uddin Ahamed (Topic)",
      },
      {
        titleBangla: "নদীর কূল নাই কিনার নাই",
        titleRoman: "Nodir Kul Nai Kinar Nai",
        artist: "Abbasuddin Ahmed, words by Jasimuddin",
        year: null,
        note: "The river has no bank and no edge. Jasimuddin's line and Abbasuddin's voice, the definitive statement of what a Bengali river does to a person.",
        youtubeId: "BWJNVhysc7w",
        channel: "Abbas Uddin Ahamed (Topic)",
      },
      {
        titleBangla: "এবার আমার উমা এলে",
        titleRoman: "Ebar Amar Uma Ele",
        artist: "Amar Pal",
        year: null,
        note: "Ramprasad's Agomoni sung in full folk register by a lokgeeti master. This is what Agomoni sounds like before the recording studios got hold of it.",
        youtubeId: "_f6rpEoqBgw",
        channel: "Perennial Records",
      },
      {
        titleBangla: "রাই জাগো রাই জাগো",
        titleRoman: "Rai Jago Rai Jago Bole",
        artist: "Amar Pal",
        year: null,
        note: "The pre-dawn waking song, sung by villagers walking the lanes before sunrise. The exact rural counterpart to what Akashvani does for the city on Mahalaya.",
        youtubeId: "tzNeTDxuMd4",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "জয় জয় বিজয়াগমন",
        titleRoman: "Joyo Joyo Bijoyagaman",
        artist: "Dohar and Iman Chakraborty",
        year: 2023,
        note: "Dohar's folk chorus meeting a contemporary singer for a Dashami song. Written for a film, but it walks straight back into the village it came from.",
        youtubeId: "zu07LXoyxro",
        channel: "WINDOWS",
      },
      {
        titleBangla: "পাহাড়ের রানী",
        titleRoman: "Paharer Rani",
        artist: "Josna Mahato",
        year: 2024,
        note: "Jhumur from Jhargram, the Puja music of western Bengal that Kolkata mostly forgets. Included so the village on this page is not only a riverside one.",
        youtubeId: "-Jl_MMjtNMk",
        channel: "Josna Rani Jhumur Official",
      },
      {
        titleBangla: "বঁধুয়া রিমিঝিমি এই শ্রাবণে",
        titleRoman: "Bodhuya Rimi Jhimi Ei Shrabone",
        artist: "Mita Chatterjee",
        year: null,
        note: "Monsoon drizzle and a bride's longing, sung in the palligeeti register Mita Chatterjee owns. Belongs to the village room for its rain-and-riverbank imagery rather than any city street.",
        youtubeId: "a-vKcs_kgn0",
        channel: "MELODY WIND",
      },
      {
        titleBangla: "পালকিতে বউ চলে যায়",
        titleRoman: "Palki Te Bou Chole Jai",
        artist: "Mita Chatterjee",
        year: null,
        note: "The palanquin leaving with the bride — the oldest image in Bengali folk song, and still the saddest. Village room, because the whole scene is a dirt road and a receding drumbeat.",
        youtubeId: "XDO1lj8y7wg",
        channel: "Atlantis Music",
      },
      {
        titleBangla: "ইনি বিনি টাপা টিনি",
        titleRoman: "Ini Bini Tapa Tini",
        artist: "Iman Chakraborty",
        year: 2019,
        note: "Iman Chakraborty on a folk dance tune that escaped the film entirely and became a wedding standard. Filed to the village room because the rhythm is older than any script.",
        youtubeId: "IQOF-Z4KYXI",
        channel: "Bangla Hitbox",
      },
      {
        titleBangla: "রঙ্গবতী",
        titleRoman: "Rangabati",
        artist: "Surojit Chatterjee & Iman Chakraborty",
        year: 2019,
        note: "The Sambalpuri folk classic rebuilt in Bengali for Gotro. Surojit Chatterjee's folk instincts keep it earthy even inside a film, so it belongs with the village material.",
        youtubeId: "A_PUnDNxFaE",
        channel: "Bangla Hitbox",
      },
      {
        titleBangla: "ফাগুনেরও মোহনায়",
        titleRoman: "Fagunero Mohonaye 2.0",
        artist: "Antara Nandy & Ankita Nandy",
        year: 2024,
        note: "A Goalporia folk melody given a contemporary 2.0 treatment by the Nandy sisters. The bones are Bhawaiya, so it sits in the village room despite the modern gloss.",
        youtubeId: "47BOJY1sheQ",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "আছে গৌর নিতাই নদীয়াতে",
        titleRoman: "Achhe Gour Nitai Nadiate",
        artist: "Mita Chatterjee",
        year: null,
        note: "Gour and Nitai in Nadia — Vaishnav kirtan material, sung folk-style rather than in a temple. The village room is where this belongs, not the adhunik one.",
        youtubeId: "fKh-JKFK418",
        channel: "Sweet Soom",
      },
      {
        titleBangla: "কুচবরণ কন্যা তোমার মেঘবরণ চুল",
        titleRoman: "Kuchboron Kanya Tomar Meghboron Chul",
        artist: "Srikanto Acharya",
        year: null,
        note: "Dark-skinned girl with cloud-coloured hair — a folk lyric older than anyone's recording of it. Srikanto Acharya keeps the folk contour, so it belongs in the village room.",
        youtubeId: "pusNs0E_Rh0",
        channel: "Pabitra Dharmokatha",
      },
    ],
  },
  {
    id: "funny",
    bangla: "হাসির গান",
    roman: "Hashir Gaan",
    blurb: "Pujo is mostly adda, and adda is mostly people trying to make each other laugh. Chandrabindoo's deadpan, Nachiketa's satire, Ramkumar Chattopadhyay's hymn to the luchi, and the shellac-era comic songs of Ranjit Roy and Mintoo Dasgupta that invented the whole genre. Warm throughout, and safe to play in front of anyone's grandmother.",
    tracks: [
      {
        titleBangla: "গীত গোবিন্দ",
        titleRoman: "Geet Gobindo",
        artist: "Chandrabindoo",
        year: null,
        note: "Chandrabindoo's finest piece of deadpan, a whole relationship conducted in the wrong register. The joke lands, then keeps landing on later listens.",
        youtubeId: "4IWOO9luQr4",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "আমরা বাঙালি জাতি",
        titleRoman: "Amra Bangali Jaati",
        artist: "Chandrabindoo",
        year: null,
        note: "We, the Bengali people, gently and comprehensively taken apart by three Bengalis. Affectionate, merciless, and the single best adda-starter on this list.",
        youtubeId: "E6zKpNDQQlM",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "যুযু",
        titleRoman: "Juju",
        artist: "Chandrabindoo",
        year: null,
        note: "The bogeyman song. Three minutes of absurdist nonsense delivered with a completely straight face, which is the Chandrabindoo method in miniature.",
        youtubeId: "IR6du_cY2Q4",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "রোগা বল না",
        titleRoman: "Roga Bolo Na",
        artist: "Chandrabindoo",
        year: null,
        note: "Please do not call me skinny. A small domestic grievance turned into a pop song, which is roughly ninety percent of what Chandrabindoo does.",
        youtubeId: "XeXikL8dyo8",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "ব্যাঙাখোকা",
        titleRoman: "Byanakhoka",
        artist: "Chandrabindoo, featuring Anindya Chatterjee",
        year: null,
        note: "Frog-child. Nonsense verse in the Sukumar Ray line of descent, which every Bengali child is raised on and every Bengali adult still finds funny.",
        youtubeId: "RSREUs8zhKo",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "বাথরুম",
        titleRoman: "Bathroom",
        artist: "Chandrabindoo",
        year: null,
        note: "A love song set entirely in a bathroom, sung with total sincerity. Silly in the best way and completely safe to play in front of anyone's grandmother.",
        youtubeId: "5Z8b0DtlLBk",
        channel: "Chandrabindoo (Topic)",
      },
      {
        titleBangla: "লাল বল নীল বল",
        titleRoman: "Laal Ball Neel Ball",
        artist: "Chandrabindoo (Upal Sengupta)",
        year: 2025,
        note: "Upal Sengupta on cricket, colour and the passage of time, from the band's own channel. Newer, funnier and a little sadder than it first looks.",
        youtubeId: "jCPUEx_xcV8",
        channel: "Chandrabindoo",
      },
      {
        titleBangla: "ওগো লুচি, তোমার মান্য ত্রিভুবনে",
        titleRoman: "Ogo Luchi Tomar Manyo Tribhubane",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "A formal hymn of praise addressed to the luchi. Amritalal Basu wrote it in the nineteenth century and Bengalis have not stopped agreeing with it since.",
        youtubeId: "IjwkqgVipeI",
        channel: "Perennial Records",
      },
      {
        titleBangla: "কাদের কুলের বৌ গো তুমি",
        titleRoman: "Kader Kuler Bou Go Tumi",
        artist: "Ramkumar Chattopadhyay",
        year: null,
        note: "Old Kolkata baithaki comedy, a whole neighbourhood's curiosity about a new bride compressed into three minutes. Warm, gossipy, never unkind.",
        youtubeId: "livUpNNgKVg",
        channel: "INRECO BENGALI",
      },
      {
        titleBangla: "আমি হজমি বটিকা",
        titleRoman: "Aami Hojmi Botika",
        artist: "Ranjit Roy",
        year: 1937,
        note: "A shellac-era parody in which a man introduces himself as a digestive tablet. Bengali comic song at its origin point, and genuinely still funny.",
        youtubeId: "G3zZ3lNcfmY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বুড়োকে ব্লাফ দিয়ে",
        titleRoman: "Buroke Bluff Diye",
        artist: "Mintoo Dasgupta",
        year: null,
        note: "Mintoo Dasgupta was the great Bengali parodist, setting domestic mischief to borrowed tunes. Bluffing the old man, four minutes, entirely affectionate.",
        youtubeId: "-Iu8BO4QQ8I",
        channel: "Mintoo Dasgupta (Topic)",
      },
      {
        titleBangla: "শোনো গো প্রাণের রাণু",
        titleRoman: "Sono Go Praner Ranu",
        artist: "Mintoo Dasgupta and Neela Banerjee",
        year: null,
        note: "A comic duet issued as a Pujor gaan, from the era when the Puja record releases carried the jokes as well as the romance.",
        youtubeId: "qoLyrlxtxMY",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "পেটকাটি চাঁদিয়াল",
        titleRoman: "Petkati Chandiyal",
        artist: "Kabir Suman",
        year: 1992,
        note: "Kite names as a list of everything a Kolkata childhood contained. Not a joke song exactly, but it produces the same grin, and it belongs at every adda.",
        youtubeId: "nFuXgbnvglc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "আমি মুখ্যু সুখ্যু মানুষ",
        titleRoman: "Ami Mukkhu Sukkhu Manush",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "I am a simple uneducated man, says the narrator, before demolishing everyone cleverer than him. Nachiketa's satire, sharp but never sour.",
        youtubeId: "ucJ-RRFOyKU",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "কপাল আমার মন্দ",
        titleRoman: "Kapal Amar Mondo",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "A comprehensive and very funny complaint about bad luck. The self-pity is the joke, and Nachiketa knows exactly when to let the listener in on it.",
        youtubeId: "JMlEKWyKoUk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "পচা কাকা",
        titleRoman: "Pocha Kaka",
        artist: "Bhoomi",
        year: null,
        note: "Every Bengali neighbourhood has a Pocha Kaka, and Bhoomi wrote him a theme tune. Silly, singable, and the reason this song outlives its album.",
        youtubeId: "bVdKik75E8A",
        channel: "Times Music Bangla",
      },
      {
        titleBangla: "রঞ্জনা আমি আর আসবো না",
        titleRoman: "Ranjana Ami Ar Ashbo Na",
        artist: "Anjan Dutt",
        year: null,
        note: "A breakup delivered as a shrug and a suitcase. The humour is in the timing, and by the second chorus a whole room is shouting the title back.",
        youtubeId: "tbi2eYL89Uk",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মায়া",
        titleRoman: "Maya (full album)",
        artist: "Mohiner Ghoraguli",
        year: null,
        note: "The album that invented Bengali band music, wry and shambolic and forty years ahead of itself. Includes Telephone, the funniest sad song in the language.",
        youtubeId: "cwjzEa8xrbc",
        channel: "Asha Audio",
      },
      {
        titleBangla: "গোল্ড প্রিন্টের শাড়ি পরে",
        titleRoman: "Gold Printer Sari Pore",
        artist: "Mita Chatterjee",
        year: null,
        note: "A whole comic drama about a sari and who is looking at it. Mita Chatterjee's deadpan delivery is the joke; the tune is sweet enough that nobody minds being teased.",
        youtubeId: "zoAIg8_5Cto",
        channel: "Sanatani Bangla",
      },
      {
        titleBangla: "গা ছমছম",
        titleRoman: "Ga Cham Cham",
        artist: "Mita Chatterjee",
        year: null,
        note: "A shivers-down-the-spine song played entirely for comedy. Mita Chatterjee commits to the spookiness so thoroughly that it loops back around into affection.",
        youtubeId: "PTW8xYes1lM",
        channel: "Atlantis Music",
      },
      {
        titleBangla: "মাছের কাঁটা",
        titleRoman: "Machher Kanta",
        artist: "Mita Chatterjee",
        year: null,
        note: "An entire song about a fish bone. Only Bengali comic repertoire would attempt it and only Mita Chatterjee could sell it without a wink. Deeply silly, genuinely affectionate.",
        youtubeId: "-6QFv2_X8eU",
        channel: "Atlantis Music",
      },
      {
        titleBangla: "গভীর জলের ফিশ",
        titleRoman: "Gobhir Joler Fish",
        artist: "Khoka 420",
        year: 2013,
        note: "A Bengali idiom for a sly operator, turned into a film song with a straight face. The comedy is in the phrase itself; the tune just carries it around.",
        youtubeId: "NJgIWNWz0Ho",
        channel: "Eskay Music",
      },
      {
        titleBangla: "টুম্পা",
        titleRoman: "Tumpa",
        artist: "Arijit Sorkar (Rest in প্রেম)",
        year: 2021,
        note: "The 'Tumpa sona' phenomenon in its original indie form. Affectionate, a bit crude, entirely of its moment — and the moment was a Kolkata that badly needed a joke.",
        youtubeId: "oh-btKnbTpY",
        channel: "CONFUSED Picture.",
      },
      {
        titleBangla: "লে হালুয়া লে",
        titleRoman: "Le Halua Le",
        artist: "Le Halua Le",
        year: 2012,
        note: "The title is the punchline and the whole film was named after it. Peak Bengali comic-film songwriting — nonsense phrase, enormous chorus, no interest in dignity.",
        youtubeId: "JPH8eTjKFxo",
        channel: "Release - Topic",
      },
      {
        titleBangla: "পুলিশ চোরের প্রেমে পড়েছে",
        titleRoman: "Police Chorer Preme Poreche",
        artist: "Challenge 2",
        year: 2012,
        note: "The police have fallen in love with the thief. A comic premise delivered at full volume, and a reminder that Bengali film songs used to be allowed to be ridiculous.",
        youtubeId: "TduWn57J0xk",
        channel: "SVF",
      },
      {
        titleBangla: "খোকা চালু চিজ",
        titleRoman: "Khoka Chalu Cheez",
        artist: "Khokababu",
        year: 2012,
        note: "Dev announcing his own cleverness for three minutes. The swagger is so exaggerated it reads as comedy, which is almost certainly how it was intended.",
        youtubeId: "GnDM9FvDz4E",
        channel: "Eskay Movies",
      },
      {
        titleBangla: "ময়না শুধু বলে",
        titleRoman: "Moyna Sudhu Bole",
        artist: "Mita Chatterjee",
        year: null,
        note: "The myna keeps saying it. A small affectionate joke stretched to song length, which in Mita Chatterjee's hands is exactly the right amount.",
        youtubeId: "f9ymCrcvZ3g",
        channel: "Sanatani Bangla",
      },
      {
        titleBangla: "বউ কথা কও",
        titleRoman: "Bou Katha Kou",
        artist: "Mita Chatterjee",
        year: null,
        note: "Named for the bird whose call sounds like 'wife, say something'. Bengali comic song at its most domestic — the joke and the tenderness are the same thing.",
        youtubeId: "e6hLqoLVJTE",
        channel: "Atlantis Music",
      },
    ],
  },
  {
    id: "adhunik",
    bangla: "আধুনিক",
    roman: "Adhunik",
    blurb: "Bengali modern song, which is what Bengal calls everything that is not a film song, a folk song or a hymn. Hemanta, Manna Dey, Kishore singing Bengali rather than Hindi, and the bands that came after them. None of it is about the Puja. All of it is what plays in the days around it.",
    tracks: [
      {
        titleBangla: "আমায় প্রশ্ন করে নীল ধ্রুবতারা",
        titleRoman: "Amay Prashna Kare Neel Dhrubatara",
        artist: "Bappa Mazumder",
        year: null,
        note: "Bappa Mazumder takes Hemanta's night-sky question and sings it softer, slower. A Dhaka voice on a Kolkata standard, which is exactly the kind of crossing a listening room should allow.",
        youtubeId: "NqPSSnXmodA",
        channel: "Saregama Open Stage",
      },
      {
        titleBangla: "সেই রাতে রাত ছিল পূর্ণিমা",
        titleRoman: "Sei Rate Raat Chhilo Purnima",
        artist: "Kishore Kumar",
        year: null,
        note: "Kishore in full-moon mode, Shibdas Banerjee's tune curling around him. Not a film song, just a Bengali modern song built for a verandah and a slow evening.",
        youtubeId: "4IaG5v53Of4",
        channel: "Kishore Kumaar Bangla Gaan",
      },
      {
        titleBangla: "কথা হয়েছিল",
        titleRoman: "Katha Hoyechilo",
        artist: "Mita Chatterjee",
        year: null,
        note: "Her own reading of a much-loved title — plainer than the film version, more like someone remembering the conversation than performing it. Good for the quiet stretch of an evening.",
        youtubeId: "ncDcw3nnQ2Y",
        channel: "Sweet Soom",
      },
      {
        titleBangla: "তুমি আছো এতো কাছে তাই",
        titleRoman: "Tumi Achho Eto Kachhe Tai",
        artist: "Kumar Sanu",
        year: null,
        note: "Kumar Sanu at his least showy, which is when he is best in Bengali. A modern song about proximity, sung as if the other person is actually in the room.",
        youtubeId: "CYS_WXc7EJc",
        channel: "Old Bengali Songs",
      },
      {
        titleBangla: "আমার স্বপ্ন যে",
        titleRoman: "Amar Swapno Je",
        artist: "Kishore Kumar & Lata Mangeshkar",
        year: null,
        note: "Kishore and Lata trading a dream back and forth in Bengali. Two enormous voices deliberately underplaying, which is why it still sounds intimate decades later.",
        youtubeId: "ZvpgGrFZZNI",
        channel: "INRECO BENGALI",
      },
      {
        titleBangla: "চাঁদ কেন আসেনা আমার ঘরে",
        titleRoman: "Chand Keno Asena Amar Ghore",
        artist: "Raghab Chattarjee",
        year: null,
        note: "Raghab Chattarjee asking why the moon won't come to his room. Nineties Bengali modern song at its most unguarded — big melody, no irony, and it still lands.",
        youtubeId: "rrophy3FXF0",
        channel: "MULTIPLEX BANGLA",
      },
      {
        titleBangla: "একটু বোসো চলে যেও না",
        titleRoman: "Ektu Boso Chole Jeona",
        artist: "Mita Chatterjee",
        year: null,
        note: "Sit a moment, don't go yet. The whole song is that one request, repeated with small variations, which is why it works so well late in a listening session.",
        youtubeId: "smLRqXzkkJM",
        channel: "Sweet Soom",
      },
      {
        titleBangla: "এক বৈশাখে দেখা হলো দুজনার",
        titleRoman: "Ek Baishakhe Dekha Holo Dujanar",
        artist: "Nandita",
        year: null,
        note: "Two people meeting one Baishakh. A small, well-made modern song that does not overreach, which makes it a good landing spot between louder tracks.",
        youtubeId: "26zAqjbJJTc",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "বুলবুলি",
        titleRoman: "Bulbuli",
        artist: "Ritu Raj & Nandita",
        year: 2022,
        note: "Nazrul's bulbuli, rebuilt by Coke Studio Bangla and turned into a genuine hit. Proof that Nazrulgeeti survives rearrangement better than purists usually allow.",
        youtubeId: "MY1aZQPmd8I",
        channel: "Ritu Raj - Topic",
      },
      {
        titleBangla: "এমন মধুর সন্ধ্যায়",
        titleRoman: "Emon Madhur Sandhyay",
        artist: "Mita Chatterjee",
        year: null,
        note: "Her cover of the Ekanta Apan song, sung plainer and a little slower than Asha's. Worth keeping both versions if you want listeners to notice the difference.",
        youtubeId: "t2fK09YTLs8",
        channel: "Atlantis Music",
      },
      {
        titleBangla: "আমি দূর হতে তোমারে দেখেছি",
        titleRoman: "Ami Dur Hote Tomare Dekhechi",
        artist: "Hemanta Mukherjee",
        year: null,
        note: "Hemanta watching from a distance. The definition of Bengali adhunik gaan — restrained, beautifully phrased, and completely uninterested in showing off.",
        youtubeId: "m5MnxgU8pnM",
        channel: "Sonabeej",
      },
      {
        titleBangla: "রাজশ্রী",
        titleRoman: "Rajashree",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "Nachiketa writing a whole person into three minutes, the way he does. Audio-only upload, which suits a song that never needed pictures.",
        youtubeId: "sVx8WBKQx2Y",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "যখন সময় থমকে দাঁড়ায়",
        titleRoman: "Jakhan Samay Thamke Danray",
        artist: "Nachiketa Chakraborty",
        year: null,
        note: "When time stops still. Nachiketa at his most direct, with no arrangement to hide behind — the kind of track that earns a quiet slot late in the evening.",
        youtubeId: "3TZvO1CjON0",
        channel: "Saregama Bengali",
      },
      {
        titleBangla: "মলয় বাতাসে",
        titleRoman: "Moloyo Batashe",
        artist: "Sahana Bajpaie",
        year: null,
        note: "Dwijendralal Roy's song in Sahana Bajpaie's hands — modern production, nineteenth-century writing. The best argument on this list for keeping an adhunik room at all.",
        youtubeId: "jBbpd1kVAwA",
        channel: "SVF Music",
      },
      {
        titleBangla: "বন্ধ মনের দুয়ার দিয়েছি খুলে",
        titleRoman: "Bandha Moner Duar Diyechhi Khule",
        artist: "Mita Chatterjee",
        year: null,
        note: "I have opened the closed door of my mind. A straight-faced Bengali modern song from a singer better known for comic material — worth hearing for the contrast alone.",
        youtubeId: "MQzPuF5xQe4",
        channel: "Sweet Soom",
      },
      {
        titleBangla: "তোলো ছিন্ন বীণা",
        titleRoman: "Tolo Chhinno Bina",
        artist: "Mita Chatterjee",
        year: null,
        note: "Lift up the broken veena. Older and more formal in its language than most of her catalogue, and she sings it with noticeably more restraint.",
        youtubeId: "T33AMwbrFDw",
        channel: "Sweet Soom",
      },
      {
        titleBangla: "আমি খোলা জানালা",
        titleRoman: "Ami Khola Janala",
        artist: "Srikanto Acharya",
        year: 2022,
        note: "Srikanto Acharya as an open window. Later work, and he sings it with the ease of someone who has nothing left to prove about Bengali modern song.",
        youtubeId: "oAmQ5XIE2RI",
        channel: "Shemaroo Bengali Music",
      },
      {
        titleBangla: "আমায় প্রশ্ন করে নীল ধ্রুবতারা",
        titleRoman: "Amay Prashna Kare Neel Dhrubatara",
        artist: "Srikanto Acharya",
        year: null,
        note: "The second reading of Hemanta's song on this list, this one by its most careful modern custodian. Hearing it after the Bappa Mazumder version is genuinely instructive.",
        youtubeId: "6aoNvYh7Zy4",
        channel: "Golden Music",
      },
      {
        titleBangla: "বৃষ্টি তোমাকে দিলাম",
        titleRoman: "Brishti Tomake Dilam",
        artist: "Srikanto Acharya",
        year: null,
        note: "I gave you the rain. Joy Sarkar's tune and the song that made Srikanto Acharya's name — the nineties Bengali adhunik revival in a single track.",
        youtubeId: "VhEPJkhXR1E",
        channel: "Srikanto Acharya",
      },
      {
        titleBangla: "কেনো দূরে থাকো",
        titleRoman: "Keno Dure Thako",
        artist: "Srikanto Acharya",
        year: null,
        note: "Why do you stay far away. A quiet, well-built modern song, and the lyric video means listeners who don't read Bengali can still follow it.",
        youtubeId: "4AmNsWQAeHs",
        channel: "90's Only Music",
      },
      {
        titleBangla: "যেওনা দক্ষিণ দ্বারে",
        titleRoman: "Jeo Na Dakhindware",
        artist: "Srikanto Acharya",
        year: null,
        note: "Don't go to the southern door. From the Brishti Tomake Dilam sessions — the same restraint, the same refusal to oversing a good melody.",
        youtubeId: "W36Zb76y40A",
        channel: "Shemaroo Bengali Music",
      },
      {
        titleBangla: "পথে পথে চলতে চলতে",
        titleRoman: "Pathe Pathe Cholte Cholte",
        artist: "Srikanto Acharya",
        year: null,
        note: "Walking on and on. A song about motion that never hurries, which is a hard thing to arrange and he gets it right.",
        youtubeId: "VSXR3QKqsjs",
        channel: "Shemaroo Bengali Music",
      },
      {
        titleBangla: "আমি একটু আমার সঙ্গে দেখা করতে চাই",
        titleRoman: "Ami Ektu Amar Sange Dekha Korte Chai",
        artist: "Srikanto Acharya",
        year: null,
        note: "I'd like to meet myself for a bit. The best title on this entire list, and the song earns it — small, wry, and quietly sad.",
        youtubeId: "w5SVNJ0lXVU",
        channel: "GMS official studio",
      },
      {
        titleBangla: "যেন কিছু মনে কোরো না",
        titleRoman: "Jeno Kichu Mone Kono Na",
        artist: "Srikanto Acharya",
        year: null,
        note: "From the Moner Janala album. An apology song, delivered without a trace of the self-pity the form usually invites — he simply says it and lets the melody carry the rest.",
        youtubeId: "X53VhAowXSY",
        channel: "GMS official studio",
      },
      {
        titleBangla: "আমি যামিনী তুমি শশী হে",
        titleRoman: "Ami Jamini Tumi Shashi He",
        artist: "Srikanto Acharya",
        year: null,
        note: "I am the night, you are the moon. Older, more formal writing than his own material, and he sings it with an appropriate step back in register.",
        youtubeId: "GLOQNWGfikE",
        channel: "Golden Music",
      },
    ],
  },
];

/**
 * Videos that exist, play on their own page, and refuse to play
 * inside a frame. YouTube returns 401 from the oEmbed endpoint for
 * each of these, which is the only way to find out before a visitor
 * presses play and gets silence. They are named here rather than
 * quietly dropped, so nobody re-adds them next year.
 */
export const EMBED_BLOCKED = [
  { youtubeId: "tfLPSTQPa8k", title: "Asha Chhilo Bhalobasa Chhilo" },
  { youtubeId: "E58YBAUOKXE", title: "Opare Thakbo Ami" },
  { youtubeId: "7gbfDlIs3hg", title: "Tumi Ashbe Bole" },
] as const;

export const MAHALAYA_RIGHTS = "Mahishasuramardini cannot be self-hosted, and the IISc site should not put an audio file of it on its own server. The chain of rights is unusually well documented. The script is by Bani Kumar, the music by Pankaj Kumar Mullick and the narration by Birendra Krishna Bhadra; the programme went out live on All India Radio from the mid-1930s and was committed to a definitive studio recording in 1966, which is the version broadcast ever since. Copyright therefore sits in two places at once. Prasar Bharati / All India Radio holds the broadcast and the underlying programme, and its published copyright policy (prasarbharati.gov.in/copyright-policy/) is restrictive and explicit: \"You may only access and use the material for personal or educational purposes\" and \"you may not reproduce, republish, post, transmit or distribute any material\" without written consent. That is not a licence to host or to re-serve an audio file. Separately, the commercial sound-recording rights to the 1966 master were acquired from AIR by HMV-RPG, now Saregama India Ltd, which has released it on LP, cassette, CD and digitally, and which operates the Saregama Bengali YouTube channel. Nothing in this is public domain: the 1966 recording is comfortably inside the Indian sound-recording term, and the compositions of Pankaj Mullick (d. 1978) and the text of Bani Kumar (d. 1980) are still in copyright in India as well. The one legal, zero-cost route is to EMBED the rights-holder's own YouTube upload, which is what this research recommends. Saregama Bengali's full-programme upload at youtube.com/watch?v=YQyo8QeoYhc is the rights holder publishing its own master, embedding is enabled on it (verified), and the YouTube embed carries the licence with it. There is also a channel called \"Akashvani AIR\" (UCdwm5QNss1TpY_whBkql0dw) carrying a 1966 Mahishasuramardini and a Bengali full version; it presents itself as All India Radio, but I could NOT confirm from Prasar Bharati's own site that it is an official Prasar Bharati channel, so it is listed here only as a secondary option and the Saregama upload should be preferred. Practical rule for the build: embed, never download; never rip to MP3 and serve it from the IISc domain; never put it behind a wall or over a donation prompt; and credit it on the page as \"Mahishasuramardini, All India Radio, 1966. Narration Birendra Krishna Bhadra, script Bani Kumar, music Pankaj Kumar Mullick. Recording courtesy Saregama India Ltd.\"";
